#!/bin/bash
if [ -f /swapfile ]; then
clear
test_swap=$(free -m | grep Swap | awk '{print $2}')
echo "========================================================================= "
echo "Swap already created! Swap size: $test_swap MB"
echo "-------------------------------------------------------------------------"
echo "You must delete old Swap before create the new one!"
/etc/vpssim/menu/swap/vpssim-them-xoa-swap-vps-menu
exit
fi
echo "========================================================================="
echo "Use this function to create SWAP (Vitual RAM) for server. Recommend:"
echo "-------------------------------------------------------------------------"
echo "SWAP space = Equal RAM size if RAM < 2 GB "
echo "-------------------------------------------------------------------------"
echo "SWAP space = 2 GB if RAM > 2 GB "
echo "-------------------------------------------------------------------------"
read -r -p "You want to create 512 MB swap?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
check_swap=$(free -m | grep Swap | awk '{print $2}')
dd if=/dev/zero of=/swapfile bs=1024 count=512k 
mkswap /swapfile  
swapon /swapfile
chown root:root /swapfile 
chmod 0600 /swapfile 
test_swap=$(free -m | grep Swap | awk '{print $2}')
if [ "$check_swap" == "$test_swap" ]; then
swapoff /swapfile
rm -rf /swapfile
clear 
echo "========================================================================= "
echo "Create new swap for Server failed"
echo "-------------------------------------------------------------------------"
echo "Your VPS do not support create new swap"
/etc/vpssim/menu/swap/vpssim-them-xoa-swap-vps-menu
else
  if [ "$(grep "/swapfile    none    swap    sw    0    0" /etc/fstab | awk '{print $1}')" == "" ]; then
echo "/swapfile    none    swap    sw    0    0" >> /etc/fstab  
  fi 
clear 
echo "========================================================================= "
echo "Successfully created Swap: 512 MB"
/etc/vpssim/menu/swap/vpssim-them-xoa-swap-vps-menu
fi
       ;;
    *)
       clear
/etc/vpssim/menu/swap/vpssim-them-xoa-swap-vps-menu
        ;;
esac




