#!/bin/bash 

. /home/vpssim.conf
prompt="Type in your choice: "
php_version=$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")
if [ "$php_version" == "5.6" ]; then
options=( "PHP 7.0" "PHP 5.6 (Current)" "PHP 5.5" "PHP 5.4" "Exit")
elif [ "$php_version" == "5.5" ]; then
options=( "PHP 7.0" "PHP 5.6" "PHP 5.5 (Current)" "PHP 5.4" "Exit")
elif [ "$php_version" == "5.4" ]; then
options=( "PHP 7.0" "PHP 5.6" "PHP 5.5" "PHP 5.4 (Current)" "Exit")
else
options=( "PHP 7.0 (Current)" "PHP 5.6" "PHP 5.5" "PHP 5.4" "Exit")
fi
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                    Choose PHP Version for Server\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) chonphpversion="70"; break;;
    2) chonphpversion="56"; break;;
    3) chonphpversion="55"; break;;
    4) chonphpversion="54"; break;;
    5) chonphpversion="Cancel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
  
    esac  
done
###################################
#7.0
###################################
if [ "$chonphpversion" = "70" ]; then
/etc/vpssim/menu/nangcap-php/setup-php-70
###################################
#5.6
###################################
elif [ "$chonphpversion" = "56" ]; then
/etc/vpssim/menu/nangcap-php/setup-php-56
###################################
#5.5
###################################
elif [ "$chonphpversion" = "55" ]; then
/etc/vpssim/menu/nangcap-php/setup-php-55
###################################
#5.4
###################################
elif [ "$chonphpversion" = "54" ]; then
/etc/vpssim/menu/nangcap-php/setup-php-54
else 
clear && /etc/vpssim/menu/vpssim-update-upgrade-service-menu
fi
