#!/bin/sh 
. /home/vpssim.conf
curTime=$(date +%d)
checktruenumber='^[0-9]+$'
if [ $(id -u) != "0" ]; then
    printf "Error ! VPSSIM run only with root user !\n"
    exit
fi


if [ ! -f /tmp/00-all-nginx-version.txt ]; then
touch -a -m -t 201601180130.09 /tmp/00-all-nginx-version.txt  
fi

fileTime=$(date -r /tmp/00-all-nginx-version.txt +%d)
if [ ! "$fileTime" == "$curTime" ]; then
rm -rf /tmp/00-all-nginx-version.txt
wget -q https://vpssim.com/script/vpssim/00-all-nginx-version.txt -O /tmp/00-all-nginx-version.txt
touch /tmp/00-all-nginx-version.txt
Nginx1=`cat /etc/vpssim/nginx.version`
checksize=$(du -sb /tmp/00-all-nginx-version.txt | awk 'NR==1 {print $1}')
if [ $checksize -gt 14 ]; then
Nginx3=`cat /tmp/00-all-nginx-version.txt | awk 'NR==2 {print $1}' | sed 's/|//' | sed 's/|//'`
cat >> "/tmp/vpssim_check_nginx" <<END
		if [  "$(grep $Nginx1 /tmp/00-all-nginx-version.txt | sed 's/|//' | sed 's/|//')" == "$Nginx1" ]; then
			if [ ! "$Nginx1" == "$Nginx3" ]; then
			echo "========================================================================="
			echo "Update for Nginx Found !  "
			echo "-------------------------------------------------------------------------"
			echo "Your Version: $Nginx1   |   Newest version: $Nginx3"
			echo "-------------------------------------------------------------------------"
			echo "How to update: VPSSIM menu => Update System => Change Nginx Version "
			
			fi
		fi
END
chmod +x /tmp/vpssim_check_nginx
/tmp/vpssim_check_nginx
rm -rf /tmp/vpssim_check_nginx
fi
fi

if [ ! -f /tmp/vpssim.newversion ]; then
touch -a -m -t 201602180130.09 /tmp/vpssim.newversion  
fi
fileTime2=$(date -r /tmp/vpssim.newversion +%d)
if [ ! "$fileTime2" == "$curTime" ]; then
rm -rf /tmp/vpssim.newversion
wget -q https://vpssim.com/script/vpssim/vpssim.newversion -O /tmp/vpssim.newversion
touch /tmp/vpssim.newversion
LOCALVER=`cat /etc/vpssim/vpssim.version`
checksize=$(du -sb /tmp/vpssim.newversion | awk 'NR==1 {print $1}')
###
	if [ $checksize -gt 2 ]; then
	REMOVER=`cat /tmp/vpssim.newversion`
	cat >> "/tmp/vpssim_check_vpssim_version" <<END
		if [ ! "$LOCALVER" == "$REMOVER" ]; then
			echo "========================================================================="
			echo "Update for VPSSIM found !  "
			echo "-------------------------------------------------------------------------"
			echo "Your Version: $LOCALVER   |   Newest version: $REMOVER"
			echo "-------------------------------------------------------------------------"
			echo "How to update: VPSSIM menu => Update System => Update VPSSIM "
			
		fi
END
	chmod +x /tmp/vpssim_check_vpssim_version
	/tmp/vpssim_check_vpssim_version
	rm -rf /tmp/vpssim_check_vpssim_version

	fi
fi

if [ ! -f /etc/vpssim/tatthongbao.csf ]; then
if [ ! -f /etc/csf/csf.conf ]; then
echo "========================================================================="
echo "WARNING ! YOU SHOULD SETUP CSF FIREWALL TO PROTECT VPS/SERVER !"
echo "========================================================================="
echo "This warning auto Disable after server has CSF installed. Or Disable by"
echo "========================================================================="
echo "[ OFF/ON Warning On Menu ] function on [ CSF Firewall Manage ] "
fi
fi
rm -rf /tmp/*ip*
who am i| awk '{ print $5}' | sed 's/(//'| sed 's/)//' > /tmp/checkip
checksize=$(du -sb /tmp/checkip | awk 'NR==1 {print $1}')
if [ $checksize -gt 8 ]; then
if [ -f /etc/csf/csf.conf ]; then
checkip=$(cat /tmp/checkip)
	if [ ! -f /etc/csf/csf.ignore ]; then
	echo "" > /etc/csf/csf.ignore
	fi
if [ "$(grep $checkip /etc/csf/csf.ignore)" == "" ]; then 
cat >> "/tmp/addcheckip" <<END
echo "$checkip" >> /etc/csf/csf.ignore
echo "$checkip" >> /etc/csf/csf.allow
echo "========================================================================="
echo "Your current IP dddress:  $checkip" 
echo "-------------------------------------------------------------------------"
echo "This IP address do not exit in CSF Firewwall's whitelist "
echo "-------------------------------------------------------------------------"
echo "VPSSIM has added it to CSF whitelist to prevent this IP blocked by CSF"
echo "-------------------------------------------------------------------------"
echo "To take effect for this change, CSF Firewall must be restart"
echo "========================================================================="
read -p "Press [Enter] to restart CSF Firewall and go to VPSSIM menu ..."
#iptables -I INPUT -p tcp --dport $priport -j ACCEPT
#iptables -A INPUT -p tcp -s $checkip --dport $priport -j ACCEPT
#service iptables save
#service iptables restart
/etc/vpssim/menu/CSF-Fiwall/vpssim-re-start-khoi-dong-lai-csf-lfd
clear
echo "========================================================================="
echo "IP: $checkip added to CSF Firewall's Whitelist"
END
chmod +x /tmp/addcheckip
/tmp/addcheckip
fi
fi
fi

if [ ! -f /etc/vpssim/minfreedisc.info ]; then
echo "1000" > /etc/vpssim/minfreedisc.info
fi
minfreedisc=`cat /etc/vpssim/minfreedisc.info`
if ! [[ $minfreedisc =~ $checktruenumber ]] ; then
echo "1000" > /etc/vpssim/minfreedisc.info
fi 
if [ ! -f /tmp/checkdiscsize ]; then
touch -a -m -t 201602180130.09 /tmp/checkdiscsize 
fi

fileTime3=$(date -r /tmp/checkdiscsize +%d)
if [ ! "$fileTime3" == "$curTime" ]; then
touch /tmp/checkdiscsize
disfree=$(calc $(df $PWD | awk '/[0-9]%/{print $(NF-2)}')/1024)
	if [[ $disfree =~ $checktruenumber ]] ; then  
	  if [ "$disfree" -lt "$minfreedisc" ]; then
	  touch /tmp/checkdiscsize
echo "========================================================================="
echo "Warning: Free disk space of server has only $disfree MB ! "
	  fi
   fi
fi

rm -rf /tmp/*ip*
rm -rf /tmp/showthongbao 
#find /etc/vpssim/menu -type f -exec chmod 755 {} \;
prompt="Type in your choice:"
options=("Add Website & Code" "Remove Website" "Backup & Restore Code" "Database Manage" "PhpMyadmin Manage" "Zend OPcache Manage" "Memcached Manage" "Redis Cache Manage"  "FTP Server Manage" "Swap Manage" "Cronjob Manage"  "Log File Manage" "Change PHP Settings" "Wordpress Blog Tools" "CSF Firewall Manage" "IPtables Firewall Manage" "BitTorrent Sync Manage" "VPS Backup Manage" "Linux Malware Detect" "Setup File Manager" "Setup Net2FTP" "Setup NetData" "Setup SSL (Let's Enctypt)" "Check & Block IP DOS" "Tools - Addons" "Update System" "Clear All Caches" "Default User & Password" "Server Status" "Exit")

echo "========================================================================="
echo "            VPSSIM - Manage VPS/Server by VPSSIM.COM ($(cat /etc/vpssim/vpssim.version))               "
echo "========================================================================="
echo "                             VPSSIM Menu                                "
echo "========================================================================="

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

	1) clear && /etc/vpssim/menu/vpssim-befor-them-website-menu;;
    2) /etc/vpssim/menu/vpssim-befor-xoa-website;;
    3) clear && /etc/vpssim/menu/vpssim-sao-luu;;
    4) clear && /etc/vpssim/menu/vpssim-befor-them-xoa-database;;
    5) clear && /etc/vpssim/menu/vpssim-phpmyadmin-menu;;
    6) clear && /etc/vpssim/menu/opcache/vpssim-before-opcache;;
    7) clear && /etc/vpssim/menu/memcache/vpssim-before-memcache-menu;;
    8) clear && /etc/vpssim/menu/vpssim-redis-befor-menu;;
    9) clear &&/etc/vpssim/menu/vpssim-ftpserver-menu;;
    10 )clear && /etc/vpssim/menu/swap/vpssim-them-xoa-swap-vps-menu;;
    11) clear && /etc/vpssim/menu/crontab/vpssim-cronjob-menu;;
    12) clear && /etc/vpssim/menu/vpssim-eroor-menu;;
    13) clear && /etc/vpssim/menu/vpssim-befor-vpssim-config-php.ini-menu;;
    14) clear && /etc/vpssim/menu/vpssim-wordpress-tools-menu;;
    #14) clear && /etc/vpssim/menu/pagespeed/before-vpssim-pagespeed-menu;;"Nginx Pagespeed Manage" 
    15) /etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-before-menu;;
    16) clear && /etc/vpssim/menu/vpssim-iptables-firewall-manager-menu;;
    17) clear && /etc/vpssim/menu/vpssim-bitsync-menu;;
    18) clear && /etc/vpssim/menu/vpssim-befor-rsync;;
    19) clear && /etc/vpssim/menu/vpssim-maldet-menu;;
    20) clear && /etc/vpssim/menu/vpssim-web-upload-menu;;
    21) clear && /etc/vpssim/menu/vpssim-net2ftp-menu;;
    22) clear && /etc/vpssim/menu/vpssim-netdata-menu;;
    23) clear && /etc/vpssim/menu/vpssim-letsencrypt-menu;;
    24) clear && /etc/vpssim/menu/vpssim-kiem-tra-ddos;;
    25) clear && /etc/vpssim/menu/vpssim-tien-ich;;
    26) clear && /etc/vpssim/menu/vpssim-update-upgrade-service-menu;;
    27) /etc/vpssim/menu/vpssim-clear-cache-xoa-cache-server;;
    28) /etc/vpssim/menu/vpssim-dat-mat-khau-bao-ve-folder-mac-dinh;;
    29) clear && /etc/vpssim/menu/vpssim-vps-info;;
	30) clear && cat /etc/motd && killall -g vpssim;; 
 *) echo "You typed wrong, please type in the ordinal number on the list";continue;;

    esac
done
