#!/bin/bash

. /home/vpssim.conf
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
    rm -rf /tmp/*list*
   cd /home
find . -type f -print0 | xargs -0 du | sort -n | tail -5 | cut -f2 | xargs -I{} du -sh {} > /tmp/listfile
find . -type d -print0 | xargs -0 du | sort -n | tail -5 | cut -f2 | xargs -I{} du -sh {} > /tmp/listfolder
cd
clear
echo "========================================================================="
echo "List 5 Largest Files In /home:"
echo "-------------------------------------------------------------------------"
cat /tmp/listfile
echo "-------------------------------------------------------------------------"
echo "List 5 Largest Directories In /home:"
cat /tmp/listfolder
rm -rf /tmp/*list*
/etc/vpssim/menu/vpssim-tien-ich
