#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to view all Iptables Firewall Rules Of this Server"
echo "-------------------------------------------------------------------------"
read -r -p "You want to view Iptables Firewall Rules ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ...";sleep 1
rm -rf /home/$mainsite/private_html/IPtablesRules*
randomcode=`date |md5sum |cut -c '1-16'`
echo "============================================================================" > /home/$mainsite/private_html/IPtablesRules-$randomcode.txt
echo "IPtables Firewall Rules in Server: $serverip - Created by VPSSIM " >> /home/$mainsite/private_html/IPtablesRules-$randomcode.txt
echo "============================================================================" >>/home/$mainsite/private_html/IPtablesRules-$randomcode.txt
echo "" >> /home/$mainsite/private_html/IPtablesRules-$randomcode.txt
iptables-save >> /home/$mainsite/private_html/IPtablesRules-$randomcode.txt
clear
echo "========================================================================= "
echo "Link View IPtables Firewall Rules:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/IPtablesRules-$randomcode.txt"
/etc/vpssim/menu/vpssim-iptables-firewall-manager-menu
        ;;
    *)
       clear
/etc/vpssim/menu/vpssim-iptables-firewall-manager-menu
        ;;
esac


