#!/bin/bash

. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to view 5 largest files and directories in website "
echo "-------------------------------------------------------------------------"
nhapduieu () {
echo -n "Type in the website [ENTER]: " 
read website
if [ "$website" = "" ]; then
echo "-------------------------------------------------------------------------"
echo "You typed wrong, Please type in accurately!"
echo "-------------------------------------------------------------------------"
nhapduieu
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
echo "-------------------------------------------------------------------------"
echo "Can not discover $website "
echo "-------------------------------------------------------------------------"
nhapduieu
fi   
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 2
rm -rf /tmp/*list*
clear  
cd /home/$website/public_html
find . -type f -print0 | xargs -0 du | sort -n | tail -5 | cut -f2 | xargs -I{} du -sh {} > /tmp/listfile
find . -type d -print0 | xargs -0 du | sort -n | tail -5 | cut -f2 | xargs -I{} du -sh {} > /tmp/listfolder
cd
echo "========================================================================="
echo "List 5 Largest Files In /home/$website/public_html:"
echo "-------------------------------------------------------------------------"
cat /tmp/listfile
echo "-------------------------------------------------------------------------"
echo "List 5 Largest Directories In /home/$website/public_html:"
echo "-------------------------------------------------------------------------"
cat /tmp/listfolder
rm -rf /tmp/*list*
/etc/vpssim/menu/vpssim-tien-ich
exit
}
nhapduieu
