#!/bin/bash 
. /home/vpssim.conf
if [ -f /usr/local/bin/htop ]; then
clear
echo "========================================================================= "
echo "HTOP was installed  "
echo "-------------------------------------------------------------------------"
echo "Run HTOP by using command: htop "
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [ -f /usr/bin/htop ]; then
clear
echo "========================================================================= "
echo "HTOP was installed  "
echo "-------------------------------------------------------------------------"
echo "Run HTOP by using command: htop "
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
echo "========================================================================="
echo "Htop is utilities to view server status like [ top -c ] but more detail"
echo "-------------------------------------------------------------------------"
echo "Use this function to install htop for server. "
echo "-------------------------------------------------------------------------"
read -r -p "You want to install htop ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ...";sleep 1
cd /tmp
wget -q --no-check-certificate https://vpssim.com/script/vpssim/Softwear/htop-2.0.0.tar.gz
tar xvfvz htop-2.0.0.tar.gz
cd /tmp/htop-2.0.0
./configure
make
make install
cd
if [ -f /usr/local/bin/htop ]; then
clear
echo "========================================================================="
echo "Installed HTOP Successfully "
echo "-------------------------------------------------------------------------"
echo "Run HTOP by using command: htop "
else
clear
echo "========================================================================="
echo "Install htop failed"
echo "-------------------------------------------------------------------------"
echo "Please try again! "
fi
/etc/vpssim/menu/vpssim-tien-ich
        ;;
    *)
       clear
/etc/vpssim/menu/vpssim-tien-ich
        ;;
esac
