#!/bin/sh
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpssim/menu/tienich/vpssim-ioncube-cai-dat-remove
	else
	echo "-------------------------------------------------------------------------"
service php-fpm start
			if [ "$(/sbin/service php-fpm status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpssim/menu/tienich/vpssim-ioncube-cai-dat-remove
		else
clear
echo "========================================================================="
echo "PHP-FPM Stopped !"
echo "-------------------------------------------------------------------------"
echo "You can not install or remove Ioncube Loader"
/etc/vpssim/menu/vpssim-tien-ich
		fi
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
	if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
/etc/vpssim/menu/tienich/vpssim-ioncube-cai-dat-remove
	else
systemctl start php-fpm.service
	if [ "`systemctl is-active php-fpm.service`" == "active" ]; then
/etc/vpssim/menu/tienich/vpssim-ioncube-cai-dat-remove
		else
clear
echo "========================================================================="
echo "PHP-FPM Stopped !"
echo "-------------------------------------------------------------------------"
echo "You can not install or remove Ioncube Loader"
/etc/vpssim/menu/vpssim-tien-ich
		fi
fi
fi
