#!/bin/bash
. /home/vpssim.conf
if [ ! -f /etc/vpssim/iptables.bak ]; then
clear
echo "========================================================================="
echo "VPSSIM can not find the backup of IPtables Firewall Rules !"
/etc/vpssim/menu/vpssim-iptables-firewall-manager-menu
exit
fi
echo "--------------------------------------------------------------------------"
echo "Discover the backup of IPtable Firewall rules"
echo "--------------------------------------------------------------------------"
echo "Backup file created on: $(date -r /etc/vpssim/iptables.bak +%H:%M/%F)"
echo "--------------------------------------------------------------------------"
read -r -p "Do you want restore all rules from this backup ? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
echo "--------------------------------------------------------------------------"
echo "Please wait...."
sleep 1
iptables-restore < /etc/vpssim/iptables.bak
service iptables save

clear
echo "========================================================================="
echo "Restore the IPtables Firewall Rules finished !"
/etc/vpssim/menu/vpssim-iptables-firewall-manager-menu
else
clear
echo "========================================================================="
echo "Cancel restore IPtables Firewall Rules !"
/etc/vpssim/menu/vpssim-iptables-firewall-manager-menu
fi
