#!/bin/sh
. /home/vpssim.conf
prompt="Type in your choice (6-Exit):"
options=("Enable Opcache" "Config Zend Opcache" "Add Website To BlackList" "Remove Website From Blacklist" "Clear Zend OPcache")
printf "=========================================================================\n"
printf "                 VPSSIM - Manage VPS/Server by VPSSIM.COM             \n"
printf "=========================================================================\n"
printf "                           Zend OPcache Manage \n"
printf "=========================================================================\n"
printf "                      Zend Opcache Status: Disable\n"
printf "=========================================================================\n"
printf "Zend Opcache Manage Link: http://$serverip:$priport/ocp.php\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" "Exit"; do 

    case "$REPLY" in
    1 ) /etc/vpssim/menu/opcache/vpssim-bat-opcache;;
    2 ) /etc/vpssim/menu/opcache/vpssim-opcache-change-size;;
    3) /etc/vpssim/menu/opcache/vpssim-them-website-vao-blacklist;;
    4) /etc/vpssim/menu/opcache/vpssim-xoa-website-khoi-blacklist;;
    5) /etc/vpssim/menu/opcache/vpssim-clear-opcache;;

    
    $(( ${#options[@]}+1 )) ) echo "";  clear && /bin/vpssim;;
    *) echo "You typed in wrong, Please type in the ordinal number on the list";continue;;

    esac
done
