#!/bin/bash 
. /home/vpssim.conf
if [ -f /etc/php.d/opcache.ini ]; then
clear
echo "========================================================================="
echo "               VPSSIM - Manage VPS/Server by VPSSIM.COM      "       
echo "========================================================================="
echo "                         Config Zend OPcache"
echo "========================================================================="
echo ""
echo ""

cleartime=$(grep opcache.revalidate_freq /etc/php.d/opcache.ini | grep -o '[0-9]*')
echo "Go to http://$serverip:$priport/ocp.php to see RAM Opcache need"
echo "========================================================================="
echo "RAM for Opcache must be a number within range of (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/5))."
echo "-------------------------------------------------------------------------"
echo -n "Type in the RAM size you config for Zend Opcache use [ENTER]: " 
read opcacheram

if [ "$opcacheram" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please fill accurately"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi

if ! [[ $opcacheram -ge 20 && $opcacheram -le $(calc $( free -m | awk 'NR==2 {print $2}' )/5)  ]] ; then  
clear
echo "========================================================================="
echo "$opcacheram is wrong!"
echo "-------------------------------------------------------------------------"
echo "RAM for Opcache must be a number within range of (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/5))."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi  
echo "-------------------------------------------------------------------------"
echo "Counting the number of php files on VPS "
sleep 1
echo "========================================================================="
echo "Current PHP files in Home folder: $(find /home -type f | grep php | wc -l) files"
echo "MAX FILES is the max of PHP files can be cached by Zend Opcache "
echo "MAX FILES must be a number within range of (2000 - 70000)."
echo "-------------------------------------------------------------------------"
echo -n "Type in MAX FILES [ENTER]: " 
read filephp
if [ "$filephp" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please fill accurately"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi

if ! [[ $filephp -ge 2000 && $filephp -le 70000  ]] ; then 
clear
echo "========================================================================="
echo "$filephp is wrong!"
echo "-------------------------------------------------------------------------"
echo "MAX FILES must be a number within range of (2000 - 70000)."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi  
echo "========================================================================="
echo "Current auto clear Zend Opcache  time: $cleartime seconds"
echo "This time larger, VPS has better performance"
echo "Auto Clear PHP cache time must be a number within range of (30 - 999999)."
echo "-------------------------------------------------------------------------"
echo -n "Type in Auto clear Zend Opcache time [ENTER]: " 
read timeclear
if [ "$timeclear" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please fill accurately"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi

if ! [[ $timeclear -ge 30 && $timeclear -le 999999  ]] ; then 
clear
echo "========================================================================="
echo "$timeclear is wrong !"
echo "-------------------------------------------------------------------------"
echo "Auto Clear Opcache time must be a number within range of (30 - 999999)."
echo "-------------------------------------------------------------------------"
echo "Please fill accurately !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi  

echo "Please wait....";sleep 2
sed --in-place '/opcache.memory_consumption/d' /etc/php.d/opcache.ini
sed --in-place '/opcache.max_accelerated_files/d' /etc/php.d/opcache.ini
sed --in-place '/opcache.revalidate_freq/d' /etc/php.d/opcache.ini
###
echo "opcache.memory_consumption=$opcacheram" >> /etc/php.d/opcache.ini
echo "opcache.max_accelerated_files=$filephp" >> /etc/php.d/opcache.ini
echo "opcache.revalidate_freq=$timeclear" >> /etc/php.d/opcache.ini

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else
systemctl restart php-fpm.service
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
test_php=$(/sbin/service php-fpm status | awk 'NR==1 {print $3}')
if [ "$test_php" == "stopped" ]; then
clear
echo "========================================================================="
echo "You config Wrong ! Please re-config again."
echo "-------------------------------------------------------------------------"
echo "Website is 502 error now !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
test_php=$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')
if [ "$test_php" == "inacctive" ]; then
clear
echo "========================================================================="
echo "You config Wrong ! Please re-config again."
echo "-------------------------------------------------------------------------"
echo "Website is 502 error now !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
test_php=$(/bin/systemctl status  php-fpm.service | awk 'NR==3 {print $2}')
if [ "$test_php" == "failed" ]; then
clear
echo "========================================================================="
echo "You config Wrong ! Please re-config again."
echo "-------------------------------------------------------------------------"
echo "Website is 502 error now !"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi
fi
clear
echo "========================================================================="
echo "Configed Zend Opcache using $opcacheram MB RAM"
echo "-------------------------------------------------------------------------"
echo "Max PHP file Zend Opcache can cache = $filephp"
echo "-------------------------------------------------------------------------"
echo "PHP cached will be clear every $timeclear seconds"
/etc/vpssim/menu/opcache/vpssim-before-opcache
fi
clear
echo "========================================================================= "
echo "Zend OPcache is disable in VPS"
echo "-------------------------------------------------------------------------"
echo "Lets enable Opcache to get the best VPS productivity"
/etc/vpssim/menu/opcache/vpssim-before-opcache
exit
fi
