#!/bin/bash
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $5}')" == "running..." ]; then
echo "-------------------------------------------------------------------------"
echo "Please wait....";sleep 1
echo "flush_all" | nc 127.0.0.1 11211
clear
echo "========================================================================= "
echo "Clear memcached Successfully"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
else
clear
echo "========================================================================= "
echo "Memcacche is Disable in your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ "`systemctl is-active memcached.service`" == "active" ]; then
echo "-------------------------------------------------------------------------"
echo "Please wait....";sleep 1
echo "flush_all" | nc 127.0.0.1 11211
clear
echo "========================================================================= "
echo "Clear memcached Successfully"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
else
clear
echo "========================================================================= "
echo "Memcacche is Disable in your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi
