#!/bin/bash
. /home/vpssim.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
chkconfig memcached off
service memcached stop
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl disable memcached.service
systemctl stop  memcached.service
fi
echo "-------------------------------------------------------------------------"
echo "Please wait....";sleep 1
clear
echo "========================================================================= "
echo "Stop memcached Successfully"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
