#!/bin/bash 
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
if [ "$(/sbin/service memcached status | awk 'NR==1 {print $3}')" == "stopped" ]; then
clear
echo "========================================================================= "
echo "Memcached is Disable in your Server"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
if [ ! "`systemctl is-active memcached.service`" == "active" ]; then
clear
echo "========================================================================= "
echo "Memcached is Disable in your server"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
fi

if [ -f /etc/sysconfig/memcached ]; then
echo "========================================================================="
echo "Use this function to config the Maximum RAM that Memcached can use"
echo "-------------------------------------------------------------------------"
echo "RAM for Memcached must be a number within range of (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/7))."
echo "-------------------------------------------------------------------------"
echo -n "Type in the RAM size for Memcached [ENTER]: " 
read memcacheram
if [ "$memcacheram" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please fill accurately"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
if ! [[ $memcacheram -ge 20 && $memcacheram -le $(calc $( free -m | awk 'NR==2 {print $2}' )/7)  ]] ; then  
clear
echo "========================================================================="
echo "$memcacheram is wrong!"
echo "-------------------------------------------------------------------------"
echo "RAM for Memcached must be a number within range of (20 - $(calc $( free -m | awk 'NR==2 {print $2}' )/7))."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi  
        
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
rm -rf /etc/sysconfig/memcached
cat > "/etc/sysconfig/memcached" <<END
PORT="11211"
USER="memcached"
MAXCONN="10024"
CACHESIZE="$memcacheram"
OPTIONS=""
END
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service memcached restart
fi
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
systemctl restart memcached.service
fi
clear
echo "========================================================================="
echo "Config successfully Memcached use $memcacheram MB RAM"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
clear
echo "========================================================================= "
echo "Memcached does not detect on your VPS"
/etc/vpssim/menu/memcache/vpssim-before-memcache-menu
exit
fi
