#!/bin/bash 
if [ -f /etc/csf/csf.conf ]; then
printf "=========================================================================\n"
printf "CSF Firewall should be installed to protect VPS/Server.\n"
echo "-------------------------------------------------------------------------"
read -r -p "Are you sured want to uninstall CSF Firewall? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Prepare to remove CSF Firewall... "
sleep 1
cd /etc/csf
sh uninstall.sh
cd
clear
clear
echo "========================================================================= "
echo "Remove CSF Firewall from Server successfully "

/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
;;
    *)
       clear 
echo "========================================================================= "
echo "You cancel remove CSF FIREWALL"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
        ;;
esac
clear 
echo "========================================================================= "
echo "You cancel remove CSF FIREWALL"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
else
clear
echo "========================================================================= "
echo "Your server is not installed CSF Firewall yet ! "
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi



