#!/bin/bash 
. /home/vpssim.conf
versioncaidat_csf=$(csf -v | awk 'NR==1 {print $NF}')
if [ "$versioncaidat_csf" == "enable" ]; then
clear
echo  "CSF Firewall is disabled on VPS."
echo "-------------------------------------------------------------------------"
echo "Please enable it before using this function!"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi
versiononline_csf=$(csf -c | awk 'NR==1 {print $NF}')
versioncaidat_csf2=$(csf -v | awk 'NR==1 {print $2}')
if [ ! "$versioncaidat_csf2" == "$versiononline_csf" ]; then
echo "Please wait....";sleep 1
csf -u
clear
echo "========================================================================="
echo  "You have updated CSF Firewall to the newest version."
echo "-------------------------------------------------------------------------"
echo  "Version: $(csf -v | awk 'NR==1 {print $2}')"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
else
clear
echo "========================================================================="
echo  "CSF Firewall is in Newest version."
echo "-------------------------------------------------------------------------"
echo  "Version:  $(csf -v | awk 'NR==1 {print $2}' | sed 's/v//')"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi


