#!/bin/bash 

. /home/vpssim.conf
if [ -f /etc/csf/csf.conf ]; then
csf -e
clear
echo "========================================================================= "
echo "Successfully enable CSF - Firewall "
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
else
echo "========================================================================= "
echo "This funcion run with CSF Firewall"
echo "-------------------------------------------------------------------------"
echo "CSF Firewall is not installed ! "
echo "-------------------------------------------------------------------------"
read -r -p "Do you want to install CSF Firewall on this VPS [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
/etc/vpssim/menu/CSF-Fiwall/vpssim-cai-dat-csf-csf
;;
esac
clear
echo "========================================================================= "
echo "You cancel install CSF Firewall ! "
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
