#!/bin/bash 
. /home/vpssim.conf
rm -rf /tmp/vpssimcheckcountrycode*
echo "========================================================================="
if [ -f /etc/csf/csf.conf ]; then
test_csf=$(csf -v | awk 'NR==1 {print $NF}')
if [ "$test_csf" == "enable" ]; then
echo "This function will enable CSF firewall if you are disabling it on server"
echo "-------------------------------------------------------------------------" 
fi
#Multiple countries can be comma separated with no spaces in between, such as “US,GB,DE” to deny access to the US, Great Britain, and Germany.
echo "Use this function to block countries using the CSF Firewall."
echo "-------------------------------------------------------------------------" 
echo "You need type in 2 letter Country Codes. Multiple countries can be comma  "
echo "-------------------------------------------------------------------------" 
echo "separated with no spaces in between, such as “CN,RU,DE” to deny access "
echo "-------------------------------------------------------------------------" 
echo "to the China, Russia, and Germany."
echo "-------------------------------------------------------------------------" 
echo "View list country codes at: https://vpssim.com/country-codes.txt"
echo "========================================================================="
echo -n "Type in country code [ENTER]: " 
read countrycode
countrycode=`echo $countrycode | tr '[a-z]' '[A-Z]'`
countrycode=`echo $countrycode | sed 's/\///' | sed 's/\///' | sed 's/\///'`
#| sed 's/\ //' | sed 's/\ //' | sed 's/\ //' | sed 's/\ //' | sed 's/\ //' | sed 's/\ //' | sed 's/\ //' | sed 's/\ //' | sed 's/\ //'
echo "$countrycode" > /tmp/vpssimcheckcountrycode
sed -i 's/,$//' /tmp/vpssimcheckcountrycode
sed -i 's/,$//' /tmp/vpssimcheckcountrycode
sed -i 's/,$//' /tmp/vpssimcheckcountrycode
sed -i 's/,$//' /tmp/vpssimcheckcountrycode
sed -i 's/,$//' /tmp/vpssimcheckcountrycode
sed -i 's/,$//' /tmp/vpssimcheckcountrycode
sed -i 's/,$//' /tmp/vpssimcheckcountrycode
cat /tmp/vpssimcheckcountrycode | awk -F, '{for (i=1;i<=NF;i++)print $i}' > /tmp/vpssimcheckcountrycode_list
if [ ! "$(grep ";" /tmp/vpssimcheckcountrycode)" = "" ]; then
clear
echo "========================================================================= "
echo "You can not use [ ; ]"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi
if [ "$countrycode" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please fill accurately"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi

if [ ! "$(grep "\ " /tmp/vpssimcheckcountrycode)" = "" ]; then
clear
echo "========================================================================= "
echo "You can not use [ space ]."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi
if [ ! "$(grep "\." /tmp/vpssimcheckcountrycode)" = "" ]; then
clear
echo "========================================================================= "
echo "You can not use [ . ]"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi
rm -rf /tmp/vpssimcheckcountrycode_list_show
rm -rf /tmp/vpssimcheckcountrycode_code_trung_nhau
rm -rf /tmp/vpssimcheckcountrycode_code_trung_nhau2
country_list=`cat /tmp/vpssimcheckcountrycode_list`

for manuoc in $country_list; do
 
 if [ ! ${#manuoc}  == "2" ]; then 
clear
echo "========================================================================= "
echo "Country code $manuoc does not exit."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi

if [ "$(grep "|${manuoc}|" /etc/vpssim/menu/CSF-Fiwall/vpssim-country-code)" = "" ]; then
clear
echo "========================================================================= "
echo "Country code $manuoc does not exit."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
else
echo "$(grep "|${manuoc}|" /etc/vpssim/menu/CSF-Fiwall/vpssim-country-code | sed "s/|${manuoc}|//")" >> /tmp/vpssimcheckcountrycode_list_show
fi

echo "${manuoc}" >> /tmp/vpssimcheckcountrycode_code_trung_nhau
grep "${manuoc}" /tmp/vpssimcheckcountrycode_code_trung_nhau > /tmp/vpssimcheckcountrycode_code_trung_nhau2
codetrungnhau=`cat /tmp/vpssimcheckcountrycode_code_trung_nhau2`
if [ ! ${#codetrungnhau} = "2" ]; then 
clear
echo "========================================================================= "
echo "Country code $manuoc appears more than once in the list you typed in."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi

done
sonuoc=`cat /tmp/vpssimcheckcountrycode_list_show | wc -l`
if [ ! "$sonuoc" = 1 ]; then
nuoc=countries
hoithoai1=`echo "The list of $nuoc you want to block by CSF Firewall:"`
hoithoai2=`echo "You want to block $sonuoc $nuoc in the list ?"`
else
nuoc=country
hoithoai1=`echo "The $nuoc you want to block by CSF Firewall:"`
hoithoai2=`echo "You want to block this country ?"`
fi
echo "========================================================================="
echo "$hoithoai1"
echo "-------------------------------------------------------------------------"
cat /tmp/vpssimcheckcountrycode_list_show | pr -2 -t
echo "========================================================================="
  read -r -p "$hoithoai2 [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ...";sleep 1
sed -i "s/.*CC_DENY\ =.*/CC_DENY = \"$(cat /tmp/vpssimcheckcountrycode)\"/g" /etc/csf/csf.conf
if [ "$test_csf" == "enable" ]; then
csf -e
fi
csf -r
clear
echo "========================================================================="
echo "Config CSF Firewall block $sonuoc $nuoc finished."
echo "-------------------------------------------------------------------------"
echo "$nuoc List:"
echo "-------------------------------------------------------------------------"
cat /tmp/vpssimcheckcountrycode_list_show | pr -2 -t
rm -rf /tmp/vpssimcheckcountrycode*
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
;;
    *)
clear 
echo "========================================================================= "
echo "Cancel !"
rm -rf /tmp/vpssimcheckcountrycode*
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
        ;;
esac
else
echo "========================================================================= "
echo "This funcion run with CSF Firewall."
echo "-------------------------------------------------------------------------"
echo "CSF Firewall is not installed ! "
echo "-------------------------------------------------------------------------"
read -r -p "Do you want to install CSF Firewall on this VPS [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
/etc/vpssim/menu/CSF-Fiwall/vpssim-cai-dat-csf-csf
;;
esac
clear
echo "========================================================================= "
echo "You cancel install CSF Firewall ! "
/etc/vpssim/menu/CSF-Fiwall/vpssim-csf-firewall-menu
exit
fi




