#!/bin/sh

prompt="Type in your choice (5-Exit):"
options=("Add crontab" "Delete crontab" "Clear all crontab" "Crontab running" "Exit")
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                            Cronjob Manage\n"
echo "========================================================================="
if [ ! -f /var/spool/cron/root ]; then
printf "                           Crontab running: 0 \n"
else
printf "                           Crontab running: $(wc -l /var/spool/cron/root | awk '{print $1}') \n"
fi
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1 ) /etc/vpssim/menu/crontab/vpssim-them-cronjob;;
    2 ) /etc/vpssim/menu/crontab/vpssim-xoa-mot-crontab;;
    3 ) /etc/vpssim/menu/crontab/vpssim-befor-xoa-het-cronjob;;
    4 ) /etc/vpssim/menu/crontab/vpssim-crontab-hien-tai;;
    5 ) clear && /bin/vpssim;;
    
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac
done

