#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "This function will update Centos system, MariaDB and PHP-FPM."
echo "-------------------------------------------------------------------------"
read -r -p "Do you want to update? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
echo "-------------------------------------------------------------------------"
echo "Prepare to update ..... "
sleep 1
yum -y update
yum -y upgrade
rm -rf /tmp/*opcache*
if [ -f /etc/php.d/opcache.bak ]; then
yes | cp -rf /etc/php.d/opcache.bak /tmp
fi
if [ -f /etc/php.d/opcache.ini ]; then
yes | cp -rf /etc/php.d/opcache.ini /tmp
fi
rm -rf /etc/php-zts.d/*opcache*
rm -rf /etc/php.d/*opcache*
yum -y upgrade php\*
rm -rf /tmp/abc.txt
rm -rf /etc/php-zts.d/*opcache*
rm -rf /etc/php.d/*opcache*
if [ -f /tmp/opcache.bak ]; then
yes | cp -rf /tmp/opcache.bak /etc/php.d
fi
if [ -f /tmp/opcache.ini ]; then
yes | cp -rf /tmp/opcache.ini /etc/php.d
fi
rm -rf /tmp/*opcache*
chmod 777 /var/lib/php/session/
clear
echo "========================================================================="
echo "Update done !"
/etc/vpssim/menu/vpssim-update-upgrade-service-menu
;;
esac
rm -rf /tmp/abc.txt
clear
echo "========================================================================="
echo "You cancel update Centos system, MariaDB and PHP-FPM !"
/etc/vpssim/menu/vpssim-update-upgrade-service-menu
exit
fi
