#!/bin/sh
. /home/vpssim.conf
echo "-------------------------------------------------------------------------"
echo "Please wait..."; sleep 1
clear
echo "========================================================================="
echo "You Can Access To PHPmyadmin Link Below:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport"
/etc/vpssim/menu/vpssim-phpmyadmin-menu
