#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to restore database for wordpress website"
echo "========================================================================="
echo -n "Type in website: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website!"
echo "-------------------------------------------------------------------------"
echo "Please try again"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ -f /home/$website/public_html/wp-config-sample.php ]; then
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website has wordpress code but not install yet !"
echo "-------------------------------------------------------------------------"
echo "Please setup wordpress first and try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
fi
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website is not wordpress blog!"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi

dataname=`cat /home/$website/public_html/wp-config.php | grep DB_NAME | cut -d \' -f 4`
randomwp=`date |md5sum |cut -c '1-18'`
echo "$website" > /tmp/vpssim-tensitephuchoi
echo "$dataname" > /tmp/vpssim-tendatabasephuchoi
date -r /var/lib/mysql/$dataname +%H%M%S> /tmp/vpssim1
randomcode=`date |md5sum |cut -c '1-12'`
if [ ! -f /home/$mainsite/private_html/backup/$dataname/*.sql.gz ]; then
     
   if [ -f /home/$website/public_html/VPSSIM-DATABASE.tar.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-tar-gz-wordpress
   elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-gz-wordpress
   elif [ -f /home/$website/public_html/VPSSIM-DATABASE.zip ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-zip-wordpress
   elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-wordpress
   else
	clear
	echo "========================================================================="
	echo "HOW TO RESTORE DATABASE"
	echo "========================================================================="
	echo "VPSSIM support Backup File format: .SQL, .ZIP, .SQL.GZ va .TAR.GZ"
	echo "-------------------------------------------------------------------------"
	echo "Depending on the Backup file format, you do:"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .SQL    => Rename backup file to VPSSIM-DATABASE.sql"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .ZIP    => Rename backup file to VPSSIM-DATABASE.zip"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .SQL.GZ => Rename backup file to VPSSIM-DATABASE.sql.gz"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .TAR.GZ => Rename backup file to VPSSIM-DATABASE.tar.gz"
	echo "-------------------------------------------------------------------------"
	echo "Then upload to:"
	echo "-------------------------------------------------------------------------"
	echo "/home/$website/public_html/"
	echo "========================================================================="
	read -p "When Upload finish. Press [Enter] to Restore..."
	echo "-------------------------------------------------------------------------"
	echo "VPSSIM finding Backup file  .... "
	echo "-------------------------------------------------------------------------"
	sleep 4
	if [ -f /home/$website/public_html/VPSSIM-DATABASE.tar.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-tar-gz-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-gz-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.zip ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-zip-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-wordpress
    else
	clear
		echo "========================================================================="
		echo "Can not discover backup file of database $dataname !"
		echo "-------------------------------------------------------------------------"
		echo "Please upload Backup file to server then try again"
		/etc/vpssim/menu/vpssim-wordpress-tools-menu
		exit
		fi
		fi
else
find /home/$mainsite/private_html/backup/$dataname -name '*.sql.gz' -type f -exec basename {} \;  > /tmp/backupname
if [ ! "$(cat /tmp/backupname | wc -l)" == "1" ]; then
clear
echo "========================================================================="
echo "There are more than 1 backup file in SQL.GZ format in: "
echo "-------------------------------------------------------------------------"
echo "/home/$mainsite/private_html/backup/$dataname"
echo "-------------------------------------------------------------------------"
echo "Please leave one single file .SQL.GZ in this folder"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
filename=`cat /tmp/backupname`
rm -rf /tmp/backupname
echo "========================================================================="
echo "Discover the backup of $dataname: $filename"
echo "-------------------------------------------------------------------------"
echo "Backup file created on: $(date -r /home/$mainsite/private_html/backup/$dataname/$filename +%H:%M/%F)"
echo "========================================================================="
prompt="Type in your choice: "
options=( "Restore database from backup file $filename" "Restore database from other Backup file" "Cancel")
printf "CHON HOW TO RESTORE DATABASE\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) luachonphuchoi="phuchoitufilebackup"; break;;
    2) luachonphuchoi="uploadsaudophuchoi"; break;;
    3) luachonphuchoi="cancel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
###################################
#phuchoitufilebackup
###################################
if [ "$luachonphuchoi" = "phuchoitufilebackup" ]; then
echo "--------------------------------------------------------------------------"
echo "Please wait ...."
echo "--------------------------------------------------------------------------"
echo "VPSSIM dang Restore $dataname.........."
sleep 3
gunzip < /home/$mainsite/private_html/backup/$dataname/$filename | mysql -u root -p$mariadbpass $dataname
date -r /var/lib/mysql/$dataname +%H%M%S> /tmp/vpssim2
check1=`cat /tmp/vpssim1`
check2=`cat /tmp/vpssim2`
	if [ "$check1" == "$check2" ]; then
	rm -rf /tmp/*vpssim*
	sleep 8
	clear
	echo "========================================================================="
		echo "Restore $dataname failed "
		echo "-------------------------------------------------------------------------"
		echo "Please check your backup file and try again !"
	/etc/vpssim/menu/vpssim-wordpress-tools-menu
	else	
   rm -rf /tmp/*vpssim*
	
	clear
	echo "========================================================================="
	echo "Restore database $dataname successfully!"
	/etc/vpssim/menu/vpssim-wordpress-tools-menu
	fi
###################################
#Upload file backup len va Restore tu file nay
###################################
elif [ "$luachonphuchoi" = "uploadsaudophuchoi" ]; then
randomcode=`date |md5sum |cut -c '1-12'`
	if [ -f /home/$website/public_html/VPSSIM-DATABASE.tar.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-tar-gz-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-gz-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.zip ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-zip-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-wordpress
    else
	clear
	echo "========================================================================="
	echo "HOW TO RESTORE DATABASE"
	echo "========================================================================="
	echo "VPSSIM support Backup File format: .SQL, .ZIP, .SQL.GZ va .TAR.GZ"
	echo "-------------------------------------------------------------------------"
	echo "Depending on the Backup file format, you do:"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .SQL    => Rename backup file to VPSSIM-DATABASE.sql"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .ZIP    => Rename backup file to VPSSIM-DATABASE.zip"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .SQL.GZ => Rename backup file to VPSSIM-DATABASE.sql.gz"
	echo "-------------------------------------------------------------------------"
	echo "Backup File .TAR.GZ => Rename backup file to VPSSIM-DATABASE.tar.gz"
	echo "-------------------------------------------------------------------------"
	echo "Then upload to:"
	echo "-------------------------------------------------------------------------"
	echo "/home/$website/public_html/"
	echo "========================================================================="
	read -p "When Upload finish. Press [Enter] to Restore..."
	echo "-------------------------------------------------------------------------"
	echo "VPSSIM finding Backup file  .... "
	echo "-------------------------------------------------------------------------"
	sleep 4
	if [ -f /home/$website/public_html/VPSSIM-DATABASE.tar.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-tar-gz-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql.gz ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-gz-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.zip ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-zip-wordpress
    elif [ -f /home/$website/public_html/VPSSIM-DATABASE.sql ]; then
   /etc/vpssim/menu/vpssim-phuc-hoi-database-vpssim-database-sql-wordpress
    else
	clear
		echo "========================================================================="
		echo "Can not discover backup file of database $dataname !"
		echo "-------------------------------------------------------------------------"
		echo "Please upload Backup file to server then try again"
		/etc/vpssim/menu/vpssim-wordpress-tools-menu
		exit
		fi
fi
###################################
#Huy bo phuchoi
###################################
else 
clear && /etc/vpssim/menu/vpssim-wordpress-tools-menu
fi
fi
