#!/bin/bash
. /home/vpssim.conf

if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
clear
echo "========================================================================= "
echo "FTP server is not installed "
echo "-------------------------------------------------------------------------"
echo "You must run Setup FTP server function first !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
echo "========================================================================="
echo "Use this function to view FTP account infomation for website"
echo "-------------------------------------------------------------------------"
echo -n "Type in the website [ENTER]: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please type in accurately !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website"
echo "-------------------------------------------------------------------------"
echo "Please try again ."
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
if [ "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "There's no FTP account for $website !"
/etc/vpssim/menu/vpssim-ftpserver-menu
fi
echo "========================================================================="
echo "Discover $website in system"
echo "-------------------------------------------------------------------------"
echo "$website was created FTP account"
echo "-------------------------------------------------------------------------"
echo "VPSSIM getting info"
echo "-------------------------------------------------------------------------"
echo "Please wait...."
sleep 5
clear
echo "========================================================================="
echo "The FTP account's login info for $website:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip"
echo "-------------------------------------------------------------------------"
echo "Username: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"
/etc/vpssim/menu/vpssim-ftpserver-menu
