#!/bin/sh
if [ ! -f /usr/local/bin/htpasswd.py ]; then
cp -r /etc/vpssim/menu/vpssim-tao-mat-khau-bao-ve-folder.py /usr/local/bin/htpasswd.py
chmod 755 /usr/local/bin/htpasswd.py
fi
if [ ! -d /etc/nginx/pwprotect ]; then
mkdir -p /etc/nginx/pwprotect
fi
if [ ! -f /etc/vpssim/pwprotect.default ]; then
echo "" > /etc/vpssim/pwprotect.default
fi
echo "========================================================================="
prompt="Type in your choice: "
options=( "Enable/Disable Protect Directory" "Create Default Username & Password" "Cancel")
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) luachonacction="taomatkhau"; break;;
    2) luachonacction="taomatkhaumacdinh"; break;;
    3) chonphpversion="cancel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done

###################################
if [ "$luachonacction" = "taomatkhau" ]; then
/etc/vpssim/menu/vpssim-dat-mat-khau-bao-ve-folder-website
###################################
elif [ "$luachonacction" = "taomatkhaumacdinh" ]; then
/etc/vpssim/menu/vpssim-dat-mat-khau-bao-ve-folder-mac-dinh
###################################
else 
clear && /etc/vpssim/menu/vpssim-tien-ich
fi
