#!/bin/bash

. /home/vpssim.conf
if [ ! -f /etc/vpssim/uploadsite ]; then
clear
echo "========================================================================="
echo "You have not installed File Manager for Server !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
uploadsite=$(cat /etc/vpssim/uploadsite)
echo "========================================================================= "
echo "Use this function to change Username & Password for Admin account of "
echo "-------------------------------------------------------------------------"
echo "File manager. VPSSIM will create new Username & Password without knowning "
echo "-------------------------------------------------------------------------"
echo "the old username & password."
echo "========================================================================= "
read -r -p "You want to create new login info for Admin user ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
#############
echo "-------------------------------------------------------------------------"
echo -n "Type in new Admin user  [ENTER]: " 
read adminupload
if [ "$adminupload" = "" ]; then
echo "========================================================================="
echo "You must type in the user Admin."
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
if [[ ! ${#adminupload} -ge 5 ]]; then
clear
echo "========================================================================="
echo "User Admin must be at least 5 characters long "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 
checkuseradmin="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
if [[ ! "$adminupload" =~ $checkuseradmin ]]; then
clear
echo "========================================================================="
echo "You must use only numbers, letters for user admin."
echo "-------------------------------------------------------------------------"
echo "Please try again  !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 

echo "-------------------------------------------------------------------------"
echo -n "Type in the password [ENTER]: "
read matkhau
if [ "$matkhau" = "" ]; then
clear
echo "========================================================================="
echo "You must type in the password."
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
#checkpass="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
#if [[ ! "$matkhau" =~ $checkpass ]]; then
#clear
#echo "========================================================================="
#echo "Ban chi duoc dung chu cai va so de dat mat khau."
#echo "-------------------------------------------------------------------------"
#echo "Ban vui long thu lai  !"
#/etc/vpssim/menu/vpssim-web-upload-menu
#exit
#fi
if [[ ! ${#matkhau} -ge 8 ]]; then
clear
echo "========================================================================="
echo "Password must be at least 8 characters long "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 
#######
echo "-------------------------------------------------------------------------"
echo "New Admin login info for File Manager:"
echo "-------------------------------------------------------------------------"
echo "Username: $adminupload | Password: $matkhau"
echo "-------------------------------------------------------------------------"
echo "Please wait ..."; sleep 3
rm -rf /home/$uploadsite/public_html/config/.htusers.php
cat > "/home/$uploadsite/public_html/config/.htusers.php" <<END
<?php
        // ensure this file is being included by a parent file
        if( !defined( '_JEXEC' ) && !defined( '_VALID_MOS' ) ) die( 'Restricted access' );
        \$GLOBALS["users"]=array(
        array('$adminupload','$(echo -n $matkhau | md5sum | cut -d" " -f1)','/home','http://localhost','1','','7',1),
);
?>
END
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else 
systemctl restart php-fpm.service
fi
clear
echo "========================================================================="
echo "Changing Login info for File Manager finished."
echo "-------------------------------------------------------------------------"
echo "Username: $adminupload | Password: $matkhau"
/etc/vpssim/menu/vpssim-web-upload-menu
;;
esac
clear
echo "========================================================================="
echo "Cancel !"
/etc/vpssim/menu/vpssim-web-upload-menu
