#!/bin/bash

. /home/vpssim.conf
serverversion=`/root/.acme.sh/acme.sh --version | awk 'NR==2' | sed 's/v//'`
echo "========================================================================="
echo "Check latest Version ..."; sleep 3
rm -rf /etc/vpssim/.tmp/checkupdate_acme.sh
mkdir -p /etc/vpssim/.tmp/checkupdate_acme.sh
cd /etc/vpssim/.tmp/checkupdate_acme.sh
wget -q https://codeload.github.com/Neilpang/acme.sh/zip/master
unzip -q master
airversion=$(grep VER= /etc/vpssim/.tmp/checkupdate_acme.sh/acme.sh-master/acme.sh | sed 's/VER=//')
rm -rf /etc/vpssim/.tmp/checkupdate_acme.sh
cd

if [ "$serverversion" = "$airversion" ]; then
clear
echo "========================================================================="
echo "You do not need to upgrade Acme.sh ."
echo "-------------------------------------------------------------------------"
echo "Latest Version: $serverversion"
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi
clear
echo "========================================================================="
/root/.acme.sh/acme.sh --upgrade
version=`/root/.acme.sh/acme.sh --version | awk 'NR==2' | sed 's/v//'`
echo "-------------------------------------------------------------------------"
echo "Latest Version: $version"
rm -rf /etc/vpssim/.tmp/check_crontab_acme
crontab -l > /etc/vpssim/.tmp/check_crontab_acme
if [ ! "$(grep "/root/.acme.sh" /etc/vpssim/.tmp/check_crontab_acme)" = "" ]; then
/root/.acme.sh/acme.sh --uninstallcronjob
fi
rm -rf /etc/vpssim/.tmp/check_crontab_acme
sleep 3
/etc/vpssim/menu/vpssim-letsencrypt-menu
