#!/bin/bash
. /home/vpssim.conf
cd /etc/nginx/conf.d
ls > /tmp/websitelist
sed -i 's/\.conf//g' /tmp/websitelist
cd
rm -rf /tmp/wordpresslist
acction1="/tmp/websitelist"
while read -r wpsite
    do
if [ -f /home/$wpsite/public_html/wp-config.php ]; then
echo "$wpsite" >> /tmp/wordpresslist
fi
 done < "$acction1"
 if [ ! -f /tmp/wordpresslist ]; then
clear
echo "========================================================================="
 echo "VPSSIM can not find website running wordpress code in this server"
 /etc/vpssim/menu/vpssim-wordpress-tools-menu
 exit
 fi
echo "========================================================================="
#prompt="Nhap lua chon cua ban: "
prompt="Type in your choice: "
options=( "Update PLugins" "Update Themes" "Cancel")
printf "CHOOSE UPDATE PLUGINS OR THEMES\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) luachonupdate="updateplugin"; break;;
    2) luachonupdate="updatethemes"; break;;
    3) luachonupdate="cancel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    
    esac  
done
###################################
#Update plugin
###################################
if [ "$luachonupdate" = "updateplugin" ]; then

sositewp=$(cat /tmp/wordpresslist | wc -l)
/etc/vpssim/menu/vpssim-re-config-cac-ham-php-disable-php.ini
echo "========================================================================="
echo "There are $sositewp websites running wordpress code on system" 
echo "-------------------------------------------------------------------------"
echo "VPSSIM will update check and update all plugins in this $sositewp website"
sleep 1
acction2="/tmp/wordpresslist"
while read -r wpwebsite
    do
if [ -f /home/$wpwebsite/public_html/wp-config.php ]; then
chown -R nginx:nginx /home/$wpwebsite/public_html/wp-content/plugins
cd /home/$wpwebsite/public_html
#echo "========================================================================="
#echo "Update Status For: $wpwebsite"
/etc/vpssim/menu/vpssim-enable-tat-ca-cac-ham-php-php.ini
wp plugin update --all --allow-root | grep Success: > /tmp/update-plugins-status
chown -R nginx:nginx /home/$wpwebsite/public_html/wp-content/plugins
   if [ "$(cat /tmp/update-plugins-status)" = "Success: Updated 0/0 plugins." ]; then
echo "-------------------------------------------------------------------------"
echo "$wpwebsite: 0 plugin need update"
rm -rf /tmp/update-plugins-status
  else
  echo "-------------------------------------------------------------------------"
echo "$wpwebsite: $(cat /tmp/update-plugins-status | sed 's/Success://')"
rm -rf /tmp/update-plugins-status
cd
  fi
  fi
done < "$acction2"
rm -rf /tmp/wordpresslist
/etc/vpssim/menu/vpssim-re-config-cac-ham-php-disable-php.ini
echo "-------------------------------------------------------------------------"
     if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
     service php-fpm restart
     else
     systemctl restart php-fpm.service
     fi 
###################################
#Update tat ca themes
###################################
elif [ "$luachonupdate" = "updatethemes" ]; then
sositewp=$(cat /tmp/wordpresslist | wc -l)
/etc/vpssim/menu/vpssim-enable-tat-ca-cac-ham-php-php.ini
echo "========================================================================="
echo "There are $sositewp websites running wordpress code on system" 
echo "-------------------------------------------------------------------------"
echo "VPSSIM will update check and update all Themes in this $sositewp website"
sleep 1
acction2="/tmp/wordpresslist"
while read -r wpwebsite
    do
if [ -f /home/$wpwebsite/public_html/wp-config.php ]; then
chown -R nginx:nginx /home/$wpwebsite/public_html/wp-content/themes
cd /home/$wpwebsite/public_html
echo "========================================================================="
echo "Update Status For: $wpwebsite"
wp theme update --all --allow-root | grep Success: > /tmp/update-themes-status
chown -R nginx:nginx /home/$wpwebsite/public_html/wp-content/themes
   if [ "$(cat /tmp/update-themes-status)" = "Success: Updated 0/0 themes." ]; then
echo "-------------------------------------------------------------------------"
echo "$wpwebsite: 0 Themes need update"
rm -rf /tmp/update-themes-status
  else
  echo "-------------------------------------------------------------------------"
echo "$wpwebsite: $(cat /tmp/update-themes-status | sed 's/Success://')"
rm -rf /tmp/update-themes-status
cd
  fi
  fi
done < "$acction2"
rm -rf /tmp/wordpresslist
/etc/vpssim/menu/vpssim-re-config-cac-ham-php-disable-php.ini
echo "-------------------------------------------------------------------------"
     if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
     service php-fpm restart
     else
     systemctl restart php-fpm.service
     fi 
###################################
#Huy bo update
###################################
else 
clear && /etc/vpssim/menu/vpssim-wordpress-tools-menu
fi
