#!/bin/bash
. /home/vpssim.conf 
if [ -f /etc/vsftpd/vsftpd.conf ]; then
clear
echo "========================================================================= "
echo "VSFTPD has been installed on this server ! "
echo "-------------------------------------------------------------------------"
echo "To use the full functionality of FTP Server Manage in VPSSIM"
echo "-------------------------------------------------------------------------"
echo "Vsftpd will be removed !"
sleep 8
clear
echo "-------------------------------------------------------------------------"
echo "Please wait .............."
sleep 3
yum -y remove vsftpd
fi
if [ -f /etc/proftpd.conf ]; then
clear
echo "====================================== =================================== "
echo "ProFTPD has been installed on this server !"
echo "-------------------------------------------------------------------------"
echo "To use the full functionality of FTP Server Manage in VPSSIM"
echo "-------------------------------------------------------------------------"
echo "ProFTPD will be removed !"
sleep 8
clear
echo "-------------------------------------------------------------------------"
echo "Please wait .............."
sleep 3
yum -y remove proftpd
fi
if [ ! -f /etc/vpssim/menu/vpssim-ftpserver-read ]; then
clear
printf "=========================================================================\n"
printf "                  VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                              FTP Server Manage\n"
printf "=========================================================================\n"
echo ""

echo "========================================================================="
echo "Use this function to setup FTP Server over TLS for server"
echo "-------------------------------------------------------------------------"
echo "After setup FTP Server, you can create FTP account for all websites in "
echo "-------------------------------------------------------------------------"
echo "server. By default, you can not login FTP to server using root account"
echo "-------------------------------------------------------------------------"
echo "if you want to login to Server by root account, you must use sFTP"
echo "-------------------------------------------------------------------------"
echo "Login to server by sFTP follow infomation:"
echo "-------------------------------------------------------------------------"
echo "Host: sftp://$serverip"
echo "-------------------------------------------------------------------------"
echo "User: root | Password: Your_password "
echo "-------------------------------------------------------------------------"
echo "Port: Port SSH (default 22 - or new Port SSH you have changed)"
echo "-------------------------------------------------------------------------"
touch /etc/vpssim/menu/vpssim-ftpserver-read
read -p "Press [Enter] to continue ..."
clear
fi
if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
/etc/vpssim/menu/vpssim-ftpserver-menu-khong
else
/etc/vpssim/menu/vpssim-ftpserver-menu-co
fi
