#!/bin/bash 

. /home/vpssim.conf
echo "========================================================================="
echo "Use this to Enable/Disable [Block Exploits, SQL Injections] for Website"
#echo "-------------------------------------------------------------------------"
#echo "You should Enable this function for all websites in server "  
#echo "-------------------------------------------------------------------------"
#echo "However, If website has a Plugin (extension) not compatible with this"
#echo "-------------------------------------------------------------------------"
#echo "config, you should disable this function or re-config the rule "
echo "-------------------------------------------------------------------------"
echo "Edit rules at: /etc/nginx/conf/block.conf"
echo "========================================================================="
nhapdulieu() {
echo -n "Type in website: "  
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
echo "========================================================================="
echo "You typed wrong, please type in accurately"
echo "-------------------------------------------------------------------------"
nhapdulieu
fi

if [ -f /etc/vpssim/net2ftpsite.info ]; then
net2ftpsite=$(cat /etc/vpssim/net2ftpsite.info)
if [ "$website" = "$net2ftpsite" ]; then
clear
echo "========================================================================="
echo "$website is Net2FTP domain"
echo "-------------------------------------------------------------------------"
echo "You can not use this function."
/etc/vpssim/menu/vpssim-tien-ich
fi
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
echo "========================================================================="
echo "$website maybe not a domain name !"
echo "-------------------------------------------------------------------------"
nhapdulieu
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
if [ ! -f /etc/nginx/conf.d/www.$website.conf ]; then
echo "========================================================================="
echo "Can not discover $website in server "
echo "-------------------------------------------------------------------------"
nhapdulieu
fi
fi

if [ -f /etc/nginx/conf.d/www.$website.conf ]; then
if [ "$(grep block.conf /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
clear
echo "========================================================================="
echo "You have changed default Vhost config for $website"
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not finish your request"
/etc/vpssim/menu/vpssim-block-exploits-sql-injections-menu
exit
fi
fi
if [ -f /etc/nginx/conf.d/$website.conf ]; then
if [ "$(grep block.conf /etc/nginx/conf.d/$website.conf)" == "" ]; then
clear
echo "========================================================================="
echo "You have changed default Vhost config for $website"
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not finish your request"
/etc/vpssim/menu/vpssim-block-exploits-sql-injections-menu
exit
fi
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
if [ "$(grep "#include /etc/nginx/conf/block.conf;" /etc/nginx/conf.d/$website.conf)" == "" ]; then
check=1
fi
fi

if [ -f /etc/nginx/conf.d/wwww.$website.conf ]; then
if [ "$(grep "#include /etc/nginx/conf/block.conf;" /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
check=1
fi
fi

if [ ! "$check" == "1" ]; then
echo "========================================================================="
echo "$website current DISABLE [Block Exploits, SQL Injections]"
echo "-------------------------------------------------------------------------"
read -r -p "You want to Enable this function ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait..."   		
    sleep 1
    cat > "/tmp/blocksqlinection.sh" <<END
#!/bin/sh
if [ -f /etc/nginx/conf.d/$website.conf ]; then
sed -i 's/.*block.conf.*/include \/etc\/nginx\/conf\/block.conf;/g' /etc/nginx/conf.d/$website.conf
fi
if [ -f /etc/nginx/conf.d/www.$website.conf ]; then
sed -i 's/.*block.conf.*/include \/etc\/nginx\/conf\/block.conf;/g' /etc/nginx/conf.d/www.$website.conf
fi
END
chmod +x /tmp/blocksqlinection.sh
/tmp/blocksqlinection.sh
rm -f /tmp/blocksqlinection.sh
clear
 
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx restart
else
systemctl restart nginx.service
fi
clear
echo "========================================================================="
echo "ENABLE [Block Exploits, SQL Injections] for $website successfully!"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
    *)
       clear
    echo "========================================================================="
   echo "Cancel Enable [Block Exploits, SQL Injections] for $website"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
esac
exit
fi

echo "========================================================================="
echo "$website current ENABLE [Block Exploits, SQL Injections]"
echo "-------------------------------------------------------------------------"
read -r -p "You want to Disable this function ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    		echo "-------------------------------------------------------------------------"
		echo "Please wait..."
		sleep 1
    cat > "/tmp/blocksqlinection.sh" <<END
#!/bin/sh
if [ -f /etc/nginx/conf.d/$website.conf ]; then
sed -i 's/.*block.conf.*/#include \/etc\/nginx\/conf\/block.conf;/g' /etc/nginx/conf.d/$website.conf
fi
if [ -f /etc/nginx/conf.d/www.$website.conf ]; then
sed -i 's/.*block.conf.*/#include \/etc\/nginx\/conf\/block.conf;/g' /etc/nginx/conf.d/www.$website.conf
fi
END
chmod +x /tmp/blocksqlinection.sh
/tmp/blocksqlinection.sh
rm -f /tmp/blocksqlinection.sh
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx restart
else
systemctl restart nginx.service
fi
clear
echo "========================================================================="
echo "DISABLE [Block Exploits, SQL Injections] for $website successfully!"
/etc/vpssim/menu/vpssim-tien-ich
       ;;
    *)
    clear
    echo "========================================================================="
   echo "Cancel Disable [Block Exploits, SQL Injections] for $website"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
esac
exit
}
nhapdulieu
