#!/bin/bash 

. /home/vpssim.conf

prompt="Type in your choice: "
options=( "Add Redirect Domain" "Add Park Domain" "Exit")
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) choose="redirect"; break;;
    2) choose="park"; break;;
    3) choose="Cancel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
if [ "$choose" = "redirect" ]; then
/etc/vpssim/menu/vpssim-redirect-domain
elif [ "$choose" = "park" ]; then
/etc/vpssim/menu/vpssim-park-domain
else 
clear && /etc/vpssim/menu/vpssim-them-website-menu
fi
