#!/bin/bash 
. /home/vpssim.conf
if [ ! -f /etc/vpssim/vps_backup_rsync.info ]; then
clear
echo "========================================================================="
echo "This server has not configured connect to VPS Backup yet"
echo "-------------------------------------------------------------------------"
echo "You must using option #1 to config connect to VPS Backup first."
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi
echo "========================================================================="
echo "Use this function to change password user root for VPS backup"
echo "-------------------------------------------------------------------------"
read -r -p "You want to change login info for user root in vps backup ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
ipvpsbackup=$(grep "ipaddress" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')
echo "-------------------------------------------------------------------------"
echo "Connecting to VPS Backup ... "
checkconnect=$(ssh -o BatchMode=yes -o ConnectTimeout=9 root@$ipvpsbackup echo connected 2>&1)
if [[ ! $checkconnect == connected ]] ; then
clear
echo "========================================================================="
echo "Connection Failed !"
echo "-------------------------------------------------------------------------"
echo "You can not use this function"
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi
echo "-------------------------------------------------------------------------"
echo -n "Type in the new password [ENTER]: " 
read PASS1
if [ "$PASS1" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please fill accurately."
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi
echo "-------------------------------------------------------------------------"
echo -n "Re-type in the password [ENTER]: " 
read PASS2
if [ "$PASS1" != "$PASS2" ]; then
clear
echo "========================================================================="
echo "Sorry, passwords do not match !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi
echo "-------------------------------------------------------------------------"
ipvpsbackup=$(grep "ipaddress" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')
cat > "/tmp/change-password-user-root-vps-backup" <<END
if [ -f /etc/lsb-release ]; then
echo "root:$PASS1" | chpasswd
elif [ -f /etc/debian_version ]; then
echo "root:$PASS1" | chpasswd
elif [ -f /etc/redhat-release ]; then
echo "$PASS1" | passwd --stdin root
else
echo "$PASS1" | passwd --stdin root
fi
END
rsync -avzq -e ssh /tmp/change-password-user-root-vps-backup root@$ipvpsbackup:/tmp/change-password-user-root-vps-backup
ssh root@$ipvpsbackup chmod +x /tmp/change-password-user-root-vps-backup
ssh root@$ipvpsbackup /tmp/change-password-user-root-vps-backup
ssh root@$ipvpsbackup rm -rf /tmp/change-password-user-root-vps-backup
rm -rf /tmp/change-password-user-root-vps-backup
if [ -f ~/.ssh/known_hosts ]; then
if [ ! "$(grep "$ipvpsbackup" ~/.ssh/known_hosts)" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "sed -i '/$ipvpsbackup/d' ~/.ssh/known_hosts" > /tmp/knownhost_sedit
chmod +x /tmp/knownhost_sedit
/tmp/knownhost_sedit
rm -rf /tmp/knownhost_sedit
fi
fi
cat > "/tmp/rsync_ketnoi" <<END
sshpass -p '$PASS1' ssh-copy-id -i ~/.ssh/id_rsa.pub $ipvpsbackup > /tmp/abc
END
chmod +x /tmp/rsync_ketnoi
/tmp/rsync_ketnoi
rm -rf /tmp/rsync_ketnoi
checkconnect=$(ssh -o BatchMode=yes -o ConnectTimeout=9 root@$ipvpsbackup echo connected 2>&1)
if [[ ! $checkconnect == connected ]] ; then
clear
echo "========================================================================="
echo "Connection Failed !"
echo "-------------------------------------------------------------------------"
echo "You can not use this function"
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi

clear
echo "========================================================================="
echo "Change password for root user in VPS backup successfully !"
echo "-------------------------------------------------------------------------"
echo "New password is: $PASS1"
echo "-------------------------------------------------------------------------"
echo "If you can not login to VPS Backup via SSH in your PC. "
echo "-------------------------------------------------------------------------"
echo "Try commmand first: ssh-keygen -R $ipvpsbackup"
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
    ;;
*)
clear
echo "========================================================================="
echo "You cancel change password for root user in vps backup!"
  /etc/vpssim/menu/vpssim-rsync-backup-vps-menu
;;
esac
