#!/bin/bash 

. /home/vpssim.conf

if [ -f /etc/csf/csf.conf ]; then
echo "========================================================================="
echo "This function will enable CSF firewall if you are disabling it on VPS."
echo "-------------------------------------------------------------------------" 
echo -n "Type in IP that you want to block [ENTER]: " 
read ipchan
test_csf=$(csf -v | awk 'NR==1 {print $NF}')
if [ "$ipchan" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please fill accurately."
/etc/vpssim/menu/vpssim-kiem-tra-ddos
exit
fi

if [ "$(grep "$ipchan" /etc/csf/csf.allow | awk '{print $4}')" == "allowed" ]; then
clear
echo "========================================================================="
echo "IP: $ipchan is in the CSF.Allow"
echo "-------------------------------------------------------------------------"
echo "Please remove $ipallow in CSF.Allow before you block!"
/etc/vpssim/menu/vpssim-kiem-tra-ddos
exit
fi


if [ ! "$(ping -c 1 $ipchan | tail -n +1 | head -1 | awk 'NR==1 {print $1}')" == "PING" ]; then
clear
echo "========================================================================="
echo "$ipchan is not a valid IP/CIDR"
echo "-------------------------------------------------------------------------"
echo "CSF Firewall can not block the IP you typed in."
/etc/vpssim/menu/vpssim-kiem-tra-ddos
exit
fi
if [ "$test_csf" == "enable" ]; then
csf -e
fi
csf -d $ipchan
/etc/vpssim/menu/CSF-Fiwall/vpssim-re-start-khoi-dong-lai-csf-lfd
clear
echo "========================================================================="
echo "IP: $ipchan has blocked by CSF FireWall. "
/etc/vpssim/menu/vpssim-kiem-tra-ddos
fi

clear
echo "========================================================================= "
echo "This funcion run with CSF Firewall"
echo "-------------------------------------------------------------------------"
echo "CSF Firewall is not installed ! "
echo "-------------------------------------------------------------------------"
read -r -p "Do you want to install CSF Firewall on this VPS [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
/etc/vpssim/menu/vpssim-cai-dat-csf-ddos
clear
echo "========================================================================= "
echo "Successfully installed and configed CSF Firewall."
/etc/vpssim/menu/vpssim-kiem-tra-ddos
;;
esac
clear
echo "========================================================================= "
echo "You cancel install CSF Firewall ! "
/etc/vpssim/menu/vpssim-kiem-tra-ddos
exit
fi
