#!/bin/sh
. /home/vpssim.conf
prompt="Type in your choice (7-Exit):"
if [ -f /etc/vpssim/btsync.info ]; then
options=("Enable/Disable BTsync" "View Manage info" "Change Manage info" "Change BTsync Port " "Change BTsync Version" "Remove BitTorrent Sync    " "Exit")
else
options=("Enable/Disable BTsync" "View Manage info" "Change Manage info" "Change BTsync Port " "Change BTsync Version" "Setup BitTorrent Sync     " "Exit")
fi
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM                \n"
printf "=========================================================================\n"
printf "                         BitTorrent Sync Manage                                \n"
printf "=========================================================================\n"
if [ -f /usr/bin/btsync ]; then
checksize=$(du -sb /usr/bin/btsync | awk 'NR==1 {print $1}')
if [ $checksize -gt 9000000 ]; then 
version=2.0
else
version=1.4
fi
ver_sionbt=`echo "| Version: $version"`
echo   "                      Status: Installed $ver_sionbt                           "
else
echo   "                             Status: Not Install                           "
fi
printf "=========================================================================\n"
echo ""
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/vpssim-tat-bat-bitsync;;
    2) /etc/vpssim/menu/vpssim-hien-mat-khau-bitsync;;
    3) /etc/vpssim/menu/vpssim-change-mat-khau-bitsync;;
    4) /etc/vpssim/menu/vpssim-thay-doi-bitsync-port;;
    5) /etc/vpssim/menu/vpssim-bitsync-thay-doi-phien-ban-bitsync;;
    6) /etc/vpssim/menu/vpssim-befor-cai-dat-xoa-bitsync;;
    7) clear && vpssim;;  
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac
done
 
