#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to fix permision error, chmod, chown for wordpress blog "
echo "-------------------------------------------------------------------------" 
echo "When website get this error, You can not upload images, update plugins,"
echo "-------------------------------------------------------------------------"
echo "update themes... and see error Can't Write..."
echo "========================================================================="
echo -n "Type in website: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately! "
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website"
echo "-------------------------------------------------------------------------"
echo "PLease try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ -f /home/$website/public_html/wp-config-sample.php ]; then
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website use wordpress code but not install yet!"
echo "-------------------------------------------------------------------------"
echo "Please install wordpress code then try again  !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
fi
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website is not wordpress blog !"
echo "-------------------------------------------------------------------------"
echo "PLease try again !."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
echo "-------------------------------------------------------------------------"
echo "Discovered $website in system"
echo "-------------------------------------------------------------------------"
echo "$website use wordpress code"
echo "-------------------------------------------------------------------------"
echo "VPSSIM fixing error"
echo "-------------------------------------------------------------------------"
echo "please wait ... "
sleep 3
chown -R nginx:nginx /home/$website/public_html
clear
echo "========================================================================="
echo "Fix permision error finished !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu



