#!/bin/sh
. /home/vpssim.conf
if [ ! -f /usr/local/bin/htpasswd.py ]; then
cp -r /etc/vpssim/menu/vpssim-tao-mat-khau-bao-ve-folder.py /usr/local/bin/htpasswd.py
chmod 755 /usr/local/bin/htpasswd.py
fi
if [ ! -f /etc/vpssim/pwprotect.default ]; then
echo "" > /etc/vpssim/pwprotect.default
fi
chmod 777 /var/lib/php/session/
prompt="Type in your choice (6-Exit):"
if [ -f /home/$mainsite/private_html/index.php ]; then 
options=("Disable PhpmyAdmin" "Open Phpmyadmin Port" "Close Phpmyadmin Port" "Change Phpmyadmin Port" "ON/OFF Protect phpMyAdmin" "Exit")
else
options=("Enable PhpmyAdmin" "Open Phpmyadmin Port" "Close Phpmyadmin Port" "Change Phpmyadmin Port" "ON/OFF Protect phpMyAdmin" "Exit")
fi
if [ -f /etc/vpssim/phpmyadmin.version ]; then
phpmyadminversion=`cat /etc/vpssim/phpmyadmin.version`
versionshow=`echo "| Version: $phpmyadminversion"`
else
versionshow=`echo "| Version: Unknown"`
fi

printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                            phpMyAdmin Manage \n"
printf "=========================================================================\n"
if [ -f /home/$mainsite/private_html/index.php ]; then 
printf "                PhpmyAdmin Status: Enable $versionshow\n"
else
printf "                PhpmyAdmin Status: Disable $versionshow\n"
fi
printf "=========================================================================\n"
printf "Link phpMyAdmin: http://$serverip:$priport\n"
printf "=========================================================================\n"
if [ "$(grep auth_basic_user_file /etc/nginx/conf.d/$mainsite.conf)" == "" ] ; then 
echo "You have not ENABLED protect phpMyAdmin, backup files, ocp.php .. yet "
echo "-------------------------------------------------------------------------"
echo "Use [ ON/OFF Protect phpMyAdmin ] to ENABLED this feature. "
echo "-------------------------------------------------------------------------"
echo "This notification auto disabled after you complete this security config!"
echo "========================================================================="
echo""
fi
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/vpssim-phpmyadmin;;
    2) /etc/vpssim/menu/tienich/vpssim-mo-phpmyadmin-port;;
    3) /etc/vpssim/menu/tienich/vpssim-dong-phpmyadmin-port;;
    4) /etc/vpssim/menu/tienich/vpssim-change-port-bi-mat;;
    #5) /etc/vpssim/menu/vpssim-hien-link-phpmyadmin;;
    5) /etc/vpssim/menu/vpssim-dat-mat-khau-bao-ve-phpmyadmin-backup-files;;
    6) clear && /bin/vpssim;;
    
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done

