#!/bin/bash 

. /home/vpssim.conf

if [ ! -f /bin/sizeconvert ]; then
cp -r /etc/vpssim/menu/vpssim-calc-for-convert-file-size-chuyen-doi-don-vi /bin/sizeconvert
chmod +x /bin/sizeconvert
sed -i 's/scale=0/scale=5/g' /bin/sizeconvert
fi

checknumber="^[0-9.]+$"
#prompt="Nhap lua chon cua ban: "
prompt="Type in your choice: "
options=( "Byte" "Kilobyte (KB)" "Megabyte (MB)" "Gigabyte (GB)" "Terabyte (TB)" "Cancel")
echo "========================================================================="
echo "Use this function to convert file size: B to KB to MB to GB to TB"
echo "-------------------------------------------------------------------------"
echo "Or TB to GB to MB to KB to B."
echo "========================================================================="
echo "Choose Your Curent File Size"
echo "========================================================================="
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) donvicanchuyen="Byte"; break;;
    2) donvicanchuyen="Kilobyte"; break;;
    3) donvicanchuyen="Megabyte"; break;;
    4) donvicanchuyen="Gigabyte"; break;;
    5) donvicanchuyen="Terabyte"; break;;
    6) donvicanchuyen="Cancel"; break;;
    #*) echo "Ban nhao sai, vui long chon so trong danh sach";continue;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
echo "-------------------------------------------------------------------------"
if [ "$donvicanchuyen" = "Byte" ]; then
echo -n "Type in File Size (Not include B): " 
read nhapso
nhapso=`echo $nhapso | tr '[A-Z]' '[a-z]'`
if [ "$nhapso" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately!"
#echo "You typed wrong, please type in accurately!"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [[ ! "$nhapso" =~ $checknumber ]]; then
clear
echo "========================================================================="
echo "$nhapso maybe not a number!"
#echo "$nhapso maybe not a number!"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
clear
echo "========================================================================="
echo "Byte: $nhapso B"
echo "========================================================================="
echo "Conversion Results:"
echo "-------------------------------------------------------------------------"
echo "Kilobyte: $(sizeconvert ${nhapso}/1024) KB"
echo "-------------------------------------------------------------------------"
echo "Megabyte: $(sizeconvert ${nhapso}/1024/1024) MB"
echo "-------------------------------------------------------------------------"
echo "Gigabyte: $(sizeconvert ${nhapso}/1024/1024/1024) GB"
echo "-------------------------------------------------------------------------"
echo "Terabyte: $(sizeconvert ${nhapso}/1024/1024/1024/1024) TB"
/etc/vpssim/menu/vpssim-tien-ich
elif [ "$donvicanchuyen" = "Kilobyte" ]; then

echo -n "Type in File Size (Not include KB): " 
read nhapso
nhapso=`echo $nhapso | tr '[A-Z]' '[a-z]'`
if [ "$nhapso" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately!"
#echo "You typed wrong, please type in accurately!"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [[ ! "$nhapso" =~ $checknumber ]]; then
clear
echo "========================================================================="
echo "$nhapso maybe not a number!"
#echo "$nhapso maybe not a number!"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
clear
echo "========================================================================="
echo "Kilobyte: $nhapso KB"
echo "========================================================================="
echo "Conversion Results:"
echo "-------------------------------------------------------------------------"
echo "Byte: $(sizeconvert ${nhapso}*1024) B"
echo "-------------------------------------------------------------------------"
echo "Megabyte: $(sizeconvert ${nhapso}/1024) MB"
echo "-------------------------------------------------------------------------"
echo "Gigabyte: $(sizeconvert ${nhapso}/1024/1024) GB"
echo "-------------------------------------------------------------------------"
echo "Terabyte: $(sizeconvert ${nhapso}/1024/1024/1024) TB"
/etc/vpssim/menu/vpssim-tien-ich
elif [ "$donvicanchuyen" = "Megabyte" ]; then
echo -n "Type in File Size (Not include MB): " 
read nhapso
nhapso=`echo $nhapso | tr '[A-Z]' '[a-z]'`
if [ "$nhapso" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately!"
#echo "You typed wrong, please type in accurately!"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [[ ! "$nhapso" =~ $checknumber ]]; then
clear
echo "========================================================================="
echo "$nhapso maybe not a number!"
#echo "$nhapso maybe not a number!"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
clear
echo "========================================================================="
echo "Megabyte: $nhapso MB"
echo "========================================================================="
echo "Conversion Results:"
echo "-------------------------------------------------------------------------"
echo "Byte: $(sizeconvert ${nhapso}*1024*1024) B"
echo "-------------------------------------------------------------------------"
echo "Kilobyte: $(sizeconvert ${nhapso}*1024) KB"
echo "-------------------------------------------------------------------------"
echo "Gigabyte: $(sizeconvert ${nhapso}/1024) GB"
echo "-------------------------------------------------------------------------"
echo "Terabyte: $(sizeconvert ${nhapso}/1024/1024) TB"
/etc/vpssim/menu/vpssim-tien-ich
elif [ "$donvicanchuyen" = "Gigabyte" ]; then
echo -n "Type in File Size (Not include GB): " 
read nhapso
nhapso=`echo $nhapso | tr '[A-Z]' '[a-z]'`
if [ "$nhapso" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately!"
#echo "You typed wrong, please type in accurately!"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [[ ! "$nhapso" =~ $checknumber ]]; then
clear
echo "========================================================================="
echo "$nhapso maybe not a number!"
#echo "$nhapso maybe not a number!"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
clear
echo "========================================================================="
echo "Gigabyte: $nhapso GB"
echo "========================================================================="
echo "Conversion Results:"
echo "-------------------------------------------------------------------------"
echo "Byte: $(sizeconvert ${nhapso}*1024*1024*1024) B"
echo "-------------------------------------------------------------------------"
echo "Kilobyte: $(sizeconvert ${nhapso}*1024*1024) KB"
echo "-------------------------------------------------------------------------"
echo "Megabyte: $(sizeconvert ${nhapso}*1024) MB"
echo "-------------------------------------------------------------------------"
echo "Terabyte: $(sizeconvert ${nhapso}/1024) TB"
/etc/vpssim/menu/vpssim-tien-ich
elif [ "$donvicanchuyen" = "Terabyte" ]; then
echo -n "Type in File Size (Not include TB): " 
read nhapso
nhapso=`echo $nhapso | tr '[A-Z]' '[a-z]'`
if [ "$nhapso" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately!"
#echo "You typed wrong, please type in accurately!"
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
if [[ ! "$nhapso" =~ $checknumber ]]; then
clear
echo "========================================================================="
echo "$nhapso maybe not a number!"
#echo "$nhapso maybe not a number!"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/vpssim-tien-ich
exit
fi
clear
echo "========================================================================="
echo "Terabyte: $nhapso TB"
echo "========================================================================="
echo "Conversion Results:"
echo "-------------------------------------------------------------------------"
echo "Byte: $(sizeconvert ${nhapso}*1024*1024*1024*1024) B"
echo "-------------------------------------------------------------------------"
echo "Kilobyte: $(sizeconvert ${nhapso}*1024*1024*1024) KB"
echo "-------------------------------------------------------------------------"
echo "Megabyte: $(sizeconvert ${nhapso}*1024*1024) MB"
echo "-------------------------------------------------------------------------"
echo "GigabyteB: $(sizeconvert ${nhapso}*1024) GB"
/etc/vpssim/menu/vpssim-tien-ich
else 
clear && /etc/vpssim/menu/vpssim-tien-ich
fi
