#!/bin/bash
. /home/vpssim.conf

if [ ! -d /etc/vpssim/Backup.Vhost.SSL ]; then
mkdir -p /etc/vpssim/Backup.Vhost.SSL
fi

if [ ! -d /etc/vpssim/.tmp ]; then
mkdir -p /etc/vpssim/.tmp
fi

if [ ! -f /root/.acme.sh/acme.sh ]; then
clear
echo "========================================================================="
echo "VPSSIM will setup Acme.Sh before run this function."
echo "-------------------------------------------------------------------------"
echo "Please wait ..."; sleep 5
wget -O -  https://get.acme.sh | sh
rm -rf /etc/vpssim/.tmp/check_crontab_acme
crontab -l > /etc/vpssim/.tmp/check_crontab_acme
if [ ! "$(grep "/root/.acme.sh" /etc/vpssim/.tmp/check_crontab_acme)" = "" ]; then
/root/.acme.sh/acme.sh --uninstallcronjob
fi
rm -rf /etc/vpssim/.tmp/check_crontab_acme
sleep 3
clear
echo "========================================================================="
echo "Setup Acme.sh finished"
echo "-------------------------------------------------------------------------"
echo "From now, you can setup SSL Let's Encrypt for your website."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi
version=`/root/.acme.sh/acme.sh --version | awk 'NR==2' | sed 's/v//'`
show_menu_lets-encrypt () {
prompt="Type in your choice (8-Exit):"
options=("Setup SSL for Domain" "Check Certificate " "Auto Renew Certificate" "Renew Certificate" "List Domain Setup SSL" "Remove SSL (Back to HTTP)" "Upgrade Acme.sh            " "Exit")
printf "=========================================================================\n"
printf "                 VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                        Setup SSL - Let's Encrypt \n"
echo "========================================================================="
echo "                   Powered by Acme.Sh | Version: $version"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/vpssim-cai-dat-ssl-letsencrypt;;
    2) /etc/vpssim/menu/vpssim-kiem-tra-ssl-letsencrypt;;
    3) /etc/vpssim/menu/vpssim-bat-auto-gia-han-letsencrypt;; 
    4) /etc/vpssim/menu/vpssim-renew-ssl-letsencrypt;;
    5) /etc/vpssim/menu/vpssim-list-domain-cai-dat-letsencrypt;;
    6) /etc/vpssim/menu/vpssim-remove-ssl-letsencrypt;;
    7) /etc/vpssim/menu/vpssim-update-letsencrypt;;
    8) clear && /bin/vpssim;;
    
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done
}

check_nginx_service () {
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
show_menu_lets-encrypt 
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "VPSSIM trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
service nginx start
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
		if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
show_menu_lets-encrypt 
		else
				clear
echo "========================================================================"
echo "VPSSIM can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Sorry, nginx stopped. Start it before use this function!"
	vpssim
		fi
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
show_menu_lets-encrypt 
	else
clear
echo "========================================================================"
echo "Nginx service is not running"
echo "------------------------------------------------------------------------"
echo "VPSSIM trying to start it"
echo "------------------------------------------------------------------------"
echo "Please wait ..."
sleep 5 ; clear
systemctl start nginx.service
clear
echo "========================================================================"
echo "Check Nginx service once again !"
echo "------------------------------------------------------------------------"
echo "please wait ..."
sleep 5 ; clear
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
show_menu_lets-encrypt 
		else
				clear
echo "========================================================================"
echo "VPSSIM can not start Nginx Service"
sleep 4 ;
	clear
	echo "========================================================================="
	echo "Sorry, nginx stopped. Start it before use this function!"
	vpssim
		fi
fi
fi
}
check_nginx_service
