#!/bin/sh
. /home/vpssim.conf
prompt="Type in your choice: "
options=( "2.0" "1.4")
echo "========================================================================="
echo "Use this function to setup BitTorrent Sync for server"
echo "-------------------------------------------------------------------------"
echo "Choose BitTorrent Sync Version You Want To Use"
echo "-------------------------------------------------------------------------"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) luachonphienban="phienban20"; break;;
    2) luachonphienban="phienban14"; break;;
 *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
     esac  
done
echo "========================================================================="
echo "Setup BitTorrent Sync Port."
echo "-------------------------------------------------------------------------"
echo "BTSync Port must not be the same with SSH port, Phpmyadmin Port And must "
echo "-------------------------------------------------------------------------"
echo "be a number within range of (30000 - 50000)"
echo "-------------------------------------------------------------------------"
echo -n "Type in the BTSync port [ENTER]: " 
read btsyncport
if [ "$btsyncport" = "" ]; then
clear
echo "========================================================================="
echo "You must type in the port for BTsync"
echo "-------------------------------------------------------------------------"
echo "BTSync port must be a number within range of (30000 - 50000) !" 
/etc/vpssim/menu/vpssim-bitsync-menu
exit
fi
if [ "$priport" = "$btsyncport" ]; then
clear
echo "========================================================================="
echo "Port you typed in similar to phpmyadmin port!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-bitsync-menu
exit
fi
if [[ ! ${btsyncport} =~ ^[0-9]+$ ]] ;then 
clear
echo "========================================================================="
echo "The Port you typed in: ${btsyncport} is wrong."
echo "-------------------------------------------------------------------------"
echo "BTsync port must be a number within range of (30000 - 50000) !" 
/etc/vpssim/menu/vpssim-bitsync-menu
exit
fi
if ! [[ $btsyncport -ge 30000 && $btsyncport -le 50000  ]] ; then  
clear
echo "========================================================================="
echo "The Port you typed in: ${btsyncport} is wrong."
echo "-------------------------------------------------------------------------"
echo "BTsync port must be a number within range of (30000 - 50000) !" 
/etc/vpssim/menu/vpssim-bitsync-menu
exit
fi    

random=`date |md5sum |cut -c '1-5'`
username=vpssim-$random
password=`date |md5sum |cut -c '6-20'`
rm -rf /etc/vpssim/btsync.info
rm -rf /etc/btsync-vpssim
mkdir -p /etc/btsync-vpssim
mkdir -p /etc/btsync-vpssim/.sync
mkdir -p /etc/btsync-vpssim/.btsync

rm -rf /etc/vpssim/btsync.info
    cat > "/etc/vpssim/btsync.info" <<END
username = $username
password = $password
btport = $btsyncport
END

if [ "$luachonphienban" = "phienban20" ]; then
echo "-------------------------------------------------------------------------"
echo "Sometimes, it can take some minutes to finish. Please wait..." && sleep 1
wget -q https://vpssim.com/script/vpssim/BTsync/2.0/$(uname -m)/btsync -O /usr/bin/btsync && chmod +x /usr/bin/btsync
cat > "/etc/btsync-vpssim/sync.conf" <<END
{ 
  "device_name": "vpssim",
  "listening_port" : 0,
  "storage_path" : "/etc/btsync-vpssim/.sync",
  "check_for_updates" : false, 
  "use_upnp" : true,
  "download_limit" : 0,                       
  "upload_limit" : 0, 
  "webui" :
  {
    "listen" : "0.0.0.0:$btsyncport",
    "login" : "$username",
    "password" : "$password"
  }
}
END
else 
echo "-------------------------------------------------------------------------"
echo "Sometimes, it can take some minutes to finish. Please wait..." && sleep 1
wget -q https://vpssim.com/script/vpssim/BTsync/1.4/$(uname -m)/btsync -O /usr/bin/btsync && chmod +x /usr/bin/btsync
cat > "/etc/btsync-vpssim/sync.conf" <<END
{ 
  "device_name": "vpssim",
  "listening_port" : 0,
  "storage_path" : "/etc/btsync-vpssim/.btsync",
  "check_for_updates" : false, 
  "use_upnp" : true,
  "download_limit" : 0,                       
  "upload_limit" : 0, 
  "webui" :
  {
    "listen" : "0.0.0.0:$btsyncport",
    "login" : "$username",
    "password" : "$password"
  }
}
END
fi

echo "/usr/bin/btsync --config /etc/btsync-vpssim/sync.conf" >> /etc/rc.d/rc.local
echo "========================================================================= "
echo "Open port: $btsyncport"
sleep 3
iptables -I INPUT -p tcp --dport $btsyncport -j ACCEPT
service iptables save
/usr/bin/btsync --config /etc/btsync-vpssim/sync.conf
clear
echo "========================================================================="
echo "Setup BitTorrent Sync complete"
echo "-------------------------------------------------------------------------"
echo "Manage infomation:"
echo "-------------------------------------------------------------------------"
echo "BTsync WebUI: http://$serverip:$(grep btport /etc/vpssim/btsync.info | awk 'NR==1 {print $3}')"
echo "-------------------------------------------------------------------------"
echo "User: $(grep username /etc/vpssim/btsync.info | awk 'NR==1 {print $3}') | Password: $(grep password /etc/vpssim/btsync.info | awk 'NR==1 {print $3}')"
/etc/vpssim/menu/vpssim-bitsync-menu
exit
fi  


