#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to setup Sub-Domain Wordpress Multisite "
echo "-------------------------------------------------------------------------" 
echo "After finish setup, Create new account in WP-Admin then creating Vhost"
echo "-------------------------------------------------------------------------" 
echo "using [ Create Vhost for WP Multisite ] function"
echo "========================================================================="
echo -n "Type in website: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately! "
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website"
echo "-------------------------------------------------------------------------"
echo "PLease try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ -f /home/$website/public_html/wp-config-sample.php ]; then
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website use wordpress code but not install yet!"
echo "-------------------------------------------------------------------------"
echo "Please install wordpress code then try again  !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
fi
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website is not wordpress blog !"
echo "-------------------------------------------------------------------------"
echo "PLease try again !."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! "$(grep "WP_ALLOW_MULTISITE" /home/$website/public_html/wp-config.php)" == "" ]; then
clear
echo "========================================================================="
echo "$website already setup Wordpress Multisite"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
tendatabase=`cat /home/$website/public_html/wp-config.php | grep DB_NAME | cut -d \' -f 4`
echo "========================================================================="
echo "Discovered $website in system"
echo "-------------------------------------------------------------------------"
echo "$website use wordpress code"
echo "========================================================================="
echo "HOW TO SETUP WORDPRESS MULTISITE"
echo "========================================================================="
prompt="Type in your choice: "
options=( "Set Wordpress Multisite immediately" "Backup (Database & Wp-config.php) then Setup" "Cancel Setup")
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) luachoncaidat="caingay"; break;;
    2) luachoncaidat="sauluuroicai"; break;;
    3) luachoncaidat="cancel"; break;;
    #*) echo "Ban nhap sai, Vui long nhap theo danh sach trong list";continue;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
###################################
#caingay
###################################
if [ "$luachoncaidat" = "caingay" ]; then
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
echo "-------------------------------------------------------------------------"   
sleep 2
cd /home/$website/public_html
wp core multisite-convert --subdomains --allow-root
cd
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else
systemctl restart php-fpm.service
fi 
clear
if [ ! "$(grep "WP_ALLOW_MULTISITE" /home/$website/public_html/wp-config.php)" == "" ]; then
echo "========================================================================="
echo "Setup Wordpress Multisite for $website successfully !"
echo "-------------------------------------------------------------------------"
echo "To create new subdomain, Create it on WP-ADMIN, then create Vhost for"
echo "-------------------------------------------------------------------------"
echo "Subdomain on Server by [ Create Vhost for WP MultiSite ] function "
/etc/vpssim/menu/vpssim-wordpress-tools-menu
else
echo "========================================================================="
echo "Setup Wordpress Multisite for $website failed !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
fi
###################################
#sao luu roi cai
###################################
elif [ "$luachoncaidat" = "sauluuroicai" ]; then
tendatabase=`cat /home/$website/public_html/wp-config.php | grep DB_NAME | cut -d \' -f 4`
echo "`date '+%d%m'`" > /tmp/datetime
tenmo=$(cat /tmp/datetime)
randomwp=`date |md5sum |cut -c '1-16'`
if [ ! -d /home/$website/public_html/0-VPSSIM ]; then
mkdir -p /home/$website/public_html/0-VPSSIM
fi
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
echo "-------------------------------------------------------------------------"   
sleep 2
cd /home/$website/public_html
#wp db export $tendatabase-$tenmo --allow-root
#mv -f /home/$website/public_html/$tendatabase-$tenmo /home/$website/public_html/0-VPSSIM/$tendatabase-$tenmo.Before-WP-Multisite
if [ "$(grep "default_storage_engine = MyISAM" /etc/my.cnf.d/server.cnf | awk 'NR==1 {print $3}')" = "MyISAM" ]; then
mysqldump -u root -p$mariadbpass $tendatabase --lock-tables=false | gzip -6 > /home/$website/public_html/0-VPSSIM/$tendatabase-$tenmo.Before-WP-Multisite_$randomwp.sql.gz
else
mysqldump -u root -p$mariadbpass $tendatabase --single-transaction | gzip -6 > /home/$website/public_html/0-VPSSIM/$tendatabase-$tenmo.Before-WP-Multisite_$randomwp.sql.gz
fi
cp /home/$website/public_html/wp-config.php /home/$website/public_html/0-VPSSIM/wp-config.php-$tenmo.Before-WP-Multisite_$randomwp
wp core multisite-convert --subdomains --allow-root
cd
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else
systemctl restart php-fpm.service
fi 
clear
if [ ! "$(grep "WP_ALLOW_MULTISITE" /home/$website/public_html/wp-config.php)" == "" ]; then
echo "========================================================================="
echo "Setup Wordpress Multisite for $website successfully !"
echo "-------------------------------------------------------------------------"
echo "To create new subdomain, Create it on WP-ADMIN, then create Vhost for"
echo "-------------------------------------------------------------------------"
echo "Subdomain on Server by [ Create Vhost for WP MultiSite ] function "
else
echo "========================================================================="
echo "Setup Wordpress Multisite for $website failed !"
fi

if [ -f /home/$website/public_html/0-VPSSIM/$tendatabase-$tenmo.Before-WP-Multisite_$randomwp.sql.gz ]; then
echo "-------------------------------------------------------------------------"
echo "Backup Database & wp-config.php successfully"
echo "-------------------------------------------------------------------------"
echo "Link foler backup: http://$website/0-VPSSIM"
else
echo "-------------------------------------------------------------------------"
echo "Back up database failed !"
fi
/etc/vpssim/menu/vpssim-wordpress-tools-menu
else 
clear && /etc/vpssim/menu/vpssim-wordpress-tools-menu
fi
