#!/bin/sh
. /home/vpssim.conf
printf "=========================================================================\n"
echo "Use this function to ENABLE or DISABLE Auto backup code for website"
echo "-------------------------------------------------------------------------"
echo -n "Type in website [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately !"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
	clear
echo "========================================================================="
echo "$website maybe not a domain name!"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "$website is not existed in the system!"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi
if [ ! -f /home/$website/public_html/index.php ]; then
clear
echo "========================================================================="
echo "$website has no data. Please choose other website."
/etc/vpssim/menu/vpssim-sao-luu
exit
fi
rm -rf /tmp/websiteautobackup
echo "$website" > /tmp/websiteautobackup
if [ -f /bin/vpssim-backupcode-$website ]; then
 if [ -f /etc/cron.d/vpssim.code.cron ]; then
     if [ ! "$(grep vpssim-backupcode-$website /etc/cron.d/vpssim.code.cron)" == "" ]; then
     /etc/vpssim/menu/vpssim-TAT-tu-dong-sao-luu-code
     fi
 fi
fi 
 /etc/vpssim/menu/vpssim-BAT-tu-dong-sao-luu-code
