#!/bin/sh
. /home/vpssim.conf
. /etc/vpssim/pwprotect.default
if [ ! -d /etc/nginx/pwprotect ]; then
mkdir -p /etc/nginx/pwprotect
fi

if [ ! -f /etc/vpssim/net2ftpsite.info ]; then
clear
echo "========================================================================="
echo "You have not installed Net2FTP in Server !"
/etc/vpssim/menu/vpssim-net2ftp-menu
exit
fi
net2ftpsite=$(cat /etc/vpssim/net2ftpsite.info)
if [ ! -f /etc/nginx/.htpasswd ]; then
clear
echo "========================================================================="
echo "You must create default User & password before using this function. "
echo "-------------------------------------------------------------------------"
echo "Create it by: VPSSIM Menu => Default User & Password."
/etc/vpssim/menu/vpssim-net2ftp-menu
exit
fi

if [ "$(grep auth_basic_user_file /etc/nginx/conf.d/$net2ftpsite.conf)" == "" ] ; then 
echo "========================================================================="
echo "Use this function to Enable/Disable protection Net2FTP Domain. "
echo "-------------------------------------------------------------------------"
echo "Login info: "
echo "-------------------------------------------------------------------------"
echo "Username: $userdefault | Password: $passdefault"
echo "-------------------------------------------------------------------------"
read -r -p "You want to Enable protection Net2FTP Domain ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
rm -rf /tmp/baovedomainfilemanage
   cat >> "/tmp/baovedomainfilemanage" <<END
sed -i "/server_name\ $net2ftpsite;/aauth_basic \"Authorization Required\";" /etc/nginx/conf.d/$net2ftpsite.conf
sed -i "/.*Authorization\ Required.*/aauth_basic_user_file  /etc/nginx/.htpasswd;" /etc/nginx/conf.d/$net2ftpsite.conf
END
chmod +x /tmp/baovedomainfilemanage
/tmp/baovedomainfilemanage
rm -rf /tmp/baovedomainfilemanage
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
else 
systemctl reload nginx
fi
;;
    *)
       clear 
echo "========================================================================= "
echo "Cancel "
/etc/vpssim/menu/vpssim-net2ftp-menu
        ;;
esac
clear 
echo "========================================================================= "
echo "Config protection Net2FTP Domain finished."
echo "-------------------------------------------------------------------------"
echo "Login infomation: "
echo "-------------------------------------------------------------------------"
echo "Username: $userdefault | Password: $passdefault"
/etc/vpssim/menu/vpssim-net2ftp-menu

else

echo "========================================================================="
echo "Use this function to Enable/Disable protection Net2FTP Domain. "
echo "-------------------------------------------------------------------------"
echo "Login Info: "
echo "-------------------------------------------------------------------------"
echo "Username: $userdefault | Password: $passdefault"
echo "-------------------------------------------------------------------------"
read -r -p "You want to Disable protection Net2FTP Domain ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ... "
sleep 1
sed -i '/auth_basic/d' /etc/nginx/conf.d/$net2ftpsite.conf
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
else 
systemctl reload nginx
fi
;;
    *)
       clear 
echo "========================================================================= "
echo "Cancel !"
/etc/vpssim/menu/vpssim-net2ftp-menu
        ;;
esac
clear 
echo "========================================================================= "
echo "Disable protection Net2FTP Domain finished. "
/etc/vpssim/menu/vpssim-net2ftp-menu
fi
