#!/bin/bash

. /home/vpssim.conf

if [ ! -f /etc/vpssim/menu/vpssim-remove-ssl-letsencrypt-read ]; then
clear
printf "=========================================================================\n"
printf "                 VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                        Setup SSL - Let's Encrypt \n"
echo "========================================================================="
echo ""
echo "You must be careful when using this function !"
echo "-------------------------------------------------------------------------"
echo "When change HTTP => HTTPS, all backlink will be unchanged but after "
echo "-------------------------------------------------------------------------"
echo "change HTTPS back to HTTP, all backlink with HTTPS:// will be lost. "
echo "-------------------------------------------------------------------------"
echo "THIS WARNING SHOW ONLY ONCE !"
echo "========================================================================="
touch /etc/vpssim/menu/vpssim-remove-ssl-letsencrypt-read
read -p "Press [Enter] to continue ..."
clear
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi

echo "========================================================================="
echo "Use this function to remove SSL (Let's Encrypt) or Back to HTTP from"
echo "-------------------------------------------------------------------------"
echo "HTTPS for domain was setup SSL by VPSSIM."
echo "-------------------------------------------------------------------------"
echo -n "Type in the domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
websiteTO=`echo $website | tr '[a-z]' '[A-Z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "The Domain name can not be empty"
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi

if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not find $website in server "
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi  

if [ ! -d /home/$website/public_html ]; then
clear
echo "========================================================================="
echo "Can not find folder public_html of $website"
echo "-------------------------------------------------------------------------"
echo "You can not using this function."
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi
##############

echo "Check $website SSL" > /home/$website/public_html/vpssim.check
checkurlsttSSL=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://$website/vpssim.check")
checkurlstt=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://$website/vpssim.check")
rm -rf /home/$website/public_html/vpssim.check

if [ ! "$checkurlstt" = "200" ] && [ ! "$checkurlsttSSL" = "200" ]; then
clear
echo "========================================================================="
echo "You have not point $website to $serverip yet !"
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not run this function."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi

if [ "$checkurlstt" = "200" ]; then
clear
echo "========================================================================="
echo "$websiteTO does not using SSL by Let's Encrypt"
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not run this function.."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi

if [ "$(grep "/etc/nginx/auth-acme/$website/$website.crt" /etc/nginx/conf.d/$website.conf)" = "" ] && [ "$checkurlsttSSL" == "200" ]; then
clear
echo "========================================================================="
echo "$websiteTO using SSL but do not using Let's Encrypt."
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not run this function."
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi




if [ ! -f /etc/vpssim/Backup.Vhost.SSL/$website/$website.conf ] && [ ! -f /etc/vpssim/Backup.Vhost.SSL/$website/$website.conf_HTTPS ]; then
echo "-------------------------------------------------------------------------"
echo "Can not find backup of Vhost of $website."
echo "========================================================================="
  read -r -p "You still want to remove SSL for $websiteTO [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    
rm -rf /etc/vpssim/.tmp/$website.conf_HTTPS
yes | cp -rf  /etc/nginx/conf.d/$website.conf /etc/vpssim/.tmp/$website.conf_HTTPS
yes | cp -rf  /etc/nginx/conf.d/$website.conf /etc/vpssim/.tmp/$website.conf_HTTPS_run

rm -rf /etc/vpssim/.tmp/servername
grep "server_name\ $website" /etc/vpssim/.tmp/$website.conf_HTTPS_run > /etc/vpssim/.tmp/servername
servername=$(cat /etc/vpssim/.tmp/servername)

sed -i "1,/${servername}/d" /etc/vpssim/.tmp/$website.conf_HTTPS_run  
# Tao vhost website
rm -rf /etc/vpssim/.tmp/$website.conf.txt

cat > "/etc/vpssim/.tmp/$website.conf.txt" <<END
server {
	    server_name www.$website;
	    rewrite ^(.*) http://$website$1 permanent;
    	}
server {
	    listen   80;
    	access_log off;
    	# access_log   /home/$website/logs/access_log;
    	error_log off;
    	# error_log /home/$website/logs/error.log;
    	add_header X-Frame-Options SAMEORIGIN;
		add_header X-Content-Type-Options nosniff;
		add_header X-XSS-Protection "1; mode=block";
		root /home/$website/public_html;
include /etc/nginx/conf/ddos2.conf;
	index index.php index.html index.htm;
$servername
END

cd /etc/vpssim/.tmp/
rm -rf $website.conf
cat $website.conf.txt $website.conf_HTTPS_run > $website.conf
rm -rf /etc/vpssim/.tmp/$website.conf_HTTPS_run
rm -rf /etc/vpssim/.tmp/$website.conf.txt
cd    
yes | cp -rf /etc/vpssim/.tmp/$website.conf /etc/nginx/conf.d/$website.conf
nginx -t

service nginx restart

rm -rf /home/$website/public_html/vpssim.check
echo "Check $website Non SSL" > /home/$website/public_html/vpssim.check
checkurlstt=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://$website/vpssim.check")
rm -rf /home/$website/public_html/vpssim.check

if [ "$checkurlstt" = "200" ] ; then
rm -rf /etc/vpssim/.tmp/$website.conf_HTTPS
rm -rf /root/.acme.sh/$website
rm -rf /etc/nginx/auth-acme/$website
rm -rf /etc/vpssim/Backup.Vhost.SSL/$website
clear
echo "========================================================================="
echo "Remove SSL for $websiteTO finished."
echo "-------------------------------------------------------------------------"
echo "Please clear your browser cache and check $website !"
/etc/vpssim/menu/vpssim-letsencrypt-menu
else
yes | cp -rf  /etc/vpssim/.tmp/$website.conf_HTTPS /etc/nginx/conf.d/$website.conf
rm -rf /etc/vpssim/.tmp/$website.conf_HTTPS
rm -rf /etc/vpssim/.tmp/$website.conf
service nginx restart
clear
echo "========================================================================="
echo "There's an error when VPSSIM remove SSL for $websiteTO."
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not run this function."
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi

;;
    *)
clear 
echo "========================================================================= "
echo "Cancel !"
/etc/vpssim/menu/vpssim-letsencrypt-menu
        ;;
esac
fi


echo "========================================================================="
  read -r -p "You want to remove SSL of $websiteTO [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
echo "-------------------------------------------------------------------------"
echo "VPSSIM will retore backup Vhost NON_SSL (HTTP) of $websiteTO."
echo "-------------------------------------------------------------------------"
echo "Please wait ..."; sleep 2
rm -rf /etc/vpssim/.tmp/$website.conf_HTTPS
yes | cp -rf  /etc/nginx/conf.d/$website.conf /etc/vpssim/.tmp/$website.conf_HTTPS
yes | cp -rf /etc/vpssim/Backup.Vhost.SSL/$website/$website.conf /etc/nginx/conf.d/$website.conf

service nginx restart
rm -rf /home/$website/public_html/vpssim.check
echo "Check $website SSL" > /home/$website/public_html/vpssim.check
checkurlstt=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://$website/vpssim.check")
rm -rf /home/$website/public_html/vpssim.check

if [ "$checkurlstt" = "200" ] ; then
rm -rf /etc/vpssim/.tmp/$website.conf_HTTPS
rm -rf /root/.acme.sh/$website
rm -rf /etc/nginx/auth-acme/$website
rm -rf /etc/vpssim/Backup.Vhost.SSL/$website
clear
echo "========================================================================="
echo "Remove SSL for $websiteTO finished."
echo "-------------------------------------------------------------------------"
echo "Please clear your browser cache and check $website !"
/etc/vpssim/menu/vpssim-letsencrypt-menu
else
yes | cp -rf  /etc/vpssim/.tmp/$website.conf_HTTPS /etc/nginx/conf.d/$website.conf
rm -rf /etc/vpssim/.tmp/$website.conf_HTTPS
service nginx restart
clear
echo "========================================================================="
echo "There's an error when VPSSIM remove SSL for $websiteTO."
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not run this function."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi
;;
    *)
clear 
echo "========================================================================= "
echo "Cancel !"
/etc/vpssim/menu/vpssim-letsencrypt-menu
        ;;
esac
