#!/bin/sh

. /home/vpssim.conf
website=$(cat /tmp/websiteautobackup)
websiteTO=`echo $website | tr '[a-z]' '[A-Z]'`
echo "-------------------------------------------------------------------------"
echo "Current $websiteTO is being ENABLED Auto backup"
echo "-------------------------------------------------------------------------"
read -r -p "You want to DISABLE Auto backup for $website  ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ..."
sleep 1
rm -rf /bin/vpssim-backupcode-$website
if [ -f /etc/cron.d/vpssim.code.cron ]; then
cat > "/tmp/removebackupcode" <<END
sed -i '/vpssim-backupcode-$website/d' /etc/cron.d/vpssim.code.cron
END
chmod +x /tmp/removebackupcode
/tmp/removebackupcode 
rm -rf /tmp/removebackupcode
service crond restart
fi
clear
echo "========================================================================="
echo "Disable auto backup $website successful."
/etc/vpssim/menu/vpssim-sao-luu
        ;;
    *)
        clear
echo "========================================================================= "
echo "Cancel DISABLE auto backup $website !"
/etc/vpssim/menu/vpssim-sao-luu
        ;;
esac
