#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Type in wordpress website you want to update wordpress code"
echo "-------------------------------------------------------------------------"
echo -n "Type in website: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately! "
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website"
echo "-------------------------------------------------------------------------"
echo "PLease try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ -f /home/$website/public_html/wp-config-sample.php ]; then
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website use wordpress code but not install yet!"
echo "-------------------------------------------------------------------------"
echo "Please install wordpress code then try again  !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
fi
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website is not wordpress blog !"
echo "-------------------------------------------------------------------------"
echo "PLease try again !."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
echo "-------------------------------------------------------------------------"
echo "Discovered $website using Wordpress code in system"
echo "-------------------------------------------------------------------------"
echo "VPSSIM checking your Wordpress version"
echo "-------------------------------------------------------------------------"
sleep 3
date |md5sum |cut -c '1-8' > /tmp/abcd
random=$(cat /tmp/abcd)
tendatabase=`cat /home/$website/public_html/wp-config.php | grep DB_NAME | cut -d \' -f 4`
echo "`date '+%d%m'`" > /tmp/datetime
tenmo=$(cat /tmp/datetime)
chown -R nginx:nginx /home/$website/public_html
cd /home/$website/public_html/
vpssimcheckversion=$(wp core check-update --allow-root | tail -n1 | awk 'NR==1 {print $1}')
if [ "$vpssimcheckversion" == "Success:" ]; then
clear
cd
echo "========================================================================="
echo "Website $website using latest wordpress version "
/etc/vpssim/menu/vpssim-wordpress-tools-menu
else
if [ ! -d /home/$website/public_html/0-VPSSIM ]; then
mkdir -p /home/$website/public_html/0-VPSSIM
fi
clear
echo "========================================================================="
echo "Wordpress version on $website: $(wp core version --allow-root)"
echo "-------------------------------------------------------------------------"
echo "Current latest Wordpress version: $vpssimcheckversion"
echo "-------------------------------------------------------------------------"
echo "VPSSIM will upgrade wordpress on $website to $vpssimcheckversion"
echo "-------------------------------------------------------------------------"
echo "Before upgrade process, VPSSIM will backup database"
echo "-------------------------------------------------------------------------"
echo "Link file backup database: "
echo "-------------------------------------------------------------------------"
echo "http://$website/0-VPSSIM/$tendatabase-$random-$tenmo.sql.gz"
echo "-------------------------------------------------------------------------"
read -p "Press [Enter] to continue ..."
if [ "$(grep "default_storage_engine = MyISAM" /etc/my.cnf.d/server.cnf | awk 'NR==1 {print $3}')" = "MyISAM" ]; then
mysqldump -u root -p$mariadbpass $tendatabase --lock-tables=false | gzip -6 > /home/$website/public_html/0-VPSSIM/$tendatabase-$random-$tenmo.sql.gz
else
mysqldump -u root -p$mariadbpass $tendatabase --single-transaction | gzip -6 > /home/$website/public_html/0-VPSSIM/$tendatabase-$random-$tenmo.sql.gz
fi
/etc/vpssim/menu/vpssim-enable-tat-ca-cac-ham-php-php.ini
wp core update --allow-root
wp core update-db --allow-root
/etc/vpssim/menu/vpssim-re-config-cac-ham-php-disable-php.ini
cd
chown -R nginx:nginx /home/$website/public_html
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service php-fpm restart
else
systemctl restart php-fpm.service
fi 
cd /home/$website/public_html/
vpssimcheckversion=$(wp core check-update --allow-root | tail -n1 | awk 'NR==1 {print $1}')
clear
echo "========================================================================="
if [ "$vpssimcheckversion" == "Success:" ]; then
echo "Update WP on $website to latest version successfully"
else
echo "Update wordpress code failed"
fi
cd
if [ -f /home/$website/public_html/0-VPSSIM/$tendatabase-$random-$tenmo.sql.gz ]; then
echo "-------------------------------------------------------------------------"
echo "Backup database $tendatabase successfully"
echo "-------------------------------------------------------------------------"
echo "Link file backup database:"
echo "-------------------------------------------------------------------------"
echo "http://$website/0-VPSSIM/$tendatabase-$random-$tenmo.sql.gz"
else
echo "-------------------------------------------------------------------------"
echo "Backup database failed"
fi
/etc/vpssim/menu/vpssim-wordpress-tools-menu
fi
