#!/bin/sh
. /home/vpssim.conf
printf "=========================================================================\n"
echo "Use this function to ENABLE or DISABLE Auto backup Database in Server"
echo "-------------------------------------------------------------------------"
echo -n "Type in Database name [ENTER]: " 
read dataname
if [ "$dataname" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
if [ ! -f /var/lib/mysql/$dataname/db.opt ]; then
clear
echo "========================================================================="
echo "Database: $dataname is not exited on server"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
if [ "$(ls -1 /var/lib/mysql/$dataname | wc -l)" == 1 ]; then
clear
echo "========================================================================="
echo "Database $dataname is empty"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi

rm -rf /tmp/databaseautobackup
echo "$dataname" > /tmp/databaseautobackup
if [ -f /bin/vpssim-backupdb-$dataname ]; then
 if [ -f /etc/cron.d/vpssim.db.cron ]; then
     if [ ! "$(grep vpssim-backupdb-$dataname /etc/cron.d/vpssim.db.cron)" == "" ]; then
     /etc/vpssim/menu/vpssim-TAT-tu-dong-sao-luu-database
     fi
 fi
fi 
 /etc/vpssim/menu/vpssim-BAT-tu-dong-sao-luu-database
