#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to get database information of Wordpress website"
echo "-------------------------------------------------------------------------" 
echo -n "Type in website: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately! "
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website"
echo "-------------------------------------------------------------------------"
echo "PLease try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ -f /home/$website/public_html/wp-config-sample.php ]; then
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website use wordpress code but not install yet!"
echo "-------------------------------------------------------------------------"
echo "Please install wordpress code then try again  !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
fi
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website is not wordpress blog !"
echo "-------------------------------------------------------------------------"
echo "PLease try again !."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi

echo "-------------------------------------------------------------------------"
echo "Discovered $website in system"
echo "-------------------------------------------------------------------------"
echo "$website use wordpress code"
echo "-------------------------------------------------------------------------"
echo "VPSSIM prepare to get database info"
echo "-------------------------------------------------------------------------"
echo "Please wait .... "
echo "-------------------------------------------------------------------------"
sleep 3

databasename=`cat /home/$website/public_html/wp-config.php | grep DB_NAME | cut -d \' -f 4`
databaseuser=`cat /home/$website/public_html/wp-config.php | grep DB_USER | cut -d \' -f 4`
databasepass=`cat /home/$website/public_html/wp-config.php | grep DB_PASSWORD | cut -d \' -f 4`
clear
echo "========================================================================="
echo "Database infomation for $website"
echo "-------------------------------------------------------------------------"
echo "Database name: $databasename"
echo "-------------------------------------------------------------------------"
echo "Username: $databaseuser"
echo "-------------------------------------------------------------------------"
echo "Password: $databasepass"
/etc/vpssim/menu/vpssim-wordpress-tools-menu

