#!/bin/sh
. /home/vpssim.conf
rm -rf /tmp/vpssim.newversion*
cd /tmp
timeout 3 wget -q https://vpssim.com/script/vpssim/vpssim.newversion
cd
LOCALVER=`cat /etc/vpssim/vpssim.version`
 if [ ! -f /tmp/vpssim.newversion ]; then 
 clear
printf "=========================================================================\n"
echo "VPSSIM cant not check current version"
echo "-------------------------------------------------------------------------"
echo "(VPSSIM Khong the kiem tra phien ban VPSSIM hien tai)"
/etc/vpssim/menu/vpssim-update-upgrade-service-menu
 exit
 fi
if [ -f /tmp/vpssim.newversion ]; then
REMOVER=`cat /tmp/vpssim.newversion`
if [ ! "$LOCALVER" == "$REMOVER" ]; then
clear
printf "=========================================================================\n"
echo "You must update VPSSIM to latest version to use this function"
echo "-------------------------------------------------------------------------"
echo "(Ban phai update VPSSIM len phien ban moi nhat de su dung chuc nang nay)"
/etc/vpssim/menu/vpssim-update-upgrade-service-menu
fi
fi
if [ "$(grep VPSSIM.COM /bin/vpssim)" != "" ]; then
options=("EngLish (Current)" "VietNamese" "Exit")
else
options=("EngLish" "VietNamese (Current)" "Exit")
fi
prompt="Type in your choice:" 
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM                \n"
printf "=========================================================================\n"
printf "                      Choose Language For VPSSIM                                \n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/vpssim-chuyen-ngon-ngu-sang-tieng-anh;;
    2) /etc/vpssim/menu/vpssim-chuyen-ngon-ngu-sang-tieng-viet;;
    3) clear && /etc/vpssim/menu/vpssim-update-upgrade-service-menu;; 
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac
done
 
