#!/bin/bash
. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to restore database for wordpress website"
echo "========================================================================="
echo -n "Type in website: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately!  "
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website !"
echo "-------------------------------------------------------------------------"
echo "Please try again"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
if [ -f /home/$website/public_html/wp-config-sample.php ]; then
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website has wordpress code but not install yet !"
echo "-------------------------------------------------------------------------"
echo "Please setup wordpress first and try again !"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
fi
if [ ! -f /home/$website/public_html/wp-config.php ]; then
clear
echo "========================================================================="
echo "$website is not wordpress blog!"
echo "-------------------------------------------------------------------------"
echo "Please try again."
/etc/vpssim/menu/vpssim-wordpress-tools-menu
exit
fi
tendatabase=`cat /home/$website/public_html/wp-config.php | grep DB_NAME | cut -d \' -f 4`
randomwp=`date |md5sum |cut -c '1-18'`
date -r /var/lib/mysql/$tendatabase +%H%M%S> /tmp/vpssim1
echo "-------------------------------------------------------------------------"
echo "Discovered $website in system"
echo "-------------------------------------------------------------------------"
echo "$website use wordpress code"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
echo "-------------------------------------------------------------------------"

if [ -f /home/$website/public_html/VPSSIM-DATABASE.sql.gz ]; then
echo "Discovered backup file VPSSIM-DATABASE.sql.gz"
echo "-------------------------------------------------------------------------"
echo "Prepare to Restore .... "
echo "-------------------------------------------------------------------------"
sleep 2
gunzip < /home/$website/public_html/VPSSIM-DATABASE.sql.gz | mysql -u root -p$mariadbpass $tendatabase
date -r /var/lib/mysql/$dataname +%H%M%S> /tmp/vpssim2
check1=`cat /tmp/vpssim1`
check2=`cat /tmp/vpssim2`

if [ "$check1" == "$check2" ]; then
	rm -rf /tmp/vpssim1
	rm -rf /tmp/vpssim2
	clear
	echo "========================================================================="
	echo "Restore database $tendataname failed "
	echo "-------------------------------------------------------------------------"
	echo "Please check Backup file then try again !"
	/etc/vpssim/menu/vpssim-wordpress-tools-menu
	else	
	rm -rf /tmp/vpssim1
	rm -rf /tmp/vpssim2
	clear
	echo "========================================================================="
	echo "Restore database $tendatabase successfully !"
	mv /home/$website/public_html/VPSSIM-DATABASE.sql.gz /home/$website/public_html/VPSSIM-DATABASE.sql.gz.$randomwp
	echo "-------------------------------------------------------------------------"
	echo "Backup file renamed to VPSSIM-DATABASE.sql.gz.$randomwp"
	/etc/vpssim/menu/vpssim-wordpress-tools-menu
	fi
else
	clear
	echo "========================================================================="
	echo "HOW TO RESTORE"
	echo "========================================================================="
	echo "This function only restore a backup database in .sql.gz format"
	echo "-------------------------------------------------------------------------"
	echo "You must rename the Backup file to VPSSIM-DATABASE.sql.gz then upload to: "
	echo "-------------------------------------------------------------------------"
	echo "/home/$website/public_html/"
	echo "========================================================================="
	read -p "Upload Finished. Press [Enter] to restore backup ..."
	echo "-------------------------------------------------------------------------"
	echo "VPSSIM finding the Backup file .... "
	echo "-------------------------------------------------------------------------"
	sleep 4
	if [ -f /home/$website/public_html/VPSSIM-DATABASE.sql.gz ]; then
echo "Discovered Backup file VPSSIM-DATABASE.sql.gz"
echo "-------------------------------------------------------------------------"
echo "Prepare to restore .... "
echo "-------------------------------------------------------------------------"
sleep 2
gunzip < /home/$website/public_html/VPSSIM-DATABASE.sql.gz | mysql -u root -p$mariadbpass $tendatabase
date -r /var/lib/mysql/$dataname +%H%M%S> /tmp/vpssim2
check1=`cat /tmp/vpssim1`
check2=`cat /tmp/vpssim2`

if [ "$check1" == "$check2" ]; then
	rm -rf /tmp/vpssim1
	rm -rf /tmp/vpssim2
	clear
	echo "========================================================================="
	echo "Restore database $tendatabase failed "
	echo "-------------------------------------------------------------------------"
	echo "Please check Backup file then try again !"
	/etc/vpssim/menu/vpssim-wordpress-tools-menu
	else	
	rm -rf /tmp/vpssim1
	rm -rf /tmp/vpssim2
	clear
	echo "========================================================================="
	echo "Restore database $tendatabase successfully !"
	mv /home/$website/public_html/VPSSIM-DATABASE.sql.gz /home/$website/public_html/VPSSIM-DATABASE.sql.gz.$randomwp
	echo "-------------------------------------------------------------------------"
	echo "Backup file renamed to VPSSIM-DATABASE.sql.gz.$randomwp"
	/etc/vpssim/menu/vpssim-wordpress-tools-menu
	fi
else
clear
echo "=========================================================================" 
echo "Can not discover VPSSIM-DATABASE.sql.gz !"
echo "-------------------------------------------------------------------------"
echo "You should upload file backup to Server then try again"
/etc/vpssim/menu/vpssim-wordpress-tools-menu
fi
fi
