#!/bin/bash  
. /home/vpssim.conf
if [ -f /etc/vpssim/uploadsite ]; then
clear
echo "========================================================================="
echo "You have installed File Manager for VPS !"
echo "-------------------------------------------------------------------------"
echo "Domain File Manager is: $(cat /etc/vpssim/uploadsite)"
echo "-------------------------------------------------------------------------"
echo "Point domain $(cat /etc/vpssim/uploadsite) to $serverip"
echo "-------------------------------------------------------------------------"
echo "And access to this domain on the browser for managing files on server."
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

echo "========================================================================="
echo "Use this function to setup Domain File Manager for server"
echo "-------------------------------------------------------------------------"
echo "Domain File Manager must be new domain and not exited on system"
echo "-------------------------------------------------------------------------"
echo "You should use Sub-Domain for Domain File Manager"
echo "-------------------------------------------------------------------------"
echo -n "Type in the Domain [ENTER]: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You entered incorrectly, please re-enter !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Discover that $website is existed in the system!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
#############
echo "-------------------------------------------------------------------------"
echo -n "Type in Admin user [ENTER]: " 
read adminupload
if [ "$adminupload" = "" ]; then
echo "========================================================================="
echo "You must type in the user Admin."
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
if [[ ! ${#adminupload} -ge 5 ]]; then
clear
echo "========================================================================="
echo "User Admin must be at least 5 characters long "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 
checkuseradmin="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
if [[ ! "$adminupload" =~ $checkuseradmin ]]; then
clear
echo "========================================================================="
echo "You must use only numbers, letters for user admin."
echo "-------------------------------------------------------------------------"
echo "Please try again  !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 

echo "-------------------------------------------------------------------------"
echo -n "Type in the password [ENTER]: "
read matkhau
if [ "$matkhau" = "" ]; then
clear
echo "========================================================================="
echo "You must type in the password."
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
#checkpass="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
#if [[ ! "$matkhau" =~ $checkpass ]]; then
#clear
#echo "========================================================================="
#echo "Ban chi duoc dung chu cai va so de dat mat khau."
#echo "-------------------------------------------------------------------------"
#echo "Ban vui long thu lai  !"
#/etc/vpssim/menu/vpssim-web-upload-menu
#exit
#fi
if [[ ! ${#matkhau} -ge 8 ]]; then
clear
echo "========================================================================="
echo "Password must be at least 8 characters long "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi 
#######
echo "$website" > /etc/vpssim/uploadsite
echo "========================================================================="
echo "Prepare install File Manager for $website"
echo "-------------------------------------------------------------------------"
echo "For security, Search engine will be blocked from connecting to $website" 
echo "-------------------------------------------------------------------------"
echo "$website will not appear on the search engines: Google, Bing..."
echo "========================================================================="
sleep 10
    mkdir -p "/home/$website/public_html"
    mkdir -p "/home/$website/logs"
    cd /home/$website/public_html
wget --no-check-certificate -q https://hostingaz.vn/script/vpssim/eXtplorer/eXtplorer_2.1.9.zip
unzip -q eXtplorer_2.1.9.zip
rm -rf eXtplorer_2.1.9.zip
echo "please wait... "; sleep 2
rm -rf /home/$website/public_html/config/.htusers.php
cat > "/home/$website/public_html/config/.htusers.php" <<END
<?php
        // ensure this file is being included by a parent file
        if( !defined( '_JEXEC' ) && !defined( '_VALID_MOS' ) ) die( 'Restricted access' );
        \$GLOBALS["users"]=array(
        array('$adminupload','$(echo -n $matkhau | md5sum | cut -d" " -f1)','/home','http://localhost','1','','7',1),
);
?>
END
cd
cat > "/home/$website/public_html/robots.txt" <<END
User-agent: *
Disallow: /
END

chown -R nginx:nginx /home/$website/public_html/
    cat > "/etc/nginx/conf.d/$website.conf" <<END
server {
	    server_name www.$website;
	    rewrite ^(.*) http://$website\$1 permanent;
    	}
server {
	    listen   80;
    	access_log off;
    	error_log off;
    	# error_log /home/$website/logs/error.log;
    	root /home/$website/public_html;
include /etc/nginx/conf/ddos2.conf;
 	index index.php index.html index.htm;
    	server_name $website;
    	

#///////////////////////////////////////////////////////
#///////////////////////////////////////////////////////
include /etc/nginx/conf/supercache.conf;  

#Do not delete the bottom line, if you delete google pagespeed function will not work!!
#include /etc/nginx/ngx_pagespeed.conf;

#security, sql injection Propeller ....(uncoment if you want to use). Because some website plugins do not run with this config, so VPSSIM to turn off default
#include /etc/nginx/conf/block.conf;

    	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
        	include /etc/nginx/fastcgi_params;
        	fastcgi_pass 127.0.0.1:9000;
        	fastcgi_index index.php;
		fastcgi_connect_timeout 2000;
		fastcgi_send_timeout 2000;
		fastcgi_read_timeout 2000;
		fastcgi_buffer_size 256k;
		fastcgi_buffers 4 256k;
		fastcgi_busy_buffers_size 256k;
		fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;
        	fastcgi_param SCRIPT_FILENAME /home/$website/public_html\$fastcgi_script_name;
    	}
    	
include /etc/nginx/conf/staticfiles.conf;
#include /etc/nginx/conf/phpstatus.conf;
include /etc/nginx/conf/drop.conf;
#include /etc/nginx/conf/errorpage.conf;
    }
END
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx.service
systemctl restart php-fpm.service
fi
clear

echo "========================================================================="
echo "Point domain $(cat /etc/vpssim/uploadsite) to $serverip"
echo "-------------------------------------------------------------------------"
echo "And access to this domain on the browser for managing files on server."
echo "========================================================================="
echo "Admin info: User: $adminupload | Password: $matkhau "
/etc/vpssim/menu/vpssim-web-upload-menu
