#!/bin/sh
. /home/vpssim.conf

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpssim/menu/vpssim-xoa-website
	else
		echo "-------------------------------------------------------------------------"
service nginx start
		if [ "$(/sbin/service nginx status | awk 'NR==1 {print $5}')" == "running..." ]; then
/etc/vpssim/menu/vpssim-xoa-website
		else
	clear
	echo "========================================================================="
	echo "Sorry, Nginx is stopped. Please start it before use this function !"
	vpssim
		fi
fi
fi

if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "7" ]; then 
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
/etc/vpssim/menu/vpssim-xoa-website
	else
systemctl start nginx.service
	if [ "`systemctl is-active nginx.service`" == "active" ]; then
/etc/vpssim/menu/vpssim-xoa-website
		else
	clear
	echo "========================================================================="
	echo "Sorry, Nginx is stopped. Please start it before use this function !"
	vpssim
		fi
fi
fi
