#!/bin/bash
prompt="Type in your choice (5-Exit):"
if [ ! -f /usr/local/maldetect/conf.maldet ]; then
options=("Scan 1 website" "Scan All Websites" "Last Scan Report" "Install Linux Malware Detect" "Exit")
else
options=("Scan 1 website" "Scan All Websites" "Last Scan Report" "Remove Linux Malware Detect" "Exit")
fi
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
if [ ! -f /usr/local/maldetect/conf.maldet ]; then
printf "               Linux Malware Detect (LMD) - Not Install\n"
else
printf "                Linux Malware Detect (LMD) - Installed \n"
fi
printf "=========================================================================\n"
printf "\n"
PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


    1) /etc/vpssim/menu/vpssim-scan-website-maldet;;
    2) /etc/vpssim/menu/vpssim-scan-home-maldet;;
    3) /etc/vpssim/menu/vpssim-view-last-scan-report;;
    4) /etc/vpssim/menu/vpssim-befor-maldet-cai-dat;;
    5) clear && vpssim;;
        *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done





