#!/bin/bash
. /home/vpssim.conf
if [ ! -f /etc/vpssim/uploadsite ]; then
clear
echo "========================================================================="
echo "You have not installed File Manager for Server !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
uploadsite=$(cat /etc/vpssim/uploadsite)
if [ ! -f /etc/nginx/conf.d/$uploadsite.conf ]; then
clear
echo "========================================================================="
echo "The process of replacing domain File Manager error !"
echo "-------------------------------------------------------------------------"
echo "Please check again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi
echo "========================================================================= "
echo "Use this function to change Domain File Manager to other Domain"
echo "-------------------------------------------------------------------------"
read -r -p "You want to change $uploadsite to other domain ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
sleep 1
echo "-------------------------------------------------------------------------"
echo -n "Type in your new domain [ENTER]: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You entered incorrectly, please re-enter !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Discover that $website is existed in the system!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-web-upload-menu
exit
fi

echo "-------------------------------------------------------------------------"
echo "Please wait ..."; sleep 4

############
mv /home/$uploadsite /home/$website

checkfilemanagedomainconfig=$(grep auth_basic /etc/nginx/conf.d/$uploadsite.conf)
if [ "$checkfilemanagedomainconfig" == "" ]; then
  cat > "/etc/nginx/conf.d/$website.conf" <<END
server {
	    server_name www.$website;
	    rewrite ^(.*) http://$website\$1 permanent;
    	}
server {
	    listen   80;
    	access_log off;
    	error_log off;
    	# error_log /home/$website/logs/error.log;
    	root /home/$website/public_html;
include /etc/nginx/conf/ddos2.conf;
 	index index.php index.html index.htm;
    	server_name $website;
    	

#///////////////////////////////////////////////////////
#///////////////////////////////////////////////////////
include /etc/nginx/conf/supercache.conf;  

#security, sql injection Propeller ....(uncoment if you want to use). Because some website plugins do not run with this config, so VPSSIM to turn off default
#include /etc/nginx/conf/block.conf;

    	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
        	include /etc/nginx/fastcgi_params;
        	fastcgi_pass 127.0.0.1:9000;
        	fastcgi_index index.php;
		fastcgi_connect_timeout 2000;
		fastcgi_send_timeout 2000;
		fastcgi_read_timeout 2000;
		fastcgi_buffer_size 256k;
		fastcgi_buffers 4 256k;
		fastcgi_busy_buffers_size 256k;
		fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;
        	fastcgi_param SCRIPT_FILENAME /home/$website/public_html\$fastcgi_script_name;
    	}
    	
include /etc/nginx/conf/staticfiles.conf;
#include /etc/nginx/conf/phpstatus.conf;
include /etc/nginx/conf/drop.conf;
#include /etc/nginx/conf/errorpage.conf;
    }
END
else
  cat > "/etc/nginx/conf.d/$website.conf" <<END
server {
	    server_name www.$website;
	    rewrite ^(.*) http://$website\$1 permanent;
    	}
server {
	    listen   80;
    	access_log off;
    	error_log off;
    	# error_log /home/$website/logs/error.log;
    	root /home/$website/public_html;
    	auth_basic "Authorization Required";
auth_basic_user_file  /etc/nginx/.htpasswd;
include /etc/nginx/conf/ddos2.conf;
 	index index.php index.html index.htm;
    	server_name $website;
    	

#///////////////////////////////////////////////////////
#///////////////////////////////////////////////////////
include /etc/nginx/conf/supercache.conf;  

#security, sql injection Propeller ....(uncoment if you want to use). Because some website plugins do not run with this config, so VPSSIM to turn off default
#include /etc/nginx/conf/block.conf;

    	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
        	include /etc/nginx/fastcgi_params;
        	fastcgi_pass 127.0.0.1:9000;
        	fastcgi_index index.php;
		fastcgi_connect_timeout 2000;
		fastcgi_send_timeout 2000;
		fastcgi_read_timeout 2000;
		fastcgi_buffer_size 256k;
		fastcgi_buffers 4 256k;
		fastcgi_busy_buffers_size 256k;
		fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;
        	fastcgi_param SCRIPT_FILENAME /home/$website/public_html\$fastcgi_script_name;
    	}
    	
include /etc/nginx/conf/staticfiles.conf;
#include /etc/nginx/conf/phpstatus.conf;
include /etc/nginx/conf/drop.conf;
#include /etc/nginx/conf/errorpage.conf;
    }
END
fi
rm -rf /etc/nginx/conf.d/$uploadsite.conf
######################
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi
echo "$website" > /etc/vpssim/uploadsite
clear
echo "========================================================================="
echo "Point domain $(cat /etc/vpssim/uploadsite) to $serverip"
echo "-------------------------------------------------------------------------"
echo "And access to this domain on the browser for managing files on server."
/etc/vpssim/menu/vpssim-web-upload-menu
;;
esac
clear
echo "========================================================================="
echo "Cancel change domain File Manager"
/etc/vpssim/menu/vpssim-web-upload-menu
