#!/bin/bash

. /home/vpssim.conf
net2ftpsite=$(cat /tmp/net2ftpsite.info)
check_folder_protect_config()
{
if [ -d /etc/nginx/pwprotect/$net2ftpsite ]; then
cd /etc/nginx/pwprotect/$net2ftpsite
rm -rf * .??*
cd
rm -rf /etc/nginx/pwprotect/$net2ftpsite
fi
}

check_ftp_account()
{
if [ ! -f /etc/vpssim/FTP-Account.info ]; then
echo "=========================================================================" > /etc/vpssim/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "If you delete this file, VPSSIM will not run !" >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/vpssim/FTP-Account.info
echo "=========================================================================" >> /etc/vpssim/FTP-Account.info
echo "" >> /etc/vpssim/FTP-Account.info
fi
if [ -f /etc/pure-ftpd/pureftpd.passwd ]; then
if [ ! "$(grep /home/$net2ftpsite/ /etc/pure-ftpd/pureftpd.passwd)" == "" ];then  
rm -rf /tmp/abcd
cat > "/tmp/abcd" <<END	
sed -i '/\/home\/$net2ftpsite/d' /etc/pure-ftpd/pureftpd.passwd
END
chmod +x /tmp/abcd
/tmp/abcd
rm -rf /tmp/abcd
pure-pw mkdb
fi
fi
if [ ! "$(grep /home/$net2ftpsite/ /etc/vpssim/FTP-Account.info)" == "" ];then 
echo "========================================================================="
echo "Discover FTP Account: $(grep /home/$net2ftpsite/ /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') cua $net2ftpsite  "
echo "-------------------------------------------------------------------------"
echo "VPSSIM will remove FTP account: $(grep /home/$net2ftpsite/ /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}')"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
echo "-------------------------------------------------------------------------"
sleep 6
rm -rf /tmp/abcde
cat > "/tmp/abcde" <<END	
sed -i '/\/home\/$net2ftpsite/d' /etc/vpssim/FTP-Account.info
END
chmod +x /tmp/abcde
/tmp/abcde
rm -rf /tmp/abcde
fi
}
echo "========================================================================="
read -r -p "You want to remove domain Net2FTP ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait....";sleep 1
rm -rf /home/$net2ftpsite
rm -f /etc/nginx/conf.d/$net2ftpsite.conf 
if [ ! -f /etc/vpssim/opcache.blacklist ]; then
cat > "/etc/vpssim/opcache.blacklist" <<END
END
fi
if [ ! "$(grep /home/$net2ftpsite /etc/vpssim/opcache.blacklist)" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "Discovered $net2ftpsite in Zend Opcache Blacklist"
echo "-------------------------------------------------------------------------"
echo "VPSSIM will remove $net2ftpsite in this blacklist"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 6
rm -rf /tmp/zendcacheblacklist
cat > "/tmp/zendcacheblacklist" <<END
sed --in-place '\/home\/$net2ftpsite/d' /etc/vpssim/opcache.blacklist
END
chmod +x /tmp/zendcacheblacklist
/tmp/zendcacheblacklist
rm -rf /tmp/zendcacheblacklist
fi
check_ftp_account
check_and_delete_auto_backup_website()
{
	if [  -f /bin/vpssim-backupcode-$net2ftpsite ]; then
	if [ ! "$(grep vpssim-backupcode-$net2ftpsite /etc/cron.d/vpssim.code.cron)" == "" ]; then
echo "========================================================================="
echo "$net2ftpsite is being Enabled auto backup code"
echo "-------------------------------------------------------------------------"
echo "VPSSIM will Disable auto backup code while remove it from server"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 5
	rm -rf /bin/vpssim-backupcode-$net2ftpsite
	cat > "/tmp/removebackupcode" <<END
sed -i '/vpssim-backupcode-$net2ftpsite/d' /etc/cron.d/vpssim.code.cron
END
chmod +x /tmp/removebackupcode
/tmp/removebackupcode 
rm -rf /tmp/removebackupcode
service crond restart
	fi
	fi
}
check_and_delete_auto_backup_website
check_folder_protect_config
rm -rf /etc/vpssim/net2ftpsite.info
rm -rf /tmp/net2ftpsite.info
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi 
clear
echo "========================================================================= "
echo "Remove Domain Net2FTP successfully ! "
vpssim
;;
    *)
       clear 
echo "========================================================================= "
echo "Cancel remove Domain Net2FTP"
vpssim
        ;;
esac
clear 
echo "========================================================================= "
echo "Cancel remove Domain Net2FTP"
vpssim



