#!/bin/bash 

. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to update Wordpress code to latest Version"  
echo "-------------------------------------------------------------------------"
echo "Before update process, VPSSIM will backup website database"
echo "========================================================================="
#prompt="Nhap lua chon cua ban: "
prompt="Type in your choice: "
options=( "Update 1 website" "Update All Wordpress website" "Cancel")
printf "CHOOSE HOW TO UPDATE\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) luachonupdate="update1site"; break;;
    2) luachonupdate="updateall"; break;;
    3) chonphpversion="Cancel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    #*) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
###################################
#Update 1 website
###################################
if [ "$luachonupdate" = "update1site" ]; then
/etc/vpssim/menu/vpssim-update-wordpresss-code-for-website
###################################
#Update tat ca cac website
###################################
elif [ "$luachonupdate" = "updateall" ]; then
/etc/vpssim/menu/vpssim-update-wp-code-tat-ca-vps-website-wordpress
###################################
#Huy bo update
###################################
else 
clear && /etc/vpssim/menu/vpssim-wordpress-tools-menu
fi
