#!/bin/sh
. /home/vpssim.conf

echo "Prepare to restore Databases..."
sleep 1
find /home/$mainsite/private_html/backup/AllDB/ -type f -exec basename {} \;  > /tmp/backupname
filename=`cat /tmp/backupname`
rm -rf /tmp/backupname
cd /home/$mainsite/private_html/backup/AllDB
gunzip < $filename | mysql -u root -p$mariadbpass
cd
listdata=`date |md5sum |cut -c '1-4'`
cd /var/lib/mysql
echo "=========================================================================" > /home/$mainsite/private_html/listdata/$listdata-listdata.txt
echo "                             LIST DATABASE "                         >>/home/$mainsite/private_html/listdata/$listdata-listdata.txt
echo "=========================================================================" >> /home/$mainsite/private_html/listdata/$listdata-listdata.txt
tree -d -i -L 1 >> /home/$mainsite/private_html/listdata/$listdata-listdata.txt
sed -i 's/directories/database on VPS (mysql & performance_schema are default databases)/g' /home/$mainsite/private_html/listdata/$listdata-listdata.txt
echo "=========================================================================" >> /home/$mainsite/private_html/listdata/$listdata-listdata.txt
cd

clear
echo "========================================================================="
echo "Restores all Database completed !"
echo "-------------------------------------------------------------------------"
echo "List the databases on VPS:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/listdata/$listdata-listdata.txt"
/etc/vpssim/menu/vpssim-sao-luu-phuc-hoi-tat-ca-database-menu
