#!/bin/bash
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi
prompt="Type in your choice (6-Exit): "
options=("Create FTP Account" "Remove FTP Account" "Change FTP Account Password" "View FTP Account Info" "Remove FTP Server" )
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                           FTP Server Manage \n"
printf "=========================================================================\n"
echo ""
PS3="$prompt"
select opt in "${options[@]}" "Exit"; do 

    case "$REPLY" in
    
        1) /etc/vpssim/menu/vpssim-tao-ftp-user-cho-domain;;
        2) /etc/vpssim/menu/vpssim-xoa-ftp-user;;
		3) /etc/vpssim/menu/vpssim-thay-mat-khau-user-ftp;;
		4) /etc/vpssim/menu/vpssim-view-userftp-password;;
        5) /etc/vpssim/menu/vpssim-remove-ftp-server;;

$(( ${#options[@]}+1 )) ) echo "";  clear && vpssim;;
     *) echo "You typed wrong, Please type in the ordinal number on the list !";continue;;

    esac

done


