#!/bin/bash
prompt="Type in your choice (23-Exit):"
options=( "Change Password Root" "Fix Error Chmod, chown" "Find Top Largest Files & Folders" "Service Running & Ram Useage" "Check IP/Nameserver website" "File Size Converter " "Check Server info" "Setting Server Timezone" "Install / Remove Imagick" "Install / Remove Ioncube" "Install Htop" "Backup Config Files & Vhost" "Change SSH Port Number" "Config SSH Timeout" "Block Exploits, SQL Injections" "Deny Run Script In Upload Folder" "Protect Directory By Password" "ON/OFF Login Notification eMail" "ON/OFF Auto Run VPSSIM" "Low Disk Space Warning" "Restart Service" "Uninstall (Remove) VPSSIM"  "Exit" )
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                          Tools - Addons\n"
printf "=========================================================================\n"


PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


    1) /etc/vpssim/menu/vpssim-doi-pass-root-vps;;
    2) /etc/vpssim/menu/vpssim-sua-loi-chown;;
    3) /etc/vpssim/menu/tienich/vpssim-xem-danh-sach-max-dung-luong-file-menu;;
    4) /etc/vpssim/menu/tienich/vpssim-dich-vu-dang-chay-va-ram-dung;;
    5) /etc/vpssim/menu/tienich/vpssim-tim-ip-nameserver-website;;
    6) /etc/vpssim/menu/vpssim-chuyen-doi-don-vi-file-size-convert;;
    7) /etc/vpssim/menu/tienich/vpssim-view-thong-tin-ip-vps;;
    8) clear && /etc/vpssim/menu/vpssim-thay-doi-thong-tin-thoi-gian;; 
    9) /etc/vpssim/menu/tienich/vpssim-before-imagick;;
    10) /etc/vpssim/menu/tienich/vpssim-before-ioncube;;
    11) /etc/vpssim/menu/tienich/vpssim-cai-dat-htop;;
    12) /etc/vpssim/menu/vpssim-sao-luu-sys;;
    13) /etc/vpssim/menu/vpssim-thay-doi-port-ssh;;
    14) /etc/vpssim/menu/vpssim-bat-tat-ssh-time-out;;
    15) /etc/vpssim/menu/vpssim-block-exploits-sql-injections-menu;;
    16) /etc/vpssim/menu/vpssim-chan-run-script-trong-folder-upload-menu;;
    17) /etc/vpssim/menu/vpssim-dat-mat-khau-bao-ve-folder-website;;
    18) /etc/vpssim/menu/vpssim-bat-tat-email-thong-bao-dang-nhap-server;;
	19) /etc/vpssim/menu/vpssim-bat-tat-tu-dong-chay-vpssim;;
	20) /etc/vpssim/menu/vpssim-config-canh-bao-dung-luong-disc-trong-free-it;;
    21) clear && /etc/vpssim/menu/tienich/vpssim-restart-service;;
    22) /etc/vpssim/menu/vpssim-go-bo-scripts;;
    23) clear && vpssim;;

  *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac
done
