#!/bin/bash 
. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to ALLOW/DENY run script inside writable folder"
echo "-------------------------------------------------------------------------"
echo "Folder:uploads,images,cache,media,logs,tmp - Script: PHP,PL,PY,JSP,SH,CGI "  
echo "-------------------------------------------------------------------------"
echo "Edit rules at: /etc/nginx/conf/deny-script-writeable-folder.conf"
echo "========================================================================="
nhapwebsite() {
echo -n "Type in website: "  
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ -f /etc/vpssim/net2ftpsite.info ]; then
net2ftpsite=$(cat /etc/vpssim/net2ftpsite.info)
if [ "$website" = "$net2ftpsite" ]; then
clear
echo "========================================================================="
echo "$website is domain Net2FTP"
echo "-------------------------------------------------------------------------"
echo "You can not use this function."
/etc/vpssim/menu/vpssim-tien-ich
fi
fi



if [ "$website" = "" ]; then
echo "-------------------------------------------------------------------------"
echo "You typed wrong, please type in accurately"
echo "-------------------------------------------------------------------------"
nhapwebsite
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
echo "-------------------------------------------------------------------------"
echo "$website maybe not a domain name! !"
echo "-------------------------------------------------------------------------"
nhapwebsite
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
if [ ! -f /etc/nginx/conf.d/www.$website.conf ]; then
echo "-------------------------------------------------------------------------"
echo "Can not discover $website in server "
echo "-------------------------------------------------------------------------"
nhapwebsite
fi
fi
if [ -f /etc/nginx/conf.d/www.$website.conf ]; then
if [ "$(grep block.conf /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
clear
echo "========================================================================="
echo "You have changed default Vhost config for $website"
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not finish your request"
/etc/vpssim/menu/vpssim-block-exploits-sql-injections-menu
exit
fi
fi
if [ -f /etc/nginx/conf.d/$website.conf ]; then
if [ "$(grep block.conf /etc/nginx/conf.d/$website.conf)" == "" ]; then
clear
echo "========================================================================="
echo "You have changed default Vhost config for $website"
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not finish your request"
/etc/vpssim/menu/vpssim-block-exploits-sql-injections-menu
exit
fi
fi
if [ -f /etc/nginx/conf.d/wwww.$website.conf ]; then
	if [ "$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
	check=bat
	elif [ ! "$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
		if [ ! "$(grep "#include /etc/nginx/conf/deny-script-writeable-folder.conf;" /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
	check=bat
		fi
	fi
fi

if [ -f /etc/nginx/conf.d/$website.conf ]; then
	if [ "$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/$website.conf)" == "" ]; then
	check=bat
	elif [ ! "$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/$website.conf)" == "" ]; then
		if [ ! "$(grep "#include /etc/nginx/conf/deny-script-writeable-folder.conf;" /etc/nginx/conf.d/$website.conf)" == "" ]; then
		check=bat
		fi
	fi
fi
if [ ! "$check" == "bat" ]; then
echo "========================================================================="
echo "$website current DENY Running Script inside writable directories "
echo "-------------------------------------------------------------------------"
read -r -p "ALLOW running Script inside writable directories ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait..."   		
    sleep 1 
    rm -rf /tmp/chanrunscriptuploadfolder.sh 
         cat > "/tmp/chanrunscriptuploadfolder.sh" <<END
#!/bin/sh
if [ -f /etc/nginx/conf.d/$website.conf ]; then
sed -i '/writable-directories/d' /etc/nginx/conf.d/$website.conf 
sed -i '/deny-script-writeable-folder/d' /etc/nginx/conf.d/$website.conf 
fi
if [ -f /etc/nginx/conf.d/www.$website.conf ]; then
sed -i '/writable-directories/d' /etc/nginx/conf.d/www.$website.conf 
sed -i '/deny-script-writeable-folder/d' /etc/nginx/conf.d/www.$website.conf 
fi
END
chmod +x /tmp/chanrunscriptuploadfolder.sh
/tmp/chanrunscriptuploadfolder.sh
rm -f /tmp/chanrunscriptuploadfolder.sh
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
else
systemctl reload nginx
fi
clear
echo "========================================================================="
echo "ALLOW run Script inside writable folder for $website successfully!"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
    *)
       clear
    echo "========================================================================="
   echo "Cancel ALLOW run Script inside writable folder for $website"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
esac
exit
fi
echo "========================================================================="
echo "$website current ALLOW Running Script inside writable folder "
echo "-------------------------------------------------------------------------"
read -r -p "DENY Running Script inside writable folder ?  [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
echo "-------------------------------------------------------------------------"
		echo "Please wait..."
		sleep 1
  cat > "/tmp/chanrunscriptuploadfolder.sh" <<END
#!/bin/sh
if [ -f /etc/nginx/conf.d/$website.conf ]; then
	if [ "\$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/$website.conf)" == "" ]; then
	sed -i "/.*block.conf*./a#Deny\ scripts\ inside\ writable-directories" /etc/nginx/conf.d/$website.conf
	#sed -i "s/.*writable-directories*./\n&/" /etc/nginx/conf.d/$website.conf
	sed -i "/.*writable-directories*./ainclude \/etc\/nginx\/conf\/deny-script-writeable-folder.conf;" /etc/nginx/conf.d/$website.conf
	fi
	if [ ! "\$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/$website.conf)" == "" ]; then
	sed -i 's/.*deny-script-writeable-folder.conf.*/include \/etc\/nginx\/conf\/deny-script-writeable-folder.conf;/g' /etc/nginx/conf.d/$website.conf
	fi
fi
if [ -f /etc/nginx/conf.d/www.$website.conf ]; then
	if [ "\$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
	sed -i "/.*block.conf*./a#Deny\ scripts\ inside\ writable-directories" /etc/nginx/conf.d/www.$website.conf
	sed -i "/.*writable-directories*./ainclude \/etc\/nginx\/conf\/deny-script-writeable-folder.conf;" /etc/nginx/conf.d/www.$website.conf
	fi
	if [ ! "\$(grep deny-script-writeable-folder.conf /etc/nginx/conf.d/www.$website.conf)" == "" ]; then
	sed -i 's/.*deny-script-writeable-folder.conf.*/include \/etc\/nginx\/conf\/deny-script-writeable-folder.conf;/g' /etc/nginx/conf.d/www.$website.conf
	fi
fi
END
chmod +x /tmp/chanrunscriptuploadfolder.sh
/tmp/chanrunscriptuploadfolder.sh
rm -f /tmp/chanrunscriptuploadfolder.sh
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
else
systemctl reload nginx
fi
clear
echo "========================================================================="
echo "DENY run script inside writable folder for $website successfully"
/etc/vpssim/menu/vpssim-tien-ich
       ;;
    *)
    clear
    echo "========================================================================="
   echo "Cancel DENY run script inside writable folder for $website"
/etc/vpssim/menu/vpssim-tien-ich
        ;;
esac
exit
}
nhapwebsite
