#!/bin/bash 
. /home/vpssim.conf
if [ ! -f /etc/vpssim/vps_backup_rsync.info ]; then
clear
echo "========================================================================="
echo "This server has not configured connect to VPS Backup yet"
echo "-------------------------------------------------------------------------"
echo "You must using option #1 to config connect to VPS Backup first."
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi
if [ -f /etc/vpssim/vpssim_backup_VPS_by_rsync ]; then
	if [ ! -f /etc/cron.d/vpssim.rsync.cron ]; then
	rm -rf /etc/vpssim/vpssim_backup_VPS_by_rsync
	fi
fi
if [ -f /etc/cron.d/vpssim.rsync.cron ]; then
	if [ ! -f /etc/vpssim/vpssim_backup_VPS_by_rsync ]; then
	rm -rf /etc/cron.d/vpssim.rsync.cron
	fi
fi
if [ -f /etc/vpssim/vpssim_backup_VPS_by_rsync ]; then
minutesrsync=$(grep vpssim_backup_VPS_by_rsync /etc/cron.d/vpssim.rsync.cron | awk 'NR==1 {print $1}' | sed 's/*\///')
clear
echo "========================================================================="
echo "Current VPSSIM auto sync Data to VPS Backup every $minutesrsync minutes"
echo "-------------------------------------------------------------------------"
echo "If you want to change this time. You must [ Disable Sync To VPS Backup ] "
echo "-------------------------------------------------------------------------"
echo "first then Re-Connect To VPS Backup again."
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi
ipvpsbackup=$(grep "ipaddress" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')
echo "-------------------------------------------------------------------------"
echo "Connecting to VPS Backup ... "
checkconnect=$(ssh -o BatchMode=yes -o ConnectTimeout=9 root@$ipvpsbackup echo connected 2>&1)
if [[ ! $checkconnect == connected ]] ; then
clear
echo "========================================================================="
echo "Connection Failed !"
echo "-------------------------------------------------------------------------"
echo "You can not use this function"
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi



prompt="Type in your choice:  "
echo "========================================================================="
echo "You want also backup all backup files (websites & databases) ?"
echo "========================================================================="
options=( "Backup All Websites Include $mainsite" "Backup All Websites Exclude $mainsite (Contain Backup Files) " "Cancel")
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) chooseaction="backuptatca"; break;;
    2) chooseaction="khongbackupmainsite"; break;;
    3) chooseaction="calcel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
make_script_backup () {
rm -rf /etc/vpssim/vpssim_backup_VPS_by_rsync
ipvpsbackup=$(grep "ipaddress" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')
cat > "/etc/vpssim/vpssim_backup_VPS_by_rsync" <<END
#!/bin/bash
ssh root@$ipvpsbackup mkdir -p /home/VPS-$serverip 
ssh root@$ipvpsbackup mkdir -p /home/VPS-$serverip/etc
if [ "\$(grep "Createfolder" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "Cai dat rsync and wget cho VPS Backup "
echo "-------------------------------------------------------------------------"
ssh root@$ipvpsbackup apt-get -y -q install rsync wget tar
ssh root@$ipvpsbackup yum -y -q install rsync wget tar
echo "Createfolder = thanhcong" >> /etc/vpssim/vps_backup_rsync.info
fi
echo "The most recent backup: $(date +%T/%d/%m/%Y)" > /home/00-Time-Backup.txt
rsync -avzq -e ssh /etc/vpssim/menu/vpssim-rsync-motd root@$ipvpsbackup:/etc/motd
rsync -avz -e ssh --exclude={cache,.cache,vpssim.conf} /home/ root@$ipvpsbackup:/home/VPS-$serverip/home/
rsync -avz -e ssh /var/lib/mysql/ root@$ipvpsbackup:/home/VPS-$serverip/mysql/
rsync -avz -e ssh /etc/nginx/ root@$ipvpsbackup:/home/VPS-$serverip/etc/nginx/
rsync -avz -e ssh /etc/my.cnf.d/ root@$ipvpsbackup:/home/VPS-$serverip/etc/my.cnf.d/
rsync -avz -e ssh /etc/php-fpm.d/ root@$ipvpsbackup:/home/VPS-$serverip/etc/php-fpm.d/
ssh root@$ipvpsbackup rm -rf /home/VPS-$serverip/etc/nginx/conf.d/$mainsite.conf
END
chmod +x /etc/vpssim/vpssim_backup_VPS_by_rsync
}

make_script_backup_no_sim_domain_com() {
rm -rf /etc/vpssim/vpssim_backup_VPS_by_rsync
ipvpsbackup=$(grep "ipaddress" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')
cat > "/etc/vpssim/vpssim_backup_VPS_by_rsync" <<END
#!/bin/bash
ssh root@$ipvpsbackup mkdir -p /home/VPS-$serverip 
ssh root@$ipvpsbackup mkdir -p /home/VPS-$serverip/etc
if [ "\$(grep "Createfolder" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "Cai dat rsync and wget cho VPS Backup "
echo "-------------------------------------------------------------------------"
ssh root@$ipvpsbackup apt-get -y -q install rsync wget tar
ssh root@$ipvpsbackup yum -y -q install rsync wget tar
echo "Createfolder = thanhcong" >> /etc/vpssim/vps_backup_rsync.info
fi
echo "The most recent backup: $(date +%T/%d/%m/%Y)" > /home/00-Time-Backup.txt
rsync -avzq -e ssh /etc/vpssim/menu/vpssim-rsync-motd root@$ipvpsbackup:/etc/motd
rsync -avz -e ssh --exclude={$mainsite,cache,.cache,vpssim.conf} /home/ root@$ipvpsbackup:/home/VPS-$serverip/home/
rsync -avz -e ssh /var/lib/mysql/ root@$ipvpsbackup:/home/VPS-$serverip/mysql/
rsync -avz -e ssh /etc/nginx/ root@$ipvpsbackup:/home/VPS-$serverip/etc/nginx/
rsync -avz -e ssh /etc/my.cnf.d/ root@$ipvpsbackup:/home/VPS-$serverip/etc/my.cnf.d/
rsync -avz -e ssh /etc/php-fpm.d/ root@$ipvpsbackup:/home/VPS-$serverip/etc/php-fpm.d/
ssh root@$ipvpsbackup rm -rf /home/VPS-$serverip/etc/nginx/conf.d/$mainsite.conf
END
chmod +x /etc/vpssim/vpssim_backup_VPS_by_rsync
}
###################################
#backuptatca
###################################
if [ "$chooseaction" = "backuptatca" ]; then
make_script_backup
echo "-------------------------------------------------------------------------"
echo "VPSSIM will backup all websites include $mainsite"
echo "-------------------------------------------------------------------------"
echo "($mainsite contain all backup files of websites & databases)"
###################################
#khongbackupmainsite
###################################
elif [ "$chooseaction" = "khongbackupmainsite" ]; then
make_script_backup_no_sim_domain_com
echo "-------------------------------------------------------------------------"
echo "VPSSIM will backup all websites exclude $mainsite"
echo "-------------------------------------------------------------------------"
echo "($mainsite contain all backup files of websites & databases)"
###################################
else 
clear && /etc/vpssim/menu/vpssim-rsync-backup-vps-menu
fi
prompt="Type in your choice: "
options=( "Every 5 Minutes" "Every 10 Minutes" "Every 20 Minutes" "Every 40 Minutes" "Every 59 Minutes" "Cancel")
  echo "========================================================================="
  echo "Setting The Time Auto Sync Data To VPS Backup"
  echo "========================================================================="
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) timersync="5phut1lan"; break;;
    2) timersync="10phut1lan"; break;;
    3) timersync="20phut1lan"; break;;
    4) timersync="40phut1lan"; break;;
    5) timersync="59phut1lan"; break;;
    6) timersync="huybo"; break;;
    #*) echo "Ban nhap sai, Vui long nhap theo danh sach trong list";continue;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
set_time_run_rsync () {
rm -rf /etc/cron.d/vpssim.rsync.cron
echo "SHELL=/bin/sh" > /etc/cron.d/vpssim.rsync.cron
echo "*/$phut * * * * root /etc/vpssim/vpssim_backup_VPS_by_rsync >/dev/null 2>&1" >> /etc/cron.d/vpssim.rsync.cron
}

###################################
#5phut1lan
###################################
if [ "$timersync" = "5phut1lan" ]; then
phut=5
#make_script_backup
set_time_run_rsync

###################################
#10phut1lan
###################################
elif [ "$timersync" = "10phut1lan" ]; then
phut=10
#make_script_backup
set_time_run_rsync
###################################
#20phut1lan
###################################
elif [ "$timersync" = "20phut1lan" ]; then
phut=20
#make_script_backup
set_time_run_rsync
###################################
#40phut1lan
###################################
elif [ "$timersync" = "40phut1lan" ]; then
phut=40
#make_script_backup
set_time_run_rsync
###################################
#59phut1lan
###################################
elif [ "$timersync" = "59phut1lan" ]; then
phut=59
#make_script_backup
set_time_run_rsync
else
rm -rf /etc/vpssim/vpssim_backup_VPS_by_rsync
clear
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
###################################
fi

echo "-------------------------------------------------------------------------"
read -r -p "You want VPSSIM sync data to vps backup every $phut minutes  ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ..."
    sleep 2
service crond restart
clear
  echo "========================================================================="
  echo "Setting the time sync data successful"
  echo "-------------------------------------------------------------------------"
  echo "Every $phut minutes, VPSSIM auto sync data to VPS backup."
  echo "-------------------------------------------------------------------------"
  echo "Backup folder on VPS backup: /home/VPS-$serverip"
  /etc/vpssim/menu/vpssim-rsync-backup-vps-menu
 
;;
*)
rm -rf /etc/cron.d/vpssim.rsync.cron
rm -rf /etc/vpssim/vpssim_backup_VPS_by_rsync
clear
echo "========================================================================="
echo "Cancel setting sync time with VPS backup!"
  /etc/vpssim/menu/vpssim-rsync-backup-vps-menu
  exit
;;
esac
exit
