#!/bin/bash
. /home/vpssim.conf

if [ ! -f /etc/pure-ftpd/pure-ftpd.conf ]; then
clear
echo "========================================================================= "
echo "FTP server is not installed "
echo "-------------------------------------------------------------------------"
echo "You must run Setup FTP server function first !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
echo "========================================================================="
echo "Use this function to create FTP account for website"
echo "-------------------------------------------------------------------------"
echo -n "Type in the website [ENTER]: " 
read website
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please type in accurately !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,14}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
clear
echo "========================================================================="
echo "$website maybe not a domain name"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not discover $website"
echo "-------------------------------------------------------------------------"
echo "Please try again ."
/etc/vpssim/menu/vpssim-ftpserver-menu
exit
fi
if [ ! -f /etc/pure-ftpd/pureftpd.passwd ]; then
touch /etc/pure-ftpd/pureftpd.passwd
fi
if [ ! "$(pure-pw list | grep "/home/$website/")" == "" ]; then
clear
echo "========================================================================="
echo "You have create FTP account for $website" 
echo "-------------------------------------------------------------------------"
echo "FTP account info:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') | Password: $(grep "/home/$website/" /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $10}')"
/etc/vpssim/menu/vpssim-ftpserver-menu
fi
echo "-------------------------------------------------------------------------"
echo "Discover $website in system"
echo "-------------------------------------------------------------------------"
echo "There's no FTP account for $website"
echo "-------------------------------------------------------------------------"
echo "VPSSIM will create FTP  account for $website"
echo "-------------------------------------------------------------------------"
echo "Please wait..."; sleep 6


echo "$website" > /tmp/vpssimftp.txt
sed -i '  s/\./_/g' /tmp/vpssimftp.txt
sed -i 's/\-/_/g' /tmp/vpssimftp.txt
username=`cat /tmp/vpssimftp.txt | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | sed "s/\_//" | cut -c1-30`
password=`date |md5sum |cut -c '3-23'`
#useradd -m -d /home/$website -g nginx -p $password $username
#usermod -aG nginx $username
#chmod g+rxw /home/$website
( echo ${password} ; echo ${password} ) | pure-pw useradd $username -u nginx -g nginx -d /home/$website -m 
pure-pw mkdb
rm -rf /tmp/ftpvpssim.temp;
pure-pw mkdb
if [ ! -f /etc/vpssim/FTP-Account.info ]; then
echo "=========================================================================" > /etc/vpssim/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "If you delete this file, VPSSIM will not run !" >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/vpssim/FTP-Account.info
echo "=========================================================================" >> /etc/vpssim/FTP-Account.info
echo "" >> /etc/vpssim/FTP-Account.info
fi
################
echo "FTP Account for $website | Username: $username | Password: $password | dd /home/$website/ " >> /etc/vpssim/FTP-Account.info
clear
echo "=========================================================================" 
echo "Create FTP account for $website successful"
echo "-------------------------------------------------------------------------"
echo "Login info:"
echo "-------------------------------------------------------------------------"
echo "IP: $serverip "
echo "-------------------------------------------------------------------------"
echo "User: $username | Password: $password"
/etc/vpssim/menu/vpssim-ftpserver-menu
