#!/bin/bash

. /home/vpssim.conf

echo "========================================================================="
echo "Use this function to renew certificate (Let's Encrypt) for domain."
echo "-------------------------------------------------------------------------"
echo -n "Type in the domain [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
websiteTO=`echo $website | tr '[a-z]' '[A-Z]'`
if [ "$website" = "" ]; then
clear
echo "========================================================================="
echo "The Domain name can not be empty"
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi

if [ ! -f /etc/nginx/conf.d/$website.conf ]; then
clear
echo "========================================================================="
echo "Can not find $website in server "
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi  

if [ ! -d /home/$website/public_html ]; then
clear
echo "========================================================================="
echo "Can not find folder public_html of $website"
echo "-------------------------------------------------------------------------"
echo "You can not using this function."
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi
##############

echo "Check $website when Setup SSL" > /home/$website/public_html/vpssim.check
checkurlsttSSL=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://$website/vpssim.check")
checkurlstt=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "http://$website/vpssim.check")
rm -rf /home/$website/public_html/vpssim.check

if [ ! "$checkurlstt" = "200" ] && [ ! "$checkurlsttSSL" = "200" ]; then
clear
echo "========================================================================="
echo "You have not point $website to $serverip yet !"
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not run this function.."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi

if [ "$(grep "/etc/nginx/auth-acme/$website/$website.crt" /etc/nginx/conf.d/$website.conf)" = "" ] && [ "$checkurlsttSSL" == "200" ]; then
clear
echo "========================================================================="
echo "$websiteTO using SSL but do not using Let's Encrypt."
echo "-------------------------------------------------------------------------"
echo "VPSSIM can not run this function.."
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi

if [ ! "$(grep "/etc/nginx/auth-acme/$website/$website.crt" /etc/nginx/conf.d/$website.conf)" = "" ] && [ "$checkurlsttSSL" == "200" ]; then

curTime=$(date +%s)
thoigiangiahangiay=`cat /root/.acme.sh/$website/$website.conf | grep Le_NextRenewTime= | cut -d \" -f 2`
hieuthoigianconlai=$(calc $thoigiangiahangiay-$curTime)
thoigiannengiahan=$(calc $hieuthoigianconlai/60/60/24)
thoigianconlai=$(calc $thoigiannengiahan+10)

if [ "$thoigianconlai" -lt 10 ]; then
echo "------------------------------------------------------------------------"
echo "$websiteTO's certificates valid for: $thoigianconlai days"
echo "------------------------------------------------------------------------"
echo "VPSSIM will renew this certificates."
echo "------------------------------------------------------------------------"
echo "Please wait ..."; sleep 3
/root/.acme.sh/acme.sh --renew --domain $website -f

curTime2=$(date +%s)
thoigiangiahangiay2=`cat /root/.acme.sh/$website/$website.conf | grep Le_NextRenewTime= | cut -d \" -f 2`
hieuthoigianconlai2=$(calc $thoigiangiahangiay2-$curTime)
thoigiannengiahan2=$(calc $hieuthoigianconlai2/60/60/24)
thoigianconlai2=$(calc $thoigiannengiahan2+10)
clear
echo "========================================================================="
echo "Completed to renew certificate for $websiteTO ."
echo "-------------------------------------------------------------------------"
echo "$websiteTO's certificate valid for: $thoigianconlai2 days."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi

if [ "$thoigianconlai" -gt 10 ] && [ "$thoigianconlai" -lt 60 ]; then
echo "========================================================================="
echo "$websiteTO's certificates valid for $thoigianconlai days."
echo "-------------------------------------------------------------------------"
echo "The valid time > 10 days."
echo "========================================================================="
  read -r -p "You want to renew certificate for $website ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ..."; sleep 3
/root/.acme.sh/acme.sh --renew --domain $website -f
curTime2=$(date +%s)
thoigiangiahangiay2=`cat /root/.acme.sh/$website/$website.conf | grep Le_NextRenewTime= | cut -d \" -f 2`
hieuthoigianconlai2=$(calc $thoigiangiahangiay2-$curTime)
thoigiannengiahan2=$(calc $hieuthoigianconlai2/60/60/24)
thoigianconlai2=$(calc $thoigiannengiahan2+10)
clear
echo "========================================================================="
echo "Completed to renew certificate for $websiteTO ."
echo "-------------------------------------------------------------------------"
echo "$websiteTO's certificate valids for: $thoigianconlai2 days."
/etc/vpssim/menu/vpssim-letsencrypt-menu
;;
    *)
clear 
echo "========================================================================= "
echo "Cancel !"
/etc/vpssim/menu/vpssim-letsencrypt-menu
        ;;
esac
fi

if [ "$thoigianconlai" -gt 61 ]; then
clear 
echo "========================================================================= "
echo "$websiteTO's certificates till valids for $thoigianconlai days."
echo "-------------------------------------------------------------------------"
echo "You do not to renew this certificate."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi
fi

if [ -f /root/.acme.sh/$website/$website.conf ] && [ "$checkurlstt" == "200" ]; then
yes | cp -rf  /etc/vpssim/Backup.Vhost.SSL/$website/$website.conf /home/$website/$website.conf_HTTP
yes | cp -rf  /etc/vpssim/Backup.Vhost.SSL/$website/$website.conf_HTTPS /home/$website/$website.conf_HTTPS
clear
echo "========================================================================="
echo "You have created certificate for $website but did not finish setup."
echo "-------------------------------------------------------------------------"
echo "You must to edit the Vhost file of $website follow:"
echo "-------------------------------------------------------------------------"
echo "File Vhost: /etc/nginx/conf.d/$website.conf"
echo "-------------------------------------------------------------------------"
echo "Backup Vhost: /home/$website/$website.conf_HTTP"
echo "-------------------------------------------------------------------------"
echo "SSL Vhost: /home/$website/$website.conf_HTTPS"
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi

if [ ! -f /root/.acme.sh/$website/$website.conf ] && [ "$checkurlstt" == "200" ]; then
clear
echo "========================================================================="
echo "You did not setup SSL Let's Encrypt for $website !"
/etc/vpssim/menu/vpssim-letsencrypt-menu
exit
fi
