#!/bin/bash 

. /home/vpssim.conf

prompt="Type in your choice: "
options=( "1 Website" "All Websites" "Cancel")
printf "=========================================================================\n"
printf "GET LINK BACKUP FILE FOR 1 WEBSITE OR ALL WEBSITEs\n"
printf "=========================================================================\n"
PS3="$prompt"
select opt in "${options[@]}"; do 

    case "$REPLY" in
    1) laylink="1website"; break;;
    2) laylink="tatca"; break;;
    3) laylink="Cancel"; break;;
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;
    esac  
done
###################################
#
###################################
if [ "$laylink" = "1website" ]; then
/etc/vpssim/menu/vpssim-link-tai-sao-luu-1-site
###################################
#
###################################
elif [ "$laylink" = "tatca" ]; then
/etc/vpssim/menu/vpssim-link-download-tat-ca-backup-website-sao-luu
###################################
#
###################################
else 
clear && /etc/vpssim/menu/vpssim-sao-luu
fi
