#!/bin/bash

. /home/vpssim.conf
if [ ! -f /etc/vpssim/net2ftpsite.info ]; then
clear
echo "========================================================================="
echo "You have not installed Net2FTP for server !"
/etc/vpssim/menu/vpssim-net2ftp-menu
exit
fi
net2ftpsite=$(cat /etc/vpssim/net2ftpsite.info)
if [ -f /home/$net2ftpsite/public_html/index.php ]; then 
echo "========================================================================="
echo "Current Net2FTP is ENABLE"
echo "========================================================================="
read -r -p "Do you want to DISABLE it ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "Please wait....";sleep 1
	mv /home/$net2ftpsite/public_html/index.php /home/$net2ftpsite/public_html/index.bak
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi
	rm -f /home/$net2ftpsite/public_html/index.html
    cat > "/home/$net2ftpsite/public_html/index.html" <<END
<!DOCTYPE html>
<html id="VPSSIM" lang="en-US" dir="LTR" class="Public Cute Pig" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<meta charset="utf-8"/>
<title>Cute Pig !!!</title>
</head>
<body>
<center><img src="https://hostingaz.vn/script/vpssim/pig.jpg"></center><br><br>
<center>What do you want?</center>
</body>
</html>
END
clear
echo "========================================================================="
echo "Net2FTP is DISABLE successfully!"
/etc/vpssim/menu/vpssim-net2ftp-menu
        ;;
    *)
clear
 echo "========================================================================="
echo "You chose NO  !"
/etc/vpssim/menu/vpssim-net2ftp-menu
        ;;
esac
exit
fi
echo "========================================================================="
echo "Current Net2FTP is DISABLE"
echo "========================================================================="
read -r -p "Do you want to ENABLE it ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "Please wait....";sleep 1
	mv /home/$net2ftpsite/public_html/index.bak /home/$net2ftpsite/public_html/index.php
	rm -f /home/$net2ftpsite/public_html/index.html
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi
clear
        echo "========================================================================="
        echo "Net2FTP is ENABLE successfully !"
/etc/vpssim/menu/vpssim-net2ftp-menu
        ;;
    *)
               clear
 echo "========================================================================="
echo "You choose NO!"
/etc/vpssim/menu/vpssim-net2ftp-menu

        ;;
esac
exit
fi
