#!/bin/bash 
. /home/vpssim.conf
uploadsite=$(cat /tmp/uploadsite)
check_folder_protect_config()
{
if [ -d /etc/nginx/pwprotect/$uploadsite ]; then
cd /etc/nginx/pwprotect/$uploadsite
rm -rf * .??*
cd
rm -rf /etc/nginx/pwprotect/$uploadsite
fi
}
check_ftp_account()
{
if [ ! -f /etc/vpssim/FTP-Account.info ]; then
echo "=========================================================================" > /etc/vpssim/FTP-Account.info
echo "Please Do Not Delete This File " >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "If you delete this file, VPSSIM will not run !" >> /etc/vpssim/FTP-Account.info
echo "-------------------------------------------------------------------------" >> /etc/vpssim/FTP-Account.info
echo "All FTP User for all domain on VPS list below:" >> /etc/vpssim/FTP-Account.info
echo "=========================================================================" >> /etc/vpssim/FTP-Account.info
echo "" >> /etc/vpssim/FTP-Account.info
fi
if [ -f /etc/pure-ftpd/pureftpd.passwd ]; then
if [ ! "$(grep /home/$uploadsite/ /etc/pure-ftpd/pureftpd.passwd)" == "" ];then  
rm -rf /tmp/abcd
cat > "/tmp/abcd" <<END	
sed -i '/\/home\/$uploadsite/d' /etc/pure-ftpd/pureftpd.passwd
END
chmod +x /tmp/abcd
/tmp/abcd
rm -rf /tmp/abcd
pure-pw mkdb
fi
fi
if [ ! "$(grep /home/$uploadsite/ /etc/vpssim/FTP-Account.info)" == "" ];then 
echo "========================================================================="
echo "Discover FTP Account: $(grep /home/$uploadsite/ /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}') for $uploadsite  "
echo "-------------------------------------------------------------------------"
echo "VPSSIM will remove FTP account: $(grep /home/$uploadsite/ /etc/vpssim/FTP-Account.info | awk 'NR==1 {print $7}')"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 6
rm -rf /tmp/abcde
cat > "/tmp/abcde" <<END	
sed -i '/\/home\/$uploadsite/d' /etc/vpssim/FTP-Account.info
END
chmod +x /tmp/abcde
/tmp/abcde
rm -rf /tmp/abcde
fi
}
echo "========================================================================="
echo "Domain you want to remove is Domain File Manager"
echo "-------------------------------------------------------------------------"
read -r -p "You want to remove this domain from server ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait....";sleep 1
rm -rf /etc/vpssim/uploadsite
rm -rf /home/$uploadsite
rm -f /etc/nginx/conf.d/$uploadsite.conf 
if [ ! -f /etc/vpssim/opcache.blacklist ]; then
cat > "/etc/vpssim/opcache.blacklist" <<END
END
fi
if [ ! "$(grep /home/$uploadsite /etc/vpssim/opcache.blacklist)" == "" ]; then
echo "-------------------------------------------------------------------------"
echo "Discovered $uploadsite in Zend Opcache Blacklist"
echo "-------------------------------------------------------------------------"
echo "VPSSIM will remove $uploadsite in this Zend Opcache blacklist"
echo "-------------------------------------------------------------------------"
echo "Please wait.... !"
sleep 6
rm -rf /tmp/zendcacheblacklist
cat > "/tmp/zendcacheblacklist" <<END
sed --in-place '\/home\/$uploadsite/d' /etc/vpssim/opcache.blacklist
END
chmod +x /tmp/zendcacheblacklist
/tmp/zendcacheblacklist
rm -rf /tmp/zendcacheblacklist
fi
check_ftp_account
check_and_delete_auto_backup_website()
{
	if [  -f /bin/vpssim-backupcode-$uploadsite ]; then
	if [ ! "$(grep vpssim-backupcode-$uploadsite /etc/cron.d/vpssim.code.cron)" == "" ]; then
echo "========================================================================="
echo "$uploadsite is being Enabled auto backup code"
echo "-------------------------------------------------------------------------"
echo "VPSSIM will Disable auto backup code while remove it from server"
echo "-------------------------------------------------------------------------"
echo "Please wait ...."
sleep 5
	rm -rf /bin/vpssim-backupcode-$uploadsite
	cat > "/tmp/removebackupcode" <<END
sed -i '/vpssim-backupcode-$uploadsite/d' /etc/cron.d/vpssim.code.cron
END
chmod +x /tmp/removebackupcode
/tmp/removebackupcode 
rm -rf /tmp/removebackupcode
service crond restart
	fi
	fi
}
check_and_delete_auto_backup_website
check_folder_protect_config
if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
service nginx reload
service php-fpm restart
else 
systemctl reload nginx
systemctl restart php-fpm.service
fi 
rm -rf /tmp/upload*
clear
echo "========================================================================= "
echo "Remove Domain File Manager successfully ! "
vpssim
;;
    *)
    rm -rf /tmp/upload*
       clear 
echo "========================================================================= "
echo "Cancel remove Domain File Manager."
vpssim
        ;;
esac
rm -rf /tmp/upload*
clear 
echo "========================================================================= "
echo "Cancel remove Domain File Manager"
vpssim



