#!/bin/bash

. /home/vpssim.conf

if [ -f /etc/vpssim/Renew.SSL.Letencrypt ] && [ -f /etc/cron.d/vpssim.autorenew.ssl.cron ]; then
clear
echo "========================================================================="
echo "[ Auto Renew Certificate ] function is ENABLED."
echo "-------------------------------------------------------------------------"
echo "VPSSIM auto renew all Certificates 10 days before expiration ."
/etc/vpssim/menu/vpssim-letsencrypt-menu
fi
echo "========================================================================="
echo "Use this function to Enable Auto renew Certificates for domains using"
echo "-------------------------------------------------------------------------"
echo "Certificates by Let's Encrypt."
echo "========================================================================="
  read -r -p "You want to ENABLE auto renew certificates ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
echo "Please wait ..."; sleep 3

cat > "/etc/vpssim/Renew.SSL.Letencrypt" <<END
#!/bin/sh
/root/.acme.sh/acme.sh --renewAll
END
chmod +x /etc/vpssim/Renew.SSL.Letencrypt
echo "SHELL=/bin/sh" > /etc/cron.d/vpssim.autorenew.ssl.cron
echo "0 23 * * * root /etc/vpssim/Renew.SSL.Letencrypt >/dev/null 2>&1" >> /etc/cron.d/vpssim.autorenew.ssl.cron
service crond restart
clear
echo "========================================================================="
echo "Completed config auto renew certificates for all domains."
echo "-------------------------------------------------------------------------"
echo "VPSSIM will auto renew all Certificates 10 days before expiration ."
/etc/vpssim/menu/vpssim-letsencrypt-menu
;;
    *)
clear 
echo "========================================================================= "
echo "Cancel !"
/etc/vpssim/menu/vpssim-letsencrypt-menu
        ;;
esac
