#!/bin/bash 
. /home/vpssim.conf
if [ ! -f /usr/local/maldetect/conf.maldet ]; then
clear
echo "========================================================================= "
echo "LMD with ClamAV is not existed in server "
echo "-------------------------------------------------------------------------"
echo "Please install LMD first !"
/etc/vpssim/menu/vpssim-maldet-menu
exit
fi

maldet --report list > /tmp/maldet.txt
if [ ! -f /usr/local/maldetect/sess/session.last ]; then
clear
echo "========================================================================= "
echo "You have not Scan Server with Maldet yet !"
/etc/vpssim/menu/vpssim-maldet-menu
else
echo "Please wait...";sleep 1 
#name123=$(maldet --report list | awk 'END {print $NF}')
name123=$(cat /usr/local/maldetect/sess/session.last)
rm -rf /tmp/maldet.txt
echo "-------------------------------------------------------------------------"
echo "Please wait..."
sleep 1
rm -rf /tmp/maldet123.txt
cp /usr/local/maldetect/sess/session.$name123 /tmp/maldet123.txt
name123=$(cat /usr/local/maldetect/sess/session.last)
rm -rf /tmp/maldet.txt
cp /usr/local/maldetect/sess/session.$name123 /tmp/maldet123.txt
sed -i '$d' /tmp/maldet123.txt && sed -i '$d' /tmp/maldet123.txt && sed -i '1d' /tmp/maldet123.txt && sed -i '1d' /tmp/maldet123.txt && sed -i '1d' /tmp/maldet123.txt
clear
echo "========================================================================="
echo "Report for last scan on:  $(cat /usr/local/maldetect/sess/session.$name123 | grep TIME: | awk '{print $2,$3,$4}')"
echo "-------------------------------------------------------------------------"
cat /tmp/maldet123.txt | grep '\S'
/etc/vpssim/menu/vpssim-maldet-menu
exit
fi

