#!/bin/sh
prompt="Type in your choice (6-Exit):"
options=("Backup 1 Database" "Backup All Database" "Restore Database" "Get Link Backup Files" "List Databases On Server" "Exit")
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                      Backup & Restore Database\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1 ) /etc/vpssim/menu/vpssim-sao-luu-data;;
    2 ) /etc/vpssim/menu/vpssim-lan-luot-sao-luu-het-tat-ca-database;;
    3 ) /etc/vpssim/menu/vpssim-phuc-hoi-database-chon-dinh-dang;;
    4 ) /etc/vpssim/menu/vpssim-lay-link-sao-luu-database-backup-menu;;
    5 ) /etc/vpssim/menu/vpssim-list-database-tren-vps;; 
    6 ) clear && /etc/vpssim/menu/vpssim-them-xoa-database;;

    
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done
