#!/bin/sh
. /home/vpssim.conf
nhapwebsite ()
{
echo -n "Type in website [ENTER]: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
}
echo "========================================================================="
echo "Use this function to restore website from backup file"
echo "-------------------------------------------------------------------------"
echo -n "Type in website: " 
read website
website=`echo $website | tr '[A-Z]' '[a-z]'`
if [ "$website" = "" ]; then
echo "========================================================================="
echo "You typed wrong, Please fill accurately"
echo "-------------------------------------------------------------------------"
nhapwebsite
fi
kiemtradomain3="^([[:alnum:]]([[:alnum:]\-]{0,61}[[:alnum:]])?\.)+[[:alpha:]]{2,12}$";
if [[ ! "$website" =~ $kiemtradomain3 ]]; then
	website=`echo $website | tr '[A-Z]' '[a-z]'`
echo "========================================================================="
echo "$website maybe not a domain name!"
echo "-------------------------------------------------------------------------"
nhapwebsite
fi
if [ ! -d /home/$website/public_html ]; then
echo "========================================================================="
echo "Can not discover $website on server"
echo "-------------------------------------------------------------------------"
nhapwebsite
fi
if [ ! -f /home/$mainsite/private_html/backup/$website/*.zip ]; then
clear
echo "========================================================================="
echo "Can not find the backup of $website on server !"
echo "-------------------------------------------------------------------------"
echo "Upload backup file .ZIP to folder below then do this function again: "
echo "-------------------------------------------------------------------------"
echo "/home/$mainsite/private_html/backup/$website"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi

find /home/$mainsite/private_html/backup/$website/ -name '*.zip' -type f -exec basename {} \;  > /tmp/backupname
if [ ! "$(cat /tmp/backupname | wc -l)" == "1" ]; then
clear
echo "========================================================================="
echo "There are more than 1 backup file in .ZIP format in: "
echo "-------------------------------------------------------------------------"
echo "/home/$mainsite/private_html/backup/$website"
echo "-------------------------------------------------------------------------"
echo "Please leave only one file .ZIP in this folder"
/etc/vpssim/menu/vpssim-sao-luu
exit
fi
filename=`cat /tmp/backupname`
rm -rf /tmp/backupname
websiteTO=`echo $website | tr '[a-z]' '[A-Z]'`
echo "========================================================================="
echo "Discovered the backup file of $website: $filename "
echo "-------------------------------------------------------------------------"
echo "File created on: $(date -r /home/$mainsite/private_html/backup/$website/$filename +%H:%M/%F)"
echo "========================================================================="
echo "CHOOSE HOW TO RECOVER $websiteTO"
echo "========================================================================="
prompt="Type in your choice (3-Exit): "
options=("Keep All Existing Data And Overwrite Them From Backup Files" "Delete All Existing Data And Recover From The Backup" "Exit")
PS3="$prompt"
select opt in "${options[@]}"; do 
case "$REPLY" in
1) luachon="restore1"; break;;
2) luachon="restore2"; break;;
3) clear && /etc/vpssim/menu/vpssim-sao-luu;;  
*) echo "You typed wrong, Please type in the ordinal number on the list !";continue;;
esac   
done
if [ "$luachon" = "restore2" ]; then
echo "========================================================================="
echo "DO NOT turn off SSH screen in recover process !"
echo "========================================================================="
echo "VPSSIM will delete all current data (Code,images,files..) "
echo "-------------------------------------------------------------------------"
echo "And recover data from backup file. This process can not be reversed"
echo "-------------------------------------------------------------------------"
echo "Press [ Enter ] to start recover, Press any others key to cancle."
echo "========================================================================="
read -n1 -r -p "Press [Enter] to start recover ..." key
if [[ ! $key = "" ]]; then
clear
echo "========================================================================="
echo "Cancel recover $website"
/etc/vpssim/menu/vpssim-sao-luu
fi
echo ""
echo "Please wait..."
sleep 1
mv /home/$website/public_html /home/$website/public_html_backup
mkdir /home/$website/public_html
cd /home/$mainsite/private_html/backup/$website
unzip $filename -d /home/$website/public_html
cd	
chown -R nginx:nginx /home/$website/public_html
if [ -f /home/$website/public_html/index.php ]; then 
rm -rf /home/$website/public_html_backup 
	if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	service php-fpm restart
	service nginx restart
	touch /var/cache/ngx_pagespeed/cache.flush
	( echo "flushall" ) | redis-cli
	else
	systemctl restart php-fpm.service
	systemctl restart nginx.service
	touch /var/cache/ngx_pagespeed/cache.flush
	( echo "flushall" ) | redis-cli
	fi
clear
echo "========================================================================="
echo "Recovery $website completed ! "
/etc/vpssim/menu/vpssim-sao-luu
else
rm -rf /home/$website/public_html
mv /home/$website/public_html_backup /home/$website/public_html
clear
echo "========================================================================="
echo "There's something wrong with your backup file"
echo "-------------------------------------------------------------------------"
echo "Recover $website failed."
/etc/vpssim/menu/vpssim-sao-luu
fi
fi
if [ "$luachon" = "restore1" ]; then
echo "========================================================================="
echo "DO NOT turn off SSH screen in recover process !"
echo "========================================================================="
echo "VPSSIM will overwrite all current data (Code,images,files..) by the backup "
echo "-------------------------------------------------------------------------"
echo "This process can not be reversed. "
echo "-------------------------------------------------------------------------"
echo "Press [ Enter ] to start recover, Press any others key to cancle."
echo "========================================================================="
read -n1 -r -p "Press [Enter] to start recover ..." key
if [[ ! $key = "" ]]; then
clear
echo "========================================================================="
echo "Cancel recover $website"
/etc/vpssim/menu/vpssim-sao-luu
fi
echo ""
echo "Please wait..."
sleep 1
rm -rf /tmp/websiterestore
mkdir -p /tmp/websiterestore
cd /home/$mainsite/private_html/backup/$website
unzip -o $filename -d /tmp/websiterestore
cd
if [ ! -f /tmp/websiterestore/index.php ]; then
rm -rf /tmp/websiterestore
clear
echo "========================================================================="
echo "There's something wrong with your backup file"
echo "-------------------------------------------------------------------------"
echo "Recover $website failed."
/etc/vpssim/menu/vpssim-sao-luu
else
yes | cp -rf /tmp/websiterestore/*.* /home/$website/public_html
yes | cp -rf /tmp/websiterestore/* /home/$website/public_html
rm -rf /tmp/websiterestore
chown -R nginx:nginx /home/$website/public_html
	if [ "$(rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release))" == "6" ]; then 
	service php-fpm restart
	service nginx restart
	touch /var/cache/ngx_pagespeed/cache.flush
	( echo "flushall" ) | redis-cli
	else
	systemctl restart php-fpm.service
	systemctl restart nginx.service
	touch /var/cache/ngx_pagespeed/cache.flush
	( echo "flushall" ) | redis-cli
	fi
clear
echo "========================================================================="
echo "Recovery $website completed ! "
/etc/vpssim/menu/vpssim-sao-luu
fi 
fi



