#!/bin/bash
. /home/vpssim.conf
rm -rf /tmp/*hostingaz*
code=`date |md5sum |cut -c '1-12'`
ls -l /var/lib/mysql | grep "^d" | awk -F" " '{print $9}' | grep -Ev "(Database|information_schema|mysql|performance_schema|vpssimCheckDB)" > /tmp/listdabasehostingaz
checksize=$(du -sb /tmp/listdabasehostingaz | awk 'NR==1 {print $1}')
   if [ "$checksize" == "0" ]; then
   clear
   echo "========================================================================="
   echo "There's no database has data on system !"
   /etc/vpssim/menu/vpssim-them-xoa-database
   exit
   fi
sodatabasetrenserver=$(cat /tmp/listdabasehostingaz | wc -l)
listdatabasetrenserver=$(cat /tmp/listdabasehostingaz)
mkdir -p /tmp/saoluudatabasethanhconghostingaz
mkdir -p /tmp/saoluudatabasethatbaihostingaz
rm -rf /tmp/*check*
for database in $listdatabasetrenserver 
do
if [ ! "$(ls -1 /var/lib/mysql/$database | wc -l)" == "1" ]; then
echo "$database" >> /tmp/checkdatabase-list
fi
 done

if [ ! -f /tmp/checkdatabase-list ]; then
rm -rf /tmp/*hostingaz*
rm -rf /tmp/*list*
clear
echo "========================================================================="
echo "There's no database has data on system !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi

saoluudata ()
{
	echo "-------------------------------------------------------------------------"
echo "Please do not turn off this screen ..."
	if [  -f /bin/vpssim-backupdb-$dataname ]; then
	if [ ! "$(grep /bin/vpssim-backupdb-$dataname /etc/cron.d/vpssim.db.cron)" == "" ]; then
filename2=$(grep "$dataname" /bin/vpssim-backupdb-$dataname | awk 'NR==7 {print $11}')
thongbao=$(echo " ($dataname Enabled Auto Backup)")
	else
filename2=$dataname$abc456.sql.gz
thongbao=$(echo "")
	fi
else
filename2=$dataname$abc456.sql.gz
thongbao=$(echo "")
fi
sleep 1
if [ ! -d /home/$mainsite/private_html/backup/$dataname ]; then
mkdir -p /home/$mainsite/private_html/backup/$dataname
fi
cd /home/$mainsite/private_html/backup/$dataname
rm -rf *.sql.gz
if [ "$(grep "default_storage_engine = MyISAM" /etc/my.cnf.d/server.cnf | awk 'NR==1 {print $3}')" = "MyISAM" ]; then
mysqldump -u root -p$mariadbpass $dataname --lock-tables=false | gzip -6 > $filename2
else
mysqldump -u root -p$mariadbpass $dataname --single-transaction | gzip -6 > $filename2
fi
cd
clear

if [ -f /home/$mainsite/private_html/backup/$dataname/$filename2 ]; then
echo "========================================================================="
echo "Link Backup File$thongbao:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/backup/$dataname/$filename2"
else
echo "========================================================================="
echo "Backup Database $dataname failed"
fi
/etc/vpssim/menu/vpssim-them-xoa-database
}

echo "========================================================================="
echo "Use this function to backup database in server"
echo "-------------------------------------------------------------------------"
echo -n "Type in The Database name [ENTER]: " 
read dataname

if [ -f /var/lib/mysql/$dataname/db.opt ]; then
echo "-------------------------------------------------------------------------"
echo "Discover data $dataname on server"
abc456=-`date |md5sum |cut -c '1-10'`

if [ -f /home/$mainsite/private_html/backup/$dataname/*.sql.gz ]; then
find /home/$mainsite/private_html/backup/$dataname -name '*.sql.gz' -type f -exec basename {} \;  > /tmp/backupname
filename=`cat /tmp/backupname`
rm -rf /tmp/backupname
echo "--------------------------------------------------------------------------"
echo "Discover the old backup file: $filename"
echo "--------------------------------------------------------------------------"
echo "Backup file created on: $(date -r /home/$mainsite/private_html/backup/$dataname/$filename +%H:%M/%F)"
echo "--------------------------------------------------------------------------"

read -r -p "Delete it and create new backup file ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
	echo "Backup data $dataname ..."
	saoluudata
        ;;
    *)
rm -rf /tmp/vpssim_ten_file_cu
if [ ! -d /home/$mainsite/private_html/backup/$dataname ]; then
mkdir -p /home/$mainsite/private_html/backup/$dataname
fi
cd /home/$mainsite/private_html/backup/$dataname
if [ -f /home/$mainsite/private_html/backup/$dataname/*.sql.gz ]; then
for file in *.sql.gz; do
time=$(date -r /home/$mainsite/private_html/backup/$dataname/$file +%H%M-%d%m%y)
    mv "$file" "`basename $file .sql.gz`.sql.gz.$time"
    echo "$file.$time" > /tmp/vpssim_ten_file_cu
done
fi
cd
echo "-------------------------------------------------------------------------"
echo "VPSSIM Will Rename Old Backup File To:"
echo "-------------------------------------------------------------------------"
echo "`cat /tmp/vpssim_ten_file_cu`"
echo "-------------------------------------------------------------------------"
echo "Then Create Backup File For $dataname"
echo "-------------------------------------------------------------------------"
echo "Please do not turn off this screen ..."
sleep 6
	if [  -f /bin/vpssim-backupdb-$dataname ]; then
	if [ ! "$(grep /bin/vpssim-backupdb-$dataname /etc/cron.d/vpssim.db.cron)" == "" ]; then
filename2=$(grep "$dataname" /bin/vpssim-backupdb-$dataname | awk 'NR==7 {print $11}')
thongbao=$(echo " ($dataname Enabled Auto Backup)")
	else
filename2=$dataname$abc456.sql.gz
thongbao=$(echo "")
	fi
else
filename2=$dataname$abc456.sql.gz
thongbao=$(echo "")
fi
sleep 1
if [ ! -d /home/$mainsite/private_html/backup/$dataname ]; then
mkdir -p /home/$mainsite/private_html/backup/$dataname
fi
cd /home/$mainsite/private_html/backup/$dataname
if [ "$(grep "default_storage_engine = MyISAM" /etc/my.cnf.d/server.cnf | awk 'NR==1 {print $3}')" = "MyISAM" ]; then
mysqldump -u root -p$mariadbpass $dataname --lock-tables=false | gzip -6 > $filename2
else
mysqldump -u root -p$mariadbpass $dataname --single-transaction | gzip -6 > $filename2
fi
cd
clear
if [ -f /home/$mainsite/private_html/backup/$dataname/$filename2 ]; then
echo "========================================================================="
echo "Link Backup File:"
echo "-------------------------------------------------------------------------"
echo "http://$serverip:$priport/backup/$dataname/$filename2"
echo "-------------------------------------------------------------------------"
echo "Your Old Backup File Was Renamed To:"
echo "-------------------------------------------------------------------------"
echo "$(cat /tmp/vpssim_ten_file_cu)"
rm -rf /tmp/*vpssim*
else
echo "========================================================================="
echo "Backup Database $dataname failed"
fi
/etc/vpssim/menu/vpssim-them-xoa-database
        ;;
esac
else
	echo "Backup data $dataname ..."
	saoluudata
fi

else
clear
echo "========================================================================="
echo "Did not find out database: $dataname on server, please check again!"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
