#!/bin/bash
prompt="Type in your choice (4-Exit):"
options=( "Create domain key & Sign SSL certificate" "Download Domain's CSR & Vhost Sample " "Fix can not download files" "Exit")
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM\n"
printf "=========================================================================\n"
printf "                           Setup SSL (https) \n"
printf "                    See instructions at VPSSIM.COM \n"
printf "=========================================================================\n"
printf "  \n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in
    1) /etc/vpssim/menu/vpssim-tao-ssl;;
    2) /etc/vpssim/menu/vpssim-tao-ssl-link-download-domain-csr;;
    3) /etc/vpssim/menu/vpssim-khong-the-download-csr-file;;
    4) clear && /bin/vpssim;;
        *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac

done



