#!/bin/bash
prompt="Type in your choice (7-Exit):"
options=( "Open Port (INPUT)" "Close Port (INPUT)" "Check services using port" "Backup IPtables rules" "Restore IPtables rules" "View Current IPtables Rules" "Exit" )
printf "=========================================================================\n"
printf "               VPSSIM - Manage VPS/Server by VPSSIM.COM \n"
printf "=========================================================================\n"
printf "                      IPtables Firewall Manage\n"
printf "=========================================================================\n"

PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in


    1) /etc/vpssim/menu/tienich/vpssim-mo-port-ip-tables;;
    2) /etc/vpssim/menu/tienich/vpssim-dong-port-ip-tables;;
    3) /etc/vpssim/menu/tienich/vpssim-check-port-service;;
    4) /etc/vpssim/menu/tienich/vpssim-sao-luu-iptables;;
    5) /etc/vpssim/menu/tienich/vpssim-phuc-hoi-iptables;;
    6) /etc/vpssim/menu/tienich/vpssim-view-iptables-rules;;
    7) clear && /bin/vpssim;;

            *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac
done










