#!/bin/sh
. /home/vpssim.conf
prompt="Type in your choice: "
if [ "$(redis-cli ping)" = "PONG" ]; then
redistatus=Working
else
redistatus=Stopped
fi
options=("Clear Redis Cache" "Config Redis" "Check Redis Status" "Exit")
printf "=========================================================================\n"
printf "                VPSSIM - Manage VPS/Server by VPSSIM.COM                \n"
printf "=========================================================================\n"
printf "                          Redis Cache Manage                                \n"
printf "=========================================================================\n"
printf "          Redis: $redistatus - Ram Max: $(grep maxmemory /etc/redis/redis.conf | awk 'NR==1 {print $2}' | sed 's/mb//') M  - Ram Using: $(redis-cli INFO | grep used_memory_human | sed 's/used_memory_human://') \n"
printf "=========================================================================\n"


PS3="$prompt"
select opt in "${options[@]}" ; do 

    case "$REPLY" in

    1) /etc/vpssim/menu/vpssim-clear-redis;;
    2) /etc/vpssim/menu/vpssim-redis-change-size;;
    3) /etc/vpssim/menu/vpssim-check-redis-status;;
    4) clear && vpssim;; 
    *) echo "You typed wrong, Please type in the ordinal number on the list";continue;;

    esac
done
 
