#!/bin/bash 
. /home/vpssim.conf
if [ ! -f /etc/vpssim/vps_backup_rsync.info ]; then
clear
echo "========================================================================="
echo "This server has not configured connect to VPS Backup yet"
echo "-------------------------------------------------------------------------"
echo "You do not need to run this function."
/etc/vpssim/menu/vpssim-rsync-backup-vps-menu
exit
fi

ipvpsbackup=$(grep "ipaddress" /etc/vpssim/vps_backup_rsync.info | awk '{print $3}')
echo "========================================================================="
echo "Use this function to disable connection from current server to vps backup"
echo "-------------------------------------------------------------------------"
echo "After disconnect, the backup process will be stop and data in vps backup"
echo "-------------------------------------------------------------------------"
echo "will not change. If you want to continue backup server, you must reconect"
echo "-------------------------------------------------------------------------"
echo "And re-setting time sync"
echo "-------------------------------------------------------------------------"
read -r -p "You want this server disconect to vps backup ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
    echo "Please wait ... "
    sleep 3
pkill rync
rm -rf ~/.ssh/id_rsa.pub
rm -rf ~/.ssh/id_rsa
echo "sed -i '/$ipvpsbackup/d' ~/.ssh/known_hosts" > /tmp/knownhost_sedit
chmod +x /tmp/knownhost_sedit
/tmp/knownhost_sedit
rm -rf /tmp/knownhost_sedit
rm -rf /etc/vpssim/vps_backup_rsync.info
rm -rf /etc/vpssim/vpssim_backup_VPS_by_rsync 
rm -rf /etc/cron.d/vpssim.rsync.cron  
service crond restart
clear
echo "========================================================================="
echo "Disconnect to vps backup finished ! "
  /etc/vpssim/menu/vpssim-befor-rsync
    ;;
*)
clear
echo "========================================================================="
echo "Cancel disconect to vps backup !"
  /etc/vpssim/menu/vpssim-rsync-backup-vps-menu
  exit
;;
esac
exit
