#!/bin/sh
. /home/vpssim.conf
echo "========================================================================= "
echo "use this function to change password for user root of MySQL"
echo "-------------------------------------------------------------------------"
read -r -p "You want to change password for user root ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
sleep 1
echo "-------------------------------------------------------------------------"
echo -n "Type in new password [ENTER]: " 
read PASS1
if [ "$PASS1" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, please type in accurately !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
if [ "$PASS1" = "$mariadbpass" ]; then
clear
echo "========================================================================="
echo "New Password is the same with old password"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
checkpass="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
if [[ ! "$PASS1" =~ $checkpass ]]; then
clear
echo "========================================================================="
echo "Change password for MySQL root user failed !"
echo "-------------------------------------------------------------------------"
echo "You must use only numbers, letters to set password !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi 
echo "-------------------------------------------------------------------------"
echo -n "Retype password [ENTER]: " 
read PASS2
if [ "$PASS1" != "$PASS2" ]; then
clear
echo "========================================================================="
echo "Sorry, passwords do not match !"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi 
cat > "/tmp/changemariadbrootpass" <<END
mysqladmin -u root -p$mariadbpass password $PASS1
END
chmod +x /tmp/changemariadbrootpass
/tmp/changemariadbrootpass 

cat > "/tmp/removelinemariadb" <<END
sed --in-place '/mariadbpass/d' /home/vpssim.conf
END
chmod +x /tmp/removelinemariadb
/tmp/removelinemariadb 
 cat >> "/home/vpssim.conf" <<END
mariadbpass="$PASS1"
END
rm -r -f /tmp/removelinemariadb 
rm -r -f /tmp/changemariadbrootpass 
echo "-------------------------------------------------------------------------"
echo "Please wait..."
sleep 1
clear
echo "========================================================================="
echo "Change password for MySQL root user successfully !"
echo "-------------------------------------------------------------------------"
echo "New password has been saved in /home/vpssim.conf"
/etc/vpssim/menu/vpssim-them-xoa-database
;;
esac
clear
echo "========================================================================="
echo "You cancel change password for MySQL user root!"
/etc/vpssim/menu/vpssim-them-xoa-database



