#!/bin/bash

. /home/vpssim.conf
echo "========================================================================="
echo "Use this function to create new database in server"
echo "-------------------------------------------------------------------------"
echo "Database, Username & password must be 6-16 characters long."
echo "-------------------------------------------------------------------------"
echo -n "Type in database name [ENTER]: " 
read dataname
dataname=`echo $dataname | tr '[A-Z]' '[a-z]'`
if [ "$dataname" = "" ]; then
clear
echo "========================================================================="
echo "You typed wrong, Please type in accurately"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
if [[ $dataname =~ ^[0-9]+$ ]]; then
clear
echo "========================================================================="
echo "You may not use only number for naming database."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi

if [[ ${#dataname} -ge 16 ]]; then
clear
echo "========================================================================="
echo "The maximum length of dataname is 16 characters ."
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi

kiemtradata="^[a-zA-Z0-9_][-a-zA-Z0-9_]{0,61}[a-zA-Z0-9_]$";
if [[ ! "$dataname" =~ $kiemtradata ]]; then
	
clear
echo "========================================================================="
echo "Create $dataname failed! "
echo "-------------------------------------------------------------------------"
echo "You must use only numbers, letters and character: _  "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi 

if [[ ! ${#dataname} -ge 5 ]]; then
clear
echo "========================================================================="
echo "Create $dataname is failed!"
echo "-------------------------------------------------------------------------"
echo "The name of Database must be at least 5 characters long "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi  
if [ -f /var/lib/mysql/$dataname/db.opt ]; then
clear
echo "========================================================================="
echo "Data $dataname is existed on server"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
    cat > "/tmp/config.temp" <<END
CREATE DATABASE $dataname COLLATE utf8_general_ci;
END

mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp
if [ ! -f /var/lib/mysql/$dataname/db.opt ]; then
clear
echo "========================================================================="
echo "Create Data $dataname failed."
echo "-------------------------------------------------------------------------"
echo "Please check you MySQL service !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
echo "-------------------------------------------------------------------------"
echo "Create data $dataname successfully !"
echo "-------------------------------------------------------------------------"
echo "Default Charset is utf8 !"
echo "========================================================================="
read -r -p "Do you want to create new user for $dataname ? [y/N] " response
case $response in
    [yY][eE][sS]|[yY]) 
    echo "-------------------------------------------------------------------------"
	echo -n "Type username [ENTER]: " 
	read username
	username=`echo $username | tr '[A-Z]' '[a-z]' | cut -c1-16`
	if [ "$username" = "" ]; then
		username="$dataname"
		echo "-------------------------------------------------------------------------"
		echo "You typed wrong, we will name username is $dataname"
	fi
	echo "-------------------------------------------------------------------------"
	echo -n "Type password [ENTER]: " 
	read password
		if ! [[ ${#password} -ge 6 && ${#password} -le 16  ]] ; then
	
	 cat > "/tmp/config.temp" <<END
drop database $dataname;
END
mysql -u root -p$mariadbpass < /tmp/config.temp
rm -f /tmp/config.temp
clear
echo "========================================================================="
echo "Create $dataname is failed!"
echo "-------------------------------------------------------------------------"
echo "The password must be 6-16 characters long "
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi  

 cat > "/tmp/config.temp" <<END
CREATE USER '$username'@'localhost' IDENTIFIED BY '$password';
END

	mysql -u root -p$mariadbpass < /tmp/config.temp
	rm -f /tmp/config.temp

    cat > "/tmp/config.temp" <<END
GRANT ALL PRIVILEGES ON $dataname . * TO '$username'@'localhost';
END
	mysql -u root -p$mariadbpass < /tmp/config.temp
	rm -f /tmp/config.temp

    cat > "/tmp/config.temp" <<END
FLUSH PRIVILEGES;
END
	mysql -u root -p$mariadbpass < /tmp/config.temp
	rm -f /tmp/config.temp
	
echo "=========================================================================" >> /home/DBinfo.txt
echo "Database: $dataname - Created on: $(date +%d/%m/%Y)" >> /home/DBinfo.txt
echo "=========================================================================" >> /home/DBinfo.txt
echo "Data name: $dataname" >> /home/DBinfo.txt
echo "Username: $username" >> /home/DBinfo.txt
echo "password: $password" >> /home/DBinfo.txt
echo "" >> /home/DBinfo.txt
if [ ! -f /var/lib/mysql/$dataname/db.opt ]; then
clear
echo "========================================================================="
echo "Create $dataname is failed!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
if [ ! -f /var/lib/mysql/$dataname/db.opt ]; then
clear
echo "========================================================================="
echo "Create $dataname is failed!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
clear
echo "========================================================================="
echo "Created Database $dataname successfully. Database info:"
echo "-------------------------------------------------------------------------"
echo "Database: $dataname"
echo "-------------------------------------------------------------------------" 
echo "Username: $username | Password: $password" 
echo "-------------------------------------------------------------------------"
echo "Database's infomation saved in: /home/DBinfo.txt"
/etc/vpssim/menu/vpssim-them-xoa-database
            ;;
    *)

echo "=========================================================================" >> /home/DBinfo.txt
echo "Database: $dataname - Created on: $(date +%d/%m/%Y)" >> /home/DBinfo.txt
echo "=========================================================================" >> /home/DBinfo.txt
echo "Databasae: $dataname" >> /home/DBinfo.txt
echo "Username: root" >> /home/DBinfo.txt
echo "password: $mariadbpass" >> /home/DBinfo.txt
echo "" >> /home/DBinfo.txt

	echo ""
        ;;
esac
if [ ! -f /var/lib/mysql/$dataname/db.opt ]; then
clear
echo "========================================================================="
echo "Create $dataname is failed!"
echo "-------------------------------------------------------------------------"
echo "Please try again !"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
clear
echo "========================================================================="
echo "Created Database $dataname successfully. Database info:"
echo "-------------------------------------------------------------------------" 
echo "Data Name: $dataname"
echo "-------------------------------------------------------------------------" 
echo "Username: root | Password: $mariadbpass" 
echo "-------------------------------------------------------------------------"
echo "Database's infomation saved in: /home/DBinfo.txt"
/etc/vpssim/menu/vpssim-them-xoa-database
exit
fi
