#!/bin/bash
. /home/vpssim.conf
random=`date |md5sum |cut -c '1-10'`
echo "-------------------------------------------------------------------------"
echo "Please wait ..."
sleep 1
echo "-------------------------------------------------------------------------"
if [ -f /home/$mainsite/logs/php-fpm-slow.log ]; then
minimumsize=1024000
 checksize=$(du -sb /home/$mainsite/logs/php-fpm-slow.log | awk 'NR==1 {print $1}')
	if [ "$checksize" = "0" ]; then
	clear
	echo "========================================================================= "
	echo "There's nothing in PHP-FPM Slow log file"
	/etc/vpssim/menu/vpssim-eroor-menu
	fi
	if [ $checksize -ge $minimumsize ]; then
	rm -rf /home/$mainsite/private_html/server-log/php-fpm-slow.log*
	\cp -uf /home/$mainsite/logs/php-fpm-slow.log /home/$mainsite/private_html/server-log
	cd /home/$mainsite/private_html/server-log
		sed -i '1s/^/========================================================================= \n\n/' php-fpm-slow.log
	sed -i '2s/^/PHP-FPM Slow Log - Created by VPSSIM \n\n/' php-fpm-slow.log
	sed -i '3s/^/========================================================================= \n\n/' php-fpm-slow.log
	zip php-fpm-slow.log-$random.zip php-fpm-slow.log
	rm -rf php-fpm-slow.log
	cd
	chmod -R 755 /home/$mainsite/private_html/server-log/*
	clear
	echo "========================================================================= "
	echo "Link download PHP-FPM Slow Log:"
	echo "-------------------------------------------------------------------------"
	echo "http://$serverip:$priport/server-log/php-fpm-slow.log-$random.zip"
	/etc/vpssim/menu/vpssim-eroor-menu
  else
    rm -rf /home/$mainsite/private_html/server-log/php-fpm-slow.log*
	\cp -uf /home/$mainsite/logs/php-fpm-slow.log /home/$mainsite/private_html/server-log/
	cd /home/$mainsite/private_html/server-log
	mv php-fpm-slow.log php-fpm-slow.log-$random.txt	
	sed -i '1s/^/========================================================================= \n\n/' php-fpm-slow.log-$random.txt
	sed -i '2s/^/PHP-FPM Slow Log - Created by VPSSIM \n\n/' php-fpm-slow.log-$random.txt
	sed -i '3s/^/========================================================================= \n\n/' php-fpm-slow.log-$random.txt
	cd
	chmod -R 755 /home/$mainsite/private_html/server-log/*
	clear
	echo "========================================================================= "
	echo "Link view PHP-FPM Slow Log:"
	echo "-------------------------------------------------------------------------"
	echo "http://$serverip:$priport/server-log/php-fpm-slow.log-$random.txt"
	/etc/vpssim/menu/vpssim-eroor-menu
  fi 
else
clear
echo "========================================================================= "
echo "Log file does not exist or you disable write logfile"
/etc/vpssim/menu/vpssim-eroor-menu
fi 
