#!/bin/sh
. /home/vpssim.conf
echo "-------------------------------------------------------------------------"
echo "Please wait...."
sleep 1
if [ "$(ls -1 /home/$mainsite/private_html/server-log | wc -l)" == "0" ]; then
clear
echo "========================================================================= "
echo "Can not discover download link for log file."
/etc/vpssim/menu/vpssim-eroor-menu
fi
rm -rf /home/$mainsite/private_html/server-log/*.*
clear
echo "========================================================================= "
echo "Delete all LOG download link successfully"
/etc/vpssim/menu/vpssim-eroor-menu


